# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//build_tools/bazel:cmake.bzl", "iree_cmake_extra_content")
load("//build_tools/bazel:generate.bzl", "iree_generated_files")
load("//build_tools/embed_data:build_defs.bzl", "iree_c_embed_data")
load("//runtime/build_tools/bazel:cc.bzl", "iree_runtime_cc_library")
load("//runtime/build_tools/bazel:cc_benchmark.bzl", "iree_runtime_cc_benchmark")
load("//runtime/build_tools/bazel:cc_fuzz.bzl", "iree_runtime_cc_fuzz")
load("//runtime/build_tools/bazel:cc_test.bzl", "iree_runtime_cc_test")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = ["notice"],
)

iree_generated_files(
    name = "projections",
    outs = [
        "disassembler/data.inl",
        "docs/specification.md",
        "testdata/core_execution.vmfb",
        "testdata/structural.vmfb",
        "verifier/data.c",
        "verifier/instruction_cases.inl",
        "verifier/module_cases.inl",
        "wire/assertions.c",
        "wire/core.h",
        "wire/module.h",
    ],
    output_args = {
        "disassembler/data.inl": "--disassembler-data={path}",
        "docs/specification.md": "--documentation={path}",
        "testdata/core_execution.vmfb": "--core-execution-module-fixture={path}",
        "testdata/structural.vmfb": "--structural-module-fixture={path}",
        "verifier/data.c": "--verifier-source={path}",
        "verifier/instruction_cases.inl": "--instruction-verifier-cases={path}",
        "verifier/module_cases.inl": "--module-verifier-cases={path}",
        "wire/assertions.c": "--wire-assertions-source={path}",
        "wire/core.h": "--wire-core-header={path}",
        "wire/module.h": "--wire-module-header={path}",
    },
    tags = ["skip-bazel_to_cmake"],
    tool = "//runtime/src/iree/vm/bytecode/spec:generate",
)

iree_runtime_cc_library(
    name = "wire",
    srcs = ["wire/assertions.c"],
    hdrs = [
        "wire/core.h",
        "wire/module.h",
    ],
    deps = ["//runtime/src/iree/base:core_headers"],
)

iree_c_embed_data(
    name = "execution_testdata",
    testonly = True,
    srcs = ["testdata/core_execution.vmfb"],
    c_file_output = "execution_testdata.c",
    flatten = True,
    h_file_output = "execution_testdata.h",
    identifier = "iree_vm_bytecode_execution_testdata",
)

iree_c_embed_data(
    name = "verifier_testdata",
    testonly = True,
    srcs = ["testdata/structural.vmfb"],
    c_file_output = "verifier_testdata.c",
    flatten = True,
    h_file_output = "verifier_testdata.h",
    identifier = "iree_vm_bytecode_verifier_testdata",
)

iree_runtime_cc_library(
    name = "verifier_data",
    srcs = ["verifier/data.c"],
    hdrs = ["verifier_data.h"],
    deps = [
        ":wire",
        "//runtime/src/iree/base:core_headers",
    ],
)

iree_runtime_cc_library(
    name = "verifier",
    srcs = ["verifier.c"],
    hdrs = [
        "layout.h",
        "verifier.h",
    ],
    textual_hdrs = [
        "verifier/instruction_cases.inl",
        "verifier/module_cases.inl",
    ],
    deps = [
        ":verifier_data",
        ":wire",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal:unicode",
        "//runtime/src/iree/vm",
    ],
)

iree_runtime_cc_library(
    name = "disassembler",
    srcs = ["disassembler.c"],
    hdrs = ["disassembler.h"],
    textual_hdrs = ["disassembler/data.inl"],
    deps = [
        ":wire",
        "//runtime/src/iree/base",
    ],
)

iree_runtime_cc_test(
    name = "verifier_test",
    srcs = ["verifier_test.cc"],
    deps = [
        ":execution_testdata",
        ":verifier",
        ":verifier_data",
        ":verifier_testdata",
        ":wire",
        "//runtime/src/iree/base",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
    ],
)

iree_runtime_cc_benchmark(
    name = "verifier_benchmark",
    srcs = ["verifier_benchmark.cc"],
    deps = [
        ":verifier",
        ":verifier_testdata",
        "//runtime/src/iree/base",
        "//runtime/src/iree/testing:benchmark",
        "//runtime/src/iree/testing:benchmark_main",
    ],
)

iree_runtime_cc_fuzz(
    name = "verifier_fuzz",
    srcs = ["verifier_fuzz.cc"],
    deps = [
        ":verifier",
        ":verifier_testdata",
        "//runtime/src/iree/base",
    ],
)

iree_runtime_cc_test(
    name = "disassembler_test",
    srcs = ["disassembler_test.cc"],
    deps = [
        ":disassembler",
        ":wire",
        "//runtime/src/iree/base",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
    ],
)

test_suite(
    name = "tests",
    tests = [
        ":disassembler_test",
        ":verifier_test",
    ],
)

iree_cmake_extra_content(
    content = """
iree_py_generated_files(
  NAME
    projections
  GENERATOR
    iree::vm::bytecode::spec::generate
  OUTPUTS
    "docs/specification.md"
    "disassembler/data.inl"
    "testdata/core_execution.vmfb"
    "testdata/structural.vmfb"
    "verifier/data.c"
    "verifier/instruction_cases.inl"
    "verifier/module_cases.inl"
    "wire/assertions.c"
    "wire/core.h"
    "wire/module.h"
  OUTPUT_FLAGS
    "--documentation"
    "--disassembler-data"
    "--core-execution-module-fixture"
    "--instruction-verifier-cases"
    "--module-verifier-cases"
    "--structural-module-fixture"
    "--verifier-source"
    "--wire-assertions-source"
    "--wire-core-header"
    "--wire-module-header"
  COMMENT
    "Generating VM bytecode specification projections"
)
""",
    inline = True,
)
