# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//build_tools/bazel:cmake.bzl", "iree_cmake_extra_content")
load("//build_tools/bazel:generate.bzl", "iree_generated_files")
load("//runtime/build_tools/bazel:cc.bzl", "iree_runtime_cc_library")
load("//runtime/build_tools/bazel:cc_benchmark.bzl", "iree_runtime_cc_benchmark")
load("//runtime/build_tools/bazel:cc_fuzz.bzl", "iree_runtime_cc_fuzz")
load("//runtime/build_tools/bazel:cc_test.bzl", "iree_runtime_cc_test")

package(
    default_visibility = ["//visibility:private"],
    features = ["layering_check"],
    licenses = ["notice"],
)

iree_generated_files(
    name = "tables_gen",
    outs = [
        "execution_tables.inl",
        "tooling/isa_tables.c.inc",
        "tooling/module_tables.c.inc",
    ],
    args = ["--output-kind=tables"],
    output_args = {
        "execution_tables.inl": "--output-file=execution_tables.inl={path}",
        "isa_tables.c.inc": "--output-file=isa_tables.c.inc={path}",
        "module_tables.c.inc": "--output-file=module_tables.c.inc={path}",
    },
    tags = ["skip-bazel_to_cmake"],
    tool = "//runtime/src/iree/vm/bytecode/spec:generate",
)

iree_cmake_extra_content(
    content = """
iree_py_generated_files(
  NAME tables_gen
  GENERATOR iree::vm::bytecode::spec::generate
  OUTPUTS
    execution_tables.inl
    tooling/isa_tables.c.inc
    tooling/module_tables.c.inc
  OUTPUT_FLAGS
    --output-file=execution_tables.inl
    --output-file=isa_tables.c.inc
    --output-file=module_tables.c.inc
  ARGS --output-kind=tables
)
""",
    inline = True,
)

iree_runtime_cc_library(
    name = "module",
    srcs = [
        "image.c",
        "module_reflection.c",
        "verification.c",
    ],
    hdrs = [
        "image.h",
        "module_reader.h",
        "module_reflection.h",
        "module_storage.h",
        "storage.h",
        "verification.h",
    ],
    visibility = ["//visibility:private"],
    deps = [
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal",
        "//runtime/src/iree/base/internal:unicode",
        "//runtime/src/iree/vm",
        "//runtime/src/iree/vm/bytecode/wire",
    ],
)

iree_runtime_cc_library(
    name = "bytecode",
    srcs = [
        "interpreter.c",
        "interpreter.h",
        "interpreter_atomic.c",
        "interpreter_atomic.h",
        "interpreter_buffer.h",
        "interpreter_call.c",
        "interpreter_call.h",
        "interpreter_float.h",
        "interpreter_float_math.c",
        "interpreter_float_math.h",
        "interpreter_frame.c",
        "interpreter_frame.h",
        "interpreter_integer.h",
        "interpreter_integer_dispatch.c.inc",
        "interpreter_stack.h",
        "module.c",
        "verification_isa.c",
        "verification_isa_buffer.c",
        "verification_isa_buffer.h",
        "verification_isa_registers.c",
        "verification_isa_registers.h",
        "verification_isa_stack.c",
        "verification_isa_stack.h",
    ],
    hdrs = ["module.h"],
    textual_hdrs = ["execution_tables.inl"],
    visibility = ["//visibility:public"],
    deps = [
        ":module",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base:core_headers",
        "//runtime/src/iree/base/internal",
        "//runtime/src/iree/base/internal:unicode",
        "//runtime/src/iree/vm",
        "//runtime/src/iree/vm/bytecode/wire",
    ],
)

iree_runtime_cc_library(
    name = "inspection",
    srcs = ["inspection.c"],
    hdrs = ["inspection.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":module",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal",
        "//runtime/src/iree/base/internal:unicode",
        "//runtime/src/iree/vm",
    ],
)

iree_runtime_cc_library(
    name = "dump",
    srcs = [
        "tooling/disassembler.c",
        "tooling/disassembler.h",
        "tooling/dump.c",
    ],
    hdrs = ["tooling/dump.h"],
    textual_hdrs = [
        "tooling/isa_tables.c.inc",
        "tooling/module_tables.c.inc",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":inspection",
        ":module",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal",
        "//runtime/src/iree/vm",
        "//runtime/src/iree/vm/bytecode/wire",
    ],
)

iree_runtime_cc_test(
    name = "interpreter_atomic_test",
    srcs = [
        "interpreter_atomic.h",
        "interpreter_atomic_test.cc",
        "interpreter_buffer.h",
    ],
    deps = [
        ":bytecode",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base:core_headers",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
        "//runtime/src/iree/vm",
        "//runtime/src/iree/vm/bytecode/wire",
    ],
)

iree_runtime_cc_test(
    name = "interpreter_float_test",
    srcs = [
        "interpreter_float.h",
        "interpreter_float_test.cc",
    ],
    deps = [
        "//runtime/src/iree/base",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
        "//runtime/src/iree/vm/bytecode/wire",
    ],
)

iree_runtime_cc_test(
    name = "interpreter_float_math_test",
    srcs = [
        "interpreter_float_math.h",
        "interpreter_float_math_test.cc",
    ],
    deps = [
        ":bytecode",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal:fpu_state",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
        "//runtime/src/iree/vm/bytecode/wire",
    ],
)

iree_runtime_cc_test(
    name = "interpreter_integer_test",
    srcs = [
        "interpreter_integer.h",
        "interpreter_integer_test.cc",
    ],
    deps = [
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
        "//runtime/src/iree/vm/bytecode/wire",
    ],
)

iree_runtime_cc_test(
    name = "interpreter_stack_test",
    srcs = [
        "interpreter_stack.h",
        "interpreter_stack_test.cc",
    ],
    deps = [
        "//runtime/src/iree/base",
        "//runtime/src/iree/base:core_headers",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
        "//runtime/src/iree/vm/bytecode/wire",
    ],
)

iree_runtime_cc_test(
    name = "module_test",
    srcs = [
        "module_test.cc",
        "module_test_data.cc",
        "module_test_data.h",
    ],
    deps = [
        ":bytecode",
        ":inspection",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
        "//runtime/src/iree/vm",
        "//runtime/src/iree/vm/bytecode/wire",
    ],
)

iree_runtime_cc_test(
    name = "module_call_test",
    srcs = [
        "module_call_test.cc",
        "module_test_data.cc",
        "module_test_data.h",
    ],
    deps = [
        ":bytecode",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
        "//runtime/src/iree/vm",
        "//runtime/src/iree/vm/bytecode/wire",
    ],
)

iree_runtime_cc_test(
    name = "module_buffer_test",
    srcs = [
        "interpreter_atomic.h",
        "module_buffer_test.cc",
        "module_test_data.cc",
        "module_test_data.h",
    ],
    deps = [
        ":bytecode",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
        "//runtime/src/iree/vm",
        "//runtime/src/iree/vm/bytecode/wire",
    ],
)

iree_runtime_cc_test(
    name = "dump_test",
    srcs = [
        "module_test_data.cc",
        "module_test_data.h",
        "tooling/dump_test.cc",
    ],
    deps = [
        ":dump",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
        "//runtime/src/iree/vm/bytecode/wire",
    ],
)

iree_runtime_cc_fuzz(
    name = "instruction_fuzz",
    srcs = [
        "instruction_fuzz.cc",
        "module_test_data.cc",
        "module_test_data.h",
    ],
    deps = [
        ":bytecode",
        ":dump",
        ":inspection",
        "//runtime/src/iree/base",
        "//runtime/src/iree/vm",
        "//runtime/src/iree/vm/bytecode/wire",
    ],
)

iree_runtime_cc_benchmark(
    name = "module_benchmark",
    srcs = [
        "module_benchmark.cc",
        "module_test_data.cc",
        "module_test_data.h",
    ],
    deps = [
        ":bytecode",
        "//runtime/src/iree/testing:benchmark",
        "//runtime/src/iree/testing:benchmark_main",
        "//runtime/src/iree/vm",
        "//runtime/src/iree/vm/bytecode/wire",
    ],
)
