// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#include "iree/vm/bytecode/interpreter_float_math.h"

#include <math.h>
#include <string.h>

#include "iree/vm/bytecode/wire/core.h"

#define IREE_VM_BYTECODE_FLOAT_MATH_NAME_CONCAT_(name, width) \
  iree_vm_bytecode_float_math_##name##_##width
#define IREE_VM_BYTECODE_FLOAT_MATH_NAME_EXPAND_(name, width) \
  IREE_VM_BYTECODE_FLOAT_MATH_NAME_CONCAT_(name, width)
#define IREE_VM_BYTECODE_FLOAT_MATH_NAME(name)   \
  IREE_VM_BYTECODE_FLOAT_MATH_NAME_EXPAND_(name, \
                                           IREE_VM_BYTECODE_FLOAT_MATH_WIDTH)
#define IREE_VM_BYTECODE_FLOAT_MATH_LIBM_CONCAT_(name, suffix) name##suffix
#define IREE_VM_BYTECODE_FLOAT_MATH_LIBM_EXPAND_(name, suffix) \
  IREE_VM_BYTECODE_FLOAT_MATH_LIBM_CONCAT_(name, suffix)
#define IREE_VM_BYTECODE_FLOAT_MATH_LIBM(name) \
  IREE_VM_BYTECODE_FLOAT_MATH_LIBM_EXPAND_(    \
      name, IREE_VM_BYTECODE_FLOAT_MATH_LIBM_SUFFIX)

#define IREE_VM_BYTECODE_FLOAT_MATH_WIDTH f32
#define IREE_VM_BYTECODE_FLOAT_MATH_TYPE float
#define IREE_VM_BYTECODE_FLOAT_MATH_BITS_TYPE uint32_t
#define IREE_VM_BYTECODE_FLOAT_MATH_LITERAL_(value) value##f
#define IREE_VM_BYTECODE_FLOAT_MATH_LITERAL(value) \
  IREE_VM_BYTECODE_FLOAT_MATH_LITERAL_(value)
#define IREE_VM_BYTECODE_FLOAT_MATH_LIBM_SUFFIX f
#define IREE_VM_BYTECODE_FLOAT_MATH_MAGNITUDE_MASK UINT32_C(0x7FFFFFFF)
#define IREE_VM_BYTECODE_FLOAT_MATH_SIGN_MASK UINT32_C(0x80000000)
#define IREE_VM_BYTECODE_FLOAT_MATH_INFINITY_BITS UINT32_C(0x7F800000)
#define IREE_VM_BYTECODE_FLOAT_MATH_QUIET_NAN_BITS UINT32_C(0x7FC00000)
#define IREE_VM_BYTECODE_FLOAT_MATH_POSITIVE_ONE_BITS UINT32_C(0x3F800000)
#define IREE_VM_BYTECODE_FLOAT_MATH_NEGATIVE_ONE_BITS UINT32_C(0xBF800000)
#define IREE_VM_BYTECODE_FLOAT_MATH_INVERSE_SQRT2_BITS UINT32_C(0x3F3504F3)
#define IREE_VM_BYTECODE_FLOAT_MATH_GELU_CUBIC_BITS UINT32_C(0x3D372713)
#define IREE_VM_BYTECODE_FLOAT_MATH_SQRT_2_OVER_PI_BITS UINT32_C(0x3F4C422A)
#include "iree/vm/bytecode/interpreter_float_math_impl.inl"
#undef IREE_VM_BYTECODE_FLOAT_MATH_SQRT_2_OVER_PI_BITS
#undef IREE_VM_BYTECODE_FLOAT_MATH_GELU_CUBIC_BITS
#undef IREE_VM_BYTECODE_FLOAT_MATH_INVERSE_SQRT2_BITS
#undef IREE_VM_BYTECODE_FLOAT_MATH_NEGATIVE_ONE_BITS
#undef IREE_VM_BYTECODE_FLOAT_MATH_POSITIVE_ONE_BITS
#undef IREE_VM_BYTECODE_FLOAT_MATH_QUIET_NAN_BITS
#undef IREE_VM_BYTECODE_FLOAT_MATH_INFINITY_BITS
#undef IREE_VM_BYTECODE_FLOAT_MATH_SIGN_MASK
#undef IREE_VM_BYTECODE_FLOAT_MATH_MAGNITUDE_MASK
#undef IREE_VM_BYTECODE_FLOAT_MATH_LIBM_SUFFIX
#undef IREE_VM_BYTECODE_FLOAT_MATH_LITERAL
#undef IREE_VM_BYTECODE_FLOAT_MATH_LITERAL_
#undef IREE_VM_BYTECODE_FLOAT_MATH_BITS_TYPE
#undef IREE_VM_BYTECODE_FLOAT_MATH_TYPE
#undef IREE_VM_BYTECODE_FLOAT_MATH_WIDTH

#define IREE_VM_BYTECODE_FLOAT_MATH_WIDTH f64
#define IREE_VM_BYTECODE_FLOAT_MATH_TYPE double
#define IREE_VM_BYTECODE_FLOAT_MATH_BITS_TYPE uint64_t
#define IREE_VM_BYTECODE_FLOAT_MATH_LITERAL(value) value
#define IREE_VM_BYTECODE_FLOAT_MATH_LIBM_SUFFIX
#define IREE_VM_BYTECODE_FLOAT_MATH_MAGNITUDE_MASK UINT64_C(0x7FFFFFFFFFFFFFFF)
#define IREE_VM_BYTECODE_FLOAT_MATH_SIGN_MASK UINT64_C(0x8000000000000000)
#define IREE_VM_BYTECODE_FLOAT_MATH_INFINITY_BITS UINT64_C(0x7FF0000000000000)
#define IREE_VM_BYTECODE_FLOAT_MATH_QUIET_NAN_BITS UINT64_C(0x7FF8000000000000)
#define IREE_VM_BYTECODE_FLOAT_MATH_POSITIVE_ONE_BITS \
  UINT64_C(0x3FF0000000000000)
#define IREE_VM_BYTECODE_FLOAT_MATH_NEGATIVE_ONE_BITS \
  UINT64_C(0xBFF0000000000000)
#define IREE_VM_BYTECODE_FLOAT_MATH_INVERSE_SQRT2_BITS \
  UINT64_C(0x3FE6A09E667F3BCD)
#define IREE_VM_BYTECODE_FLOAT_MATH_GELU_CUBIC_BITS UINT64_C(0x3FA6E4E26D4801F7)
#define IREE_VM_BYTECODE_FLOAT_MATH_SQRT_2_OVER_PI_BITS \
  UINT64_C(0x3FE9884533D43651)
#include "iree/vm/bytecode/interpreter_float_math_impl.inl"
#undef IREE_VM_BYTECODE_FLOAT_MATH_SQRT_2_OVER_PI_BITS
#undef IREE_VM_BYTECODE_FLOAT_MATH_GELU_CUBIC_BITS
#undef IREE_VM_BYTECODE_FLOAT_MATH_INVERSE_SQRT2_BITS
#undef IREE_VM_BYTECODE_FLOAT_MATH_NEGATIVE_ONE_BITS
#undef IREE_VM_BYTECODE_FLOAT_MATH_POSITIVE_ONE_BITS
#undef IREE_VM_BYTECODE_FLOAT_MATH_QUIET_NAN_BITS
#undef IREE_VM_BYTECODE_FLOAT_MATH_INFINITY_BITS
#undef IREE_VM_BYTECODE_FLOAT_MATH_SIGN_MASK
#undef IREE_VM_BYTECODE_FLOAT_MATH_MAGNITUDE_MASK
#undef IREE_VM_BYTECODE_FLOAT_MATH_LIBM_SUFFIX
#undef IREE_VM_BYTECODE_FLOAT_MATH_LITERAL
#undef IREE_VM_BYTECODE_FLOAT_MATH_BITS_TYPE
#undef IREE_VM_BYTECODE_FLOAT_MATH_TYPE
#undef IREE_VM_BYTECODE_FLOAT_MATH_WIDTH

#undef IREE_VM_BYTECODE_FLOAT_MATH_LIBM
#undef IREE_VM_BYTECODE_FLOAT_MATH_LIBM_EXPAND_
#undef IREE_VM_BYTECODE_FLOAT_MATH_LIBM_CONCAT_
#undef IREE_VM_BYTECODE_FLOAT_MATH_NAME
#undef IREE_VM_BYTECODE_FLOAT_MATH_NAME_EXPAND_
#undef IREE_VM_BYTECODE_FLOAT_MATH_NAME_CONCAT_
