// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef IREE_VM_BYTECODE_INTERPRETER_FLOAT_H_
#define IREE_VM_BYTECODE_INTERPRETER_FLOAT_H_

#include <math.h>
#include <string.h>

#include "iree/base/api.h"
#include "iree/vm/bytecode/interpreter_float_math.h"
#include "iree/vm/bytecode/wire/core.h"

// Executes verified Core floating records against a physical value bank.
// Invocation drive segments establish the architectural floating environment
// before reaching these helpers. Raw-bit classification precedes every numeric
// comparison so signaling NaNs cannot reach host comparison instructions.

#define IREE_VM_BYTECODE_FLOAT_PRIVATE_CONCAT_(width, name) \
  iree_vm_bytecode_float_##width##_##name
#define IREE_VM_BYTECODE_FLOAT_PRIVATE_EXPAND_(width, name) \
  IREE_VM_BYTECODE_FLOAT_PRIVATE_CONCAT_(width, name)
#define IREE_VM_BYTECODE_FLOAT_PRIVATE(name) \
  IREE_VM_BYTECODE_FLOAT_PRIVATE_EXPAND_(IREE_VM_BYTECODE_FLOAT_WIDTH, name)
#define IREE_VM_BYTECODE_FLOAT_BITS_CONCAT_(name, width) \
  iree_vm_bytecode_float_##name##_##width##_bits
#define IREE_VM_BYTECODE_FLOAT_BITS_EXPAND_(name, width) \
  IREE_VM_BYTECODE_FLOAT_BITS_CONCAT_(name, width)
#define IREE_VM_BYTECODE_FLOAT_BITS(name) \
  IREE_VM_BYTECODE_FLOAT_BITS_EXPAND_(name, IREE_VM_BYTECODE_FLOAT_WIDTH)
#define IREE_VM_BYTECODE_FLOAT_EXECUTE_CONCAT_(name, width) \
  iree_vm_bytecode_execute_float_##name##_##width
#define IREE_VM_BYTECODE_FLOAT_EXECUTE_EXPAND_(name, width) \
  IREE_VM_BYTECODE_FLOAT_EXECUTE_CONCAT_(name, width)
#define IREE_VM_BYTECODE_FLOAT_EXECUTE(name) \
  IREE_VM_BYTECODE_FLOAT_EXECUTE_EXPAND_(name, IREE_VM_BYTECODE_FLOAT_WIDTH)
#define IREE_VM_BYTECODE_FLOAT_RECORD_CONCAT_(name, width) \
  iree_vm_bytecode_float_##name##_##width##_t
#define IREE_VM_BYTECODE_FLOAT_RECORD_EXPAND_(name, width) \
  IREE_VM_BYTECODE_FLOAT_RECORD_CONCAT_(name, width)
#define IREE_VM_BYTECODE_FLOAT_RECORD(name) \
  IREE_VM_BYTECODE_FLOAT_RECORD_EXPAND_(name, IREE_VM_BYTECODE_FLOAT_WIDTH)
#define IREE_VM_BYTECODE_FLOAT_MATH_CONCAT_(name, width) \
  iree_vm_bytecode_float_math_##name##_##width
#define IREE_VM_BYTECODE_FLOAT_MATH_EXPAND_(name, width) \
  IREE_VM_BYTECODE_FLOAT_MATH_CONCAT_(name, width)
#define IREE_VM_BYTECODE_FLOAT_MATH(name) \
  IREE_VM_BYTECODE_FLOAT_MATH_EXPAND_(name, IREE_VM_BYTECODE_FLOAT_WIDTH)

#define IREE_VM_BYTECODE_FLOAT_WIDTH f32
#define IREE_VM_BYTECODE_FLOAT_TYPE float
#define IREE_VM_BYTECODE_FLOAT_BITS_TYPE uint32_t
#define IREE_VM_BYTECODE_FLOAT_LITERAL_(value) value##f
#define IREE_VM_BYTECODE_FLOAT_LITERAL(value) \
  IREE_VM_BYTECODE_FLOAT_LITERAL_(value)
#define IREE_VM_BYTECODE_FLOAT_MAGNITUDE_MASK UINT32_C(0x7FFFFFFF)
#define IREE_VM_BYTECODE_FLOAT_SIGN_MASK UINT32_C(0x80000000)
#define IREE_VM_BYTECODE_FLOAT_INFINITY_BITS UINT32_C(0x7F800000)
#define IREE_VM_BYTECODE_FLOAT_QUIET_NAN_BITS UINT32_C(0x7FC00000)
#define IREE_VM_BYTECODE_FLOAT_FMOD fmodf
#include "iree/vm/bytecode/interpreter_float_impl.inl"
#undef IREE_VM_BYTECODE_FLOAT_FMOD
#undef IREE_VM_BYTECODE_FLOAT_QUIET_NAN_BITS
#undef IREE_VM_BYTECODE_FLOAT_INFINITY_BITS
#undef IREE_VM_BYTECODE_FLOAT_SIGN_MASK
#undef IREE_VM_BYTECODE_FLOAT_MAGNITUDE_MASK
#undef IREE_VM_BYTECODE_FLOAT_LITERAL
#undef IREE_VM_BYTECODE_FLOAT_LITERAL_
#undef IREE_VM_BYTECODE_FLOAT_BITS_TYPE
#undef IREE_VM_BYTECODE_FLOAT_TYPE
#undef IREE_VM_BYTECODE_FLOAT_WIDTH

#define IREE_VM_BYTECODE_FLOAT_WIDTH f64
#define IREE_VM_BYTECODE_FLOAT_TYPE double
#define IREE_VM_BYTECODE_FLOAT_BITS_TYPE uint64_t
#define IREE_VM_BYTECODE_FLOAT_LITERAL(value) value
#define IREE_VM_BYTECODE_FLOAT_MAGNITUDE_MASK UINT64_C(0x7FFFFFFFFFFFFFFF)
#define IREE_VM_BYTECODE_FLOAT_SIGN_MASK UINT64_C(0x8000000000000000)
#define IREE_VM_BYTECODE_FLOAT_INFINITY_BITS UINT64_C(0x7FF0000000000000)
#define IREE_VM_BYTECODE_FLOAT_QUIET_NAN_BITS UINT64_C(0x7FF8000000000000)
#define IREE_VM_BYTECODE_FLOAT_FMOD fmod
#include "iree/vm/bytecode/interpreter_float_impl.inl"
#undef IREE_VM_BYTECODE_FLOAT_FMOD
#undef IREE_VM_BYTECODE_FLOAT_QUIET_NAN_BITS
#undef IREE_VM_BYTECODE_FLOAT_INFINITY_BITS
#undef IREE_VM_BYTECODE_FLOAT_SIGN_MASK
#undef IREE_VM_BYTECODE_FLOAT_MAGNITUDE_MASK
#undef IREE_VM_BYTECODE_FLOAT_LITERAL
#undef IREE_VM_BYTECODE_FLOAT_BITS_TYPE
#undef IREE_VM_BYTECODE_FLOAT_TYPE
#undef IREE_VM_BYTECODE_FLOAT_WIDTH

#undef IREE_VM_BYTECODE_FLOAT_MATH
#undef IREE_VM_BYTECODE_FLOAT_MATH_EXPAND_
#undef IREE_VM_BYTECODE_FLOAT_MATH_CONCAT_
#undef IREE_VM_BYTECODE_FLOAT_RECORD
#undef IREE_VM_BYTECODE_FLOAT_RECORD_EXPAND_
#undef IREE_VM_BYTECODE_FLOAT_RECORD_CONCAT_
#undef IREE_VM_BYTECODE_FLOAT_EXECUTE
#undef IREE_VM_BYTECODE_FLOAT_EXECUTE_EXPAND_
#undef IREE_VM_BYTECODE_FLOAT_EXECUTE_CONCAT_
#undef IREE_VM_BYTECODE_FLOAT_BITS
#undef IREE_VM_BYTECODE_FLOAT_BITS_EXPAND_
#undef IREE_VM_BYTECODE_FLOAT_BITS_CONCAT_
#undef IREE_VM_BYTECODE_FLOAT_PRIVATE
#undef IREE_VM_BYTECODE_FLOAT_PRIVATE_EXPAND_
#undef IREE_VM_BYTECODE_FLOAT_PRIVATE_CONCAT_

#endif  // IREE_VM_BYTECODE_INTERPRETER_FLOAT_H_
