# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//loom/build_tools/bazel:build_defs.bzl", "loom_cc_library", "loom_cc_test")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = ["notice"],
)

loom_cc_library(
    name = "request",
    srcs = ["request.c"],
    hdrs = ["request.h"],
    deps = [
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal:json",
        "//runtime/src/iree/base/internal:unicode",
    ],
)

loom_cc_test(
    name = "request_test",
    srcs = ["request_test.cc"],
    deps = [
        ":request",
        "//runtime/src/iree/base",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
    ],
)

loom_cc_library(
    name = "output",
    srcs = ["output.c"],
    hdrs = ["output.h"],
    deps = ["//runtime/src/iree/base"],
)

loom_cc_test(
    name = "output_test",
    srcs = ["output_test.cc"],
    deps = [
        ":output",
        "//runtime/src/iree/base",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
    ],
)

loom_cc_library(
    name = "service",
    srcs = ["service.c"],
    hdrs = ["service.h"],
    deps = [
        ":output",
        ":request",
        "//experimental/loom_serve/http:request",
        "//experimental/loom_serve/http:server",
        "//loom/src/loom/util:json",
        "//loom/src/loom/util:stream",
        "//runtime/src/iree/async",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal:base64",
        "//runtime/src/iree/base/threading",
        "//runtime/src/iree/base/threading:thread",
    ],
)

loom_cc_test(
    name = "service_test",
    srcs = ["service_test.cc"],
    deps = [
        ":service",
        "//experimental/loom_serve/http:server",
        "//runtime/src/iree/async",
        "//runtime/src/iree/base",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
    ],
)
