# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("@rules_python//python:defs.bzl", "py_test")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

py_test(
    name = "cmake_data_dependencies_test",
    srcs = ["cmake_data_dependencies_test.py"],
    data = [
        "cmake/iree_macros.cmake",
        "cmake/testdata/data_dependencies/CMakeLists.txt",
        "cmake/testdata/data_dependencies/fixture.txt",
        "cmake/testdata/data_dependencies/tool.c",
    ],
)

py_test(
    name = "cmake_test_metadata_test",
    srcs = ["cmake_test_metadata_test.py"],
    data = [
        "cmake/iree_configure_testing.cmake",
        "cmake/iree_macros.cmake",
        "cmake/testdata/test_metadata/CMakeLists.txt",
    ],
)

filegroup(
    name = "cmake_test_metadata_fixture",
    srcs = [
        "cmake/empty_file",
        "cmake/iree_configure_testing.cmake",
        "cmake/iree_macros.cmake",
        "cmake/testdata/test_metadata/CMakeLists.txt",
    ],
    visibility = ["//build_tools/devtools:__pkg__"],
)
