# Copyright 2022 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//build_tools/bazel:select.bzl", "iree_select")
load("//runtime/build_tools/bazel:cc.bzl", "iree_runtime_cc_library")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

iree_runtime_cc_library(
    name = "registration",
    srcs = ["init.c"],
    hdrs = ["init.h"],
    deps = [
        "//runtime/src/iree/base",
        "//runtime/src/iree/hal",
        "//runtime/src/iree/hal/drivers/task/executable:loader",
    ] + iree_select({
        "//runtime/config/hal:executable_loader_embedded_elf": [
            "//runtime/src/iree/hal/drivers/task/executable/loaders:embedded_elf_loader",
        ],
        "//conditions:default": [],
    }) + iree_select({
        "//runtime/config/hal:executable_loader_system_library": [
            "//runtime/src/iree/hal/drivers/task/executable/loaders:system_library_loader",
        ],
        "//conditions:default": [],
    }),
)
