# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//runtime/build_tools/bazel:cc.bzl", "iree_runtime_cc_library")
load("//runtime/build_tools/bazel:cc_test.bzl", "iree_runtime_cc_test")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

iree_runtime_cc_library(
    name = "frame",
    hdrs = ["frame.h"],
    deps = [
        "//runtime/src/iree/base",
    ],
)

iree_runtime_cc_library(
    name = "bulk_channel",
    srcs = ["bulk_channel.c"],
    hdrs = ["bulk_channel.h"],
    deps = [
        ":frame",
        "//runtime/src/iree/async",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal",
        "//runtime/src/iree/base/internal:atomic_slist",
        "//runtime/src/iree/base/threading",
        "//runtime/src/iree/net:message_endpoint",
        "//runtime/src/iree/net/channel/util:frame_sender",
        "//runtime/src/iree/net/channel/util:send_gate",
    ],
)

iree_runtime_cc_library(
    name = "chunk_pool",
    srcs = ["chunk_pool.c"],
    hdrs = ["chunk_pool.h"],
    deps = [
        ":frame",
        "//runtime/src/iree/async",
        "//runtime/src/iree/base",
    ],
)

iree_runtime_cc_library(
    name = "receive_window",
    srcs = ["receive_window.c"],
    hdrs = ["receive_window.h"],
    deps = [
        ":chunk_pool",
        "//runtime/src/iree/base",
    ],
)

iree_runtime_cc_library(
    name = "transfer_table",
    srcs = ["transfer_table.c"],
    hdrs = ["transfer_table.h"],
    deps = [
        "//runtime/src/iree/base",
    ],
)

iree_runtime_cc_test(
    name = "bulk_channel_test",
    srcs = ["bulk_channel_test.cc"],
    deps = [
        ":bulk_channel",
        ":frame",
        "//runtime/src/iree/async",
        "//runtime/src/iree/base",
        "//runtime/src/iree/net:carrier",
        "//runtime/src/iree/net:message_endpoint",
        "//runtime/src/iree/net/channel/util:frame_sender",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
    ],
)

iree_runtime_cc_test(
    name = "chunk_pool_test",
    srcs = ["chunk_pool_test.cc"],
    deps = [
        ":chunk_pool",
        ":frame",
        "//runtime/src/iree/async",
        "//runtime/src/iree/base",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
    ],
)

iree_runtime_cc_test(
    name = "receive_window_test",
    srcs = ["receive_window_test.cc"],
    deps = [
        ":frame",
        ":receive_window",
        "//runtime/src/iree/async",
        "//runtime/src/iree/base",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
    ],
)

iree_runtime_cc_test(
    name = "transfer_table_test",
    srcs = ["transfer_table_test.cc"],
    deps = [
        ":transfer_table",
        "//runtime/src/iree/base",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
    ],
)
