# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//loom/build_tools/bazel:loom_check.bzl", "loom_check_test_suite")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = ["notice"],
)

loom_check_test_suite(
    name = "test",
    srcs = [
        "attribute_visibility.loom-test",
        "dominance.loom-test",
        "func_like_exits.loom-test",
        "function_entry.loom-test",
        "isolation.loom-test",
        "operand_dictionary.loom-test",
        "predicate_list.loom-test",
        "type_visibility.loom-test",
        "unreachable_definitions.loom-test",
    ],
)
