# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//libamdf/build_tools/bazel:cc.bzl", "amdf_cc_binary")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

amdf_cc_binary(
    name = "enumerate",
    srcs = ["enumerate.c"],
    target_compatible_with = ["@platforms//os:windows"],
    deps = ["//libamdf:amdf"],
)
