# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//libhrx/build_tools/bazel:cc.bzl", "hrx_cc_shared_library")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

PASSTHROUGH_INCLUDES = [
    "..",
]

_LINUX_COMPATIBILITY = ["@platforms//os:linux"]

hrx_cc_shared_library(
    name = "hip_intercept",
    srcs = ["hip_intercept.c"],
    hdrs = ["hip_function_table.h"],
    includes = PASSTHROUGH_INCLUDES,
    target_compatible_with = _LINUX_COMPATIBILITY,
    deps = [
        "//build_tools/bazel:dl",
        "//build_tools/bazel:pthreads",
    ],
)

hrx_cc_shared_library(
    name = "hip_logging",
    srcs = ["hip_logging.c"],
    hdrs = ["hip_function_table.h"],
    includes = PASSTHROUGH_INCLUDES,
    target_compatible_with = _LINUX_COMPATIBILITY,
    deps = ["//build_tools/bazel:pthreads"],
)

hrx_cc_shared_library(
    name = "hip_noop",
    srcs = ["interceptors/passthrough_interceptor.c"],
    hdrs = ["hip_function_table.h"],
    includes = PASSTHROUGH_INCLUDES,
    target_compatible_with = _LINUX_COMPATIBILITY,
)

hrx_cc_shared_library(
    name = "hip_buffer_tracer",
    srcs = ["hip_buffer_tracer.c"],
    hdrs = ["hip_function_table.h"],
    includes = PASSTHROUGH_INCLUDES,
    target_compatible_with = _LINUX_COMPATIBILITY,
    deps = ["//build_tools/bazel:pthreads"],
)
