# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//loom/build_tools/bazel:loom_check.bzl", "loom_check_test_suite")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

loom_check_test_suite(
    name = "test",
    srcs = [
        "block_forwarding.loom-test",
        "block_fusion.loom-test",
        "block_merging.loom-test",
        "branch_folding.loom-test",
        "branch_fusion.loom-test",
        "branch_sink.loom-test",
        "cfg_compatibility.loom-test",
        "cfg_converge.loom-test",
        "cfg_simplify.loom-test",
        "cfg_simplify_conditions.loom-test",
        "cfg_simplify_facts.loom-test",
        "cfg_simplify_identities.loom-test",
        "cfg_simplify_scf_pipeline.loom-test",
    ],
)
