# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//loom/build_tools/bazel:build_defs.bzl", "loom_cc_library", "loom_cc_test")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = ["notice"],
)

loom_cc_library(
    name = "request",
    srcs = ["request.c"],
    hdrs = ["request.h"],
    deps = ["//runtime/src/iree/base"],
)

loom_cc_test(
    name = "request_test",
    srcs = ["request_test.cc"],
    deps = [
        ":request",
        "//runtime/src/iree/base",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
    ],
)

loom_cc_library(
    name = "router",
    srcs = ["router.c"],
    hdrs = ["router.h"],
    deps = [
        ":request",
        ":server",
        "//loom/src/loom/util:json",
        "//loom/src/loom/util:stream",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal:json",
        "//runtime/src/iree/base/threading",
    ],
)

loom_cc_library(
    name = "server",
    srcs = ["server.c"],
    hdrs = ["server.h"],
    deps = [
        ":request",
        "//runtime/src/iree/async",
        "//runtime/src/iree/async:platform",
        "//runtime/src/iree/async/util:proactor_thread",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/threading",
        "//runtime/src/iree/net:carrier",
        "//runtime/src/iree/net/carrier/tcp",
    ],
)

loom_cc_test(
    name = "router_test",
    srcs = ["router_test.cc"],
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        ":request",
        ":router",
        ":server",
        "//runtime/src/iree/async",
        "//runtime/src/iree/base",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
    ],
)

loom_cc_test(
    name = "server_test",
    srcs = ["server_test.cc"],
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        ":request",
        ":server",
        "//runtime/src/iree/async",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/threading",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
    ],
)
