# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""Repository rule exposing optional AMDGPU builtin device compiler tools."""

_STUB_BUILD = """\
# AUTO-GENERATED by amdgpu_device_toolchain_repo.bzl - do not edit.

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "unused",
    srcs = [],
)
"""

_STUB_PATHS = """\
# AUTO-GENERATED by amdgpu_device_toolchain_repo.bzl - do not edit.

AMDGPU_DEVICE_TOOLCHAIN_AVAILABLE = False
AMDGPU_DEVICE_TOOLCHAIN_ERROR = "AMDGPU device binary source mode requires --repo_env=IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN=rocm, llvm-tools, llvm-project, or auto."
AMDGPU_CLANG_TOOL = ""
AMDGPU_LLVM_AR_TOOL = ""
AMDGPU_LLVM_LINK_TOOL = ""
AMDGPU_LLD_TOOL = ""
AMDGPU_LLVM_OBJCOPY_TOOL = ""
AMDGPU_CLANG_RESOURCE_HEADERS = ""
AMDGPU_CLANG_RESOURCE_MARKER = ""
AMDGPU_CLANG_RESOURCE_INCLUDE_ARGS = []
AMDGPU_HIP_DEVICE_LIBRARIES_AVAILABLE = False
AMDGPU_HIP_DEVICE_LIBRARIES = ""
AMDGPU_HIP_DEVICE_LIBRARIES_MARKER = ""
AMDGPU_CLANG_OFFLOAD_BUNDLER_TOOL = ""
"""

_PREBUILT_TOOL_BZL = """\
\"\"\"Rule for exposing pre-built binaries as executable Bazel targets.\"\"\"

def _prebuilt_tool_impl(ctx):
    out = ctx.actions.declare_file(ctx.label.name + "{EXECUTABLE_SUFFIX}")
    ctx.actions.symlink(
        output = out,
        target_file = ctx.file.src,
        is_executable = True,
    )
    runfiles = ctx.runfiles(files = ctx.files.data + [ctx.file.src])
    return [DefaultInfo(
        executable = out,
        files = depset([out]),
        runfiles = runfiles,
    )]

prebuilt_tool = rule(
    implementation = _prebuilt_tool_impl,
    executable = True,
    attrs = {
        "src": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "The pre-built binary file.",
        ),
        "data": attr.label_list(
            allow_files = True,
            doc = "Additional files the tool needs at runtime.",
        ),
    },
    doc = "Wraps a pre-built binary as an executable Bazel target.",
)
"""

_LOCAL_BUILD_TEMPLATE = """\
# AUTO-GENERATED by amdgpu_device_toolchain_repo.bzl - do not edit.

load(":prebuilt_tool.bzl", "prebuilt_tool")

package(default_visibility = ["//visibility:public"])

prebuilt_tool(
    name = "clang",
    src = "bin/clang{EXECUTABLE_SUFFIX}",
)

prebuilt_tool(
    name = "llvm-ar",
    src = "bin/llvm-ar{EXECUTABLE_SUFFIX}",
)

prebuilt_tool(
    name = "llvm-link",
    src = "bin/llvm-link{EXECUTABLE_SUFFIX}",
)

prebuilt_tool(
    name = "lld",
    src = "bin/lld{EXECUTABLE_SUFFIX}",
)

prebuilt_tool(
    name = "llvm-objcopy",
    src = "bin/llvm-objcopy{EXECUTABLE_SUFFIX}",
)

filegroup(
    name = "clang_resource_headers",
    srcs = glob(["clang_resource_include/**"]),
)

filegroup(
    name = "clang_resource_include_marker",
    srcs = ["clang_resource_include/stddef.h"],
)
"""

_ROCM_DEVICE_LIBRARIES_BUILD = """\

prebuilt_tool(
    name = "clang-offload-bundler",
    src = "bin/clang-offload-bundler{EXECUTABLE_SUFFIX}",
)

filegroup(
    name = "hip_device_libraries",
    srcs = glob(["hip_device_libraries/**"]),
)

filegroup(
    name = "hip_device_libraries_marker",
    srcs = ["hip_device_libraries/ockl.bc"],
)
"""

_LOCAL_PATHS_TEMPLATE = """\
# AUTO-GENERATED by amdgpu_device_toolchain_repo.bzl - do not edit.

AMDGPU_DEVICE_TOOLCHAIN_AVAILABLE = True
AMDGPU_DEVICE_TOOLCHAIN_ERROR = ""
AMDGPU_CLANG_TOOL = "@iree_amdgpu_device_toolchain//:clang"
AMDGPU_LLVM_AR_TOOL = "@iree_amdgpu_device_toolchain//:llvm-ar"
AMDGPU_LLVM_LINK_TOOL = "@iree_amdgpu_device_toolchain//:llvm-link"
AMDGPU_LLD_TOOL = "@iree_amdgpu_device_toolchain//:lld"
AMDGPU_LLVM_OBJCOPY_TOOL = "@iree_amdgpu_device_toolchain//:llvm-objcopy"
AMDGPU_CLANG_RESOURCE_HEADERS = "@iree_amdgpu_device_toolchain//:clang_resource_headers"
AMDGPU_CLANG_RESOURCE_MARKER = "@iree_amdgpu_device_toolchain//:clang_resource_include_marker"
AMDGPU_CLANG_RESOURCE_INCLUDE_ARGS = [
    "--clang-resource-include",
    "$$(dirname $(location @iree_amdgpu_device_toolchain//:clang_resource_include_marker))",
]
"""

_ROCM_DEVICE_LIBRARIES_PATHS = """\
AMDGPU_HIP_DEVICE_LIBRARIES_AVAILABLE = True
AMDGPU_HIP_DEVICE_LIBRARIES = "@iree_amdgpu_device_toolchain//:hip_device_libraries"
AMDGPU_HIP_DEVICE_LIBRARIES_MARKER = "@iree_amdgpu_device_toolchain//:hip_device_libraries_marker"
AMDGPU_CLANG_OFFLOAD_BUNDLER_TOOL = "@iree_amdgpu_device_toolchain//:clang-offload-bundler"
"""

_NO_ROCM_DEVICE_LIBRARIES_PATHS = """\
AMDGPU_HIP_DEVICE_LIBRARIES_AVAILABLE = False
AMDGPU_HIP_DEVICE_LIBRARIES = ""
AMDGPU_HIP_DEVICE_LIBRARIES_MARKER = ""
AMDGPU_CLANG_OFFLOAD_BUNDLER_TOOL = ""
"""

_LLVM_PROJECT_BUILD = """\
# AUTO-GENERATED by amdgpu_device_toolchain_repo.bzl - do not edit.

package(default_visibility = ["//visibility:public"])

alias(
    name = "clang",
    actual = "@llvm-project//clang:clang",
)

alias(
    name = "llvm-ar",
    actual = "@llvm-project//llvm:llvm-ar",
)

alias(
    name = "llvm-link",
    actual = "@llvm-project//llvm:llvm-link",
)

alias(
    name = "lld",
    actual = "@llvm-project//lld:lld",
)

alias(
    name = "llvm-objcopy",
    actual = "@llvm-project//llvm:llvm-objcopy",
)
"""

_LLVM_PROJECT_PATHS = """\
# AUTO-GENERATED by amdgpu_device_toolchain_repo.bzl - do not edit.

AMDGPU_DEVICE_TOOLCHAIN_AVAILABLE = True
AMDGPU_DEVICE_TOOLCHAIN_ERROR = ""
AMDGPU_CLANG_TOOL = "@iree_amdgpu_device_toolchain//:clang"
AMDGPU_LLVM_AR_TOOL = "@iree_amdgpu_device_toolchain//:llvm-ar"
AMDGPU_LLVM_LINK_TOOL = "@iree_amdgpu_device_toolchain//:llvm-link"
AMDGPU_LLD_TOOL = "@iree_amdgpu_device_toolchain//:lld"
AMDGPU_LLVM_OBJCOPY_TOOL = "@iree_amdgpu_device_toolchain//:llvm-objcopy"
AMDGPU_CLANG_RESOURCE_HEADERS = "@llvm-project//clang:builtin_headers_gen"
AMDGPU_CLANG_RESOURCE_MARKER = ""
AMDGPU_CLANG_RESOURCE_INCLUDE_ARGS = [
    "--clang-resource-include",
    "$(BINDIR)/external/+_repo_rules+llvm-project/clang/staging/include/",
]
AMDGPU_HIP_DEVICE_LIBRARIES_AVAILABLE = False
AMDGPU_HIP_DEVICE_LIBRARIES = ""
AMDGPU_HIP_DEVICE_LIBRARIES_MARKER = ""
AMDGPU_CLANG_OFFLOAD_BUNDLER_TOOL = ""
"""

def _normalize_path(path):
    return path.replace("\\", "/")

def _join_path(left, right):
    left = _normalize_path(left)
    if left.endswith("/"):
        return left + right
    return left + "/" + right

def _dirname(path):
    path = _normalize_path(path)
    if "/" not in path:
        return "."
    return path.rsplit("/", 1)[0]

def _basename(path):
    path = _normalize_path(path)
    if "/" not in path:
        return path
    return path.rsplit("/", 1)[1]

def _append_unique(values, new_values):
    for value in new_values:
        if value not in values:
            values.append(value)

def _is_windows(repository_ctx):
    return repository_ctx.os.name.lower().startswith("windows")

def _resolve_executable(repository_ctx, candidate):
    candidates = [_normalize_path(candidate)]
    if _is_windows(repository_ctx) and not candidate.lower().endswith(".exe"):
        candidates.append(_normalize_path(candidate) + ".exe")
    for path in candidates:
        if not repository_ctx.path(path).exists:
            continue
        if _is_windows(repository_ctx):
            return str(repository_ctx.path(path))
        result = repository_ctx.execute(["test", "-x", path], quiet = True)
        if result.return_code == 0:
            return str(repository_ctx.path(path))
    return ""

def _try_find_tool(
        repository_ctx,
        names,
        directories,
        explicit_env_vars,
        additional_candidates = ()):
    candidates = []
    for env_var in explicit_env_vars:
        value = repository_ctx.getenv(env_var)
        if value:
            candidates.append(value)
    candidates.extend(additional_candidates)
    for directory in directories:
        for name in names:
            candidates.append(_join_path(directory, name))

    for candidate in candidates:
        resolved = _resolve_executable(repository_ctx, candidate)
        if resolved:
            return resolved
    return ""

def _find_tool(
        repository_ctx,
        names,
        directories,
        explicit_env_vars,
        description,
        additional_candidates = ()):
    tool = _try_find_tool(
        repository_ctx,
        names,
        directories,
        explicit_env_vars,
        additional_candidates,
    )
    if tool:
        return tool

    fail("Could not find {}. Tried env vars [{}] and candidate directories [{}].".format(
        description,
        ", ".join(explicit_env_vars),
        ", ".join(directories),
    ))

def _rocm_tool_dirs(root):
    return [
        _join_path(root, "llvm/bin"),
        _join_path(root, "lib/llvm/bin"),
        _join_path(root, "bin"),
    ]

def _candidate_rocm_roots(repository_ctx):
    roots = []
    for env_var in [
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_ROCM_PATH",
        "IREE_ROCM_PATH",
        "ROCM_PATH",
        "ROCM_ROOT",
        "ROCM_HOME",
        "HIP_PATH",
    ]:
        value = repository_ctx.getenv(env_var)
        if not value:
            continue
        value = _normalize_path(value)
        _append_unique(roots, [value])
        if env_var == "HIP_PATH" and _basename(value) == "hip":
            _append_unique(roots, [_dirname(value)])
    return roots

def _llvm_tool_dirs(root):
    return [
        root,
        _join_path(root, "bin"),
        _join_path(root, "llvm/bin"),
        _join_path(root, "lib/llvm/bin"),
    ]

def _clang_tool_candidates(repository_ctx, clang, names):
    candidates = []
    clang_dir = _dirname(clang)
    for name in names:
        result = repository_ctx.execute(
            [clang, "--print-prog-name=" + name],
            quiet = True,
        )
        if result.return_code != 0:
            continue
        printed_name = result.stdout.strip()
        if not printed_name:
            continue
        _append_unique(candidates, [
            printed_name,
            _join_path(clang_dir, printed_name),
        ])
    return candidates

def _detect_clang_resource_dir(repository_ctx, clang):
    result = repository_ctx.execute([clang, "-print-resource-dir"], quiet = True)
    if result.return_code != 0:
        fail("Failed to query clang resource directory from {}:\n{}".format(
            clang,
            result.stderr,
        ))
    resource_dir = result.stdout.strip()
    if not resource_dir:
        fail("clang resource directory query returned an empty path from {}".format(clang))
    return resource_dir

def _select_invocable_clang(repository_ctx, clang):
    resource_dir = _detect_clang_resource_dir(repository_ctx, clang)
    resource_version = _basename(resource_dir)
    if not resource_version:
        return clang
    clang_basename = _basename(clang)
    executable_suffix = ""
    if clang_basename.lower().endswith(".exe"):
        clang_basename = clang_basename[:-4]
        executable_suffix = ".exe"
    if clang_basename.endswith("-" + resource_version):
        return clang
    versioned_clang = _join_path(
        _dirname(clang),
        clang_basename + "-" + resource_version + executable_suffix,
    )
    resolved_clang = _resolve_executable(repository_ctx, versioned_clang)
    if resolved_clang:
        return resolved_clang
    return clang

def _validate_amdgpu_clang(repository_ctx, clang):
    probe_source = repository_ctx.path("amdgpu_device_toolchain_probe.c")
    repository_ctx.file(
        "amdgpu_device_toolchain_probe.c",
        "void iree_amdgpu_probe(void) {}\n",
    )
    result = repository_ctx.execute(
        [
            clang,
            "-target",
            "amdgcn-amd-amdhsa",
            "-mcpu=gfx900",
            "-nogpulib",
            "-x",
            "c",
            "-std=c11",
            "-fsyntax-only",
            str(probe_source),
        ],
        quiet = True,
    )
    if result.return_code != 0:
        fail("Configured AMDGPU device clang cannot target amdgcn-amd-amdhsa: {}\n{}".format(
            clang,
            result.stderr,
        ))

def _detect_clang_resource_include(repository_ctx, clang):
    explicit = repository_ctx.getenv("IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_CLANG_RESOURCE_INCLUDE")
    if explicit:
        path = repository_ctx.path(explicit)
        if not path.exists:
            fail("Configured clang resource include directory does not exist: {}".format(explicit))
        return str(path)

    include_dir = _join_path(_detect_clang_resource_dir(repository_ctx, clang), "include")
    path = repository_ctx.path(include_dir)
    if not path.exists:
        fail("clang resource include directory does not exist: {}".format(include_dir))
    return str(path)

def _is_rocm_device_library_dir(repository_ctx, candidate):
    path = repository_ctx.path(candidate)
    if not path.exists:
        return False
    for filename in ["hip.bc", "ockl.bc", "ocml.bc"]:
        if not repository_ctx.path(_join_path(str(path), filename)).exists:
            return False
    return True

def _detect_rocm_device_libraries(repository_ctx, clang, rocm_root):
    candidates = []
    explicit = repository_ctx.getenv(
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_ROCM_DEVICE_LIB_PATH",
    )
    if explicit:
        candidates.append(explicit)

    resource_dir = _detect_clang_resource_dir(repository_ctx, clang)
    llvm_root = _dirname(_dirname(_dirname(resource_dir)))
    candidates.append(_join_path(llvm_root, "amdgcn/bitcode"))

    if rocm_root:
        candidates.extend([
            _join_path(rocm_root, "amdgcn/bitcode"),
            _join_path(rocm_root, "lib/amdgcn/bitcode"),
            _join_path(rocm_root, "llvm/amdgcn/bitcode"),
            _join_path(rocm_root, "lib/llvm/amdgcn/bitcode"),
        ])

    for candidate in candidates:
        if _is_rocm_device_library_dir(repository_ctx, candidate):
            return str(repository_ctx.path(candidate))
    return ""

def _has_explicit_device_tools(repository_ctx):
    for env_var in [
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_CLANG_BINARY",
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_LLVM_AR_BINARY",
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_LLVM_LINK_BINARY",
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_LLD_BINARY",
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_LLVM_OBJCOPY_BINARY",
    ]:
        if repository_ctx.getenv(env_var):
            return True
    return False

def _validate_clang_resource_include(repository_ctx, clang_resource_include):
    marker = _join_path(clang_resource_include, "stddef.h")
    if not repository_ctx.path(marker).exists:
        fail("clang resource include marker does not exist: {}".format(marker))

def _write_local_toolchain_repo(
        repository_ctx,
        tools,
        clang_resource_include,
        rocm_device_libraries):
    _validate_clang_resource_include(repository_ctx, clang_resource_include)
    executable_suffix = ".exe" if _is_windows(repository_ctx) else ""
    repository_ctx.file(
        "prebuilt_tool.bzl",
        _PREBUILT_TOOL_BZL.replace("{EXECUTABLE_SUFFIX}", executable_suffix),
    )
    repository_ctx.file("bin/.keep", "")
    for name, path in tools.items():
        repository_ctx.symlink(
            repository_ctx.path(path),
            "bin/" + name + executable_suffix,
        )
    repository_ctx.symlink(
        repository_ctx.path(clang_resource_include),
        "clang_resource_include",
    )
    if rocm_device_libraries:
        repository_ctx.symlink(
            repository_ctx.path(rocm_device_libraries),
            "hip_device_libraries",
        )
    repository_ctx.file(
        "BUILD.bazel",
        (_LOCAL_BUILD_TEMPLATE +
         (_ROCM_DEVICE_LIBRARIES_BUILD if rocm_device_libraries else ""))
            .replace("{EXECUTABLE_SUFFIX}", executable_suffix),
    )
    repository_ctx.file(
        "paths.bzl",
        _LOCAL_PATHS_TEMPLATE +
        (_ROCM_DEVICE_LIBRARIES_PATHS if rocm_device_libraries else _NO_ROCM_DEVICE_LIBRARIES_PATHS),
    )

def _amdgpu_device_toolchain_repo_impl(repository_ctx):
    mode = repository_ctx.getenv("IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN") or "none"
    if mode not in ["none", "auto", "rocm", "llvm-tools", "llvm-project"]:
        fail("Unknown IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN '{}'. Available: none, auto, rocm, llvm-tools, llvm-project.".format(mode))

    if mode == "none":
        repository_ctx.file("BUILD.bazel", _STUB_BUILD)
        repository_ctx.file("paths.bzl", _STUB_PATHS)
        return

    if mode == "llvm-project":
        repository_ctx.file("BUILD.bazel", _LLVM_PROJECT_BUILD)
        repository_ctx.file("paths.bzl", _LLVM_PROJECT_PATHS)
        return

    rocm_root = ""
    tool_dirs = []
    if mode in ["auto", "rocm"]:
        rocm_roots = _candidate_rocm_roots(repository_ctx)
        if rocm_roots:
            rocm_root = rocm_roots[0]
            tool_dirs = _rocm_tool_dirs(rocm_root)
        elif mode == "rocm":
            fail("IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN=rocm requires a configured ROCm/TheRock root such as IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_ROCM_PATH or IREE_ROCM_PATH.")

    if not rocm_root and mode in ["auto", "llvm-tools"]:
        llvm_tools_dir = repository_ctx.getenv(
            "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_LLVM_TOOLS_DIR",
        )
        if llvm_tools_dir:
            tool_dirs = _llvm_tool_dirs(_normalize_path(llvm_tools_dir))
        elif mode == "auto" and not _has_explicit_device_tools(repository_ctx):
            repository_ctx.file("BUILD.bazel", _STUB_BUILD)
            repository_ctx.file("paths.bzl", _STUB_PATHS)
            return

    clang = _find_tool(
        repository_ctx,
        ["clang", "amdclang", "clang-22"],
        tool_dirs,
        ["IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_CLANG_BINARY"],
        "clang with AMDGPU support",
    )
    clang = _select_invocable_clang(repository_ctx, clang)
    _validate_amdgpu_clang(repository_ctx, clang)
    llvm_ar = _find_tool(
        repository_ctx,
        ["llvm-ar"],
        tool_dirs,
        ["IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_LLVM_AR_BINARY"],
        "llvm-ar",
        additional_candidates = _clang_tool_candidates(repository_ctx, clang, ["llvm-ar"]),
    )
    llvm_link = _find_tool(
        repository_ctx,
        ["llvm-link"],
        tool_dirs,
        ["IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_LLVM_LINK_BINARY"],
        "llvm-link",
        additional_candidates = _clang_tool_candidates(repository_ctx, clang, ["llvm-link"]),
    )
    lld = _find_tool(
        repository_ctx,
        ["lld", "ld.lld"],
        tool_dirs,
        ["IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_LLD_BINARY"],
        "lld",
        additional_candidates = _clang_tool_candidates(repository_ctx, clang, ["lld", "ld.lld"]),
    )
    llvm_objcopy = _find_tool(
        repository_ctx,
        ["llvm-objcopy"],
        tool_dirs,
        ["IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_LLVM_OBJCOPY_BINARY"],
        "llvm-objcopy",
        additional_candidates = _clang_tool_candidates(repository_ctx, clang, ["llvm-objcopy"]),
    )
    clang_resource_include = _detect_clang_resource_include(repository_ctx, clang)
    rocm_device_libraries = _detect_rocm_device_libraries(
        repository_ctx,
        clang,
        rocm_root,
    )
    tools = {
        "clang": clang,
        "lld": lld,
        "llvm-ar": llvm_ar,
        "llvm-link": llvm_link,
        "llvm-objcopy": llvm_objcopy,
    }
    if rocm_device_libraries:
        clang_offload_bundler = _try_find_tool(
            repository_ctx,
            ["clang-offload-bundler"],
            tool_dirs,
            ["IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_CLANG_OFFLOAD_BUNDLER_BINARY"],
            additional_candidates = _clang_tool_candidates(
                repository_ctx,
                clang,
                ["clang-offload-bundler"],
            ),
        )
        if clang_offload_bundler:
            tools["clang-offload-bundler"] = clang_offload_bundler
        else:
            rocm_device_libraries = ""

    _write_local_toolchain_repo(
        repository_ctx,
        tools,
        clang_resource_include,
        rocm_device_libraries,
    )

amdgpu_device_toolchain_repo = repository_rule(
    implementation = _amdgpu_device_toolchain_repo_impl,
    environ = [
        "HIP_PATH",
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN",
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_CLANG_BINARY",
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_CLANG_OFFLOAD_BUNDLER_BINARY",
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_CLANG_RESOURCE_INCLUDE",
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_LLD_BINARY",
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_LLVM_AR_BINARY",
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_LLVM_LINK_BINARY",
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_LLVM_OBJCOPY_BINARY",
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_LLVM_TOOLS_DIR",
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_ROCM_PATH",
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_ROCM_DEVICE_LIB_PATH",
        "IREE_ROCM_PATH",
        "ROCM_HOME",
        "ROCM_PATH",
        "ROCM_ROOT",
    ],
    doc = "Exposes optional AMDGPU builtin device compiler tools.",
)
