# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//build_tools/testing:build_defs.bzl", "iree_execution_test_suite")
load(
    "//loom/build_tools/bazel:build_defs.bzl",
    "loom_cc_binary",
    "loom_cc_library",
)

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

loom_cc_library(
    name = "main",
    srcs = [
        "library_linker.c",
        "main.c",
    ],
    hdrs = [
        "library_linker.h",
        "main.h",
    ],
    deps = [
        "//loom/src/loom/link:linker",
        "//loom/src/loom/sanitizer:options",
        "//loom/src/loom/target:provider",
        "//loom/src/loom/tooling/cli:help",
        "//loom/src/loom/tooling/config",
        "//loom/src/loom/tooling/context",
        "//loom/src/loom/tooling/execution:session",
        "//loom/src/loom/tooling/execution/hal:device_provider",
        "//loom/src/loom/tooling/execution/hal:testbench_actual",
        "//loom/src/loom/tooling/execution/hal:testbench_requirement_provider",
        "//loom/src/loom/tooling/io:file",
        "//loom/src/loom/tooling/testbench:device_event",
        "//loom/src/loom/tooling/testbench:executor",
        "//loom/src/loom/tooling/testbench:issue_report",
        "//loom/src/loom/tooling/testbench:reference",
        "//loom/src/loom/tooling/testbench:requirements",
        "//loom/src/loom/util:json",
        "//loom/src/loom/util:stream",
        "//loom/src/loom/verify",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal:path",
        "//runtime/src/iree/base/tooling:flags",
        "//runtime/src/iree/io:stream",
    ],
)

loom_cc_binary(
    name = "iree-test-loom",
    srcs = ["iree-test-loom.c"],
    deps = [
        ":main",
        "//loom/src/loom/tooling/execution:configured",
        "//loom/src/loom/tooling/execution:configured_testbench",
        "//loom/src/loom/tooling/execution:execution_provider",
        "//runtime/src/iree/base",
    ],
)

iree_execution_test_suite(
    name = "execution_test",
    data = [
        "testdata/library_cases.loom",
        "testdata/linked_input_cases.loom",
        "testdata/requirement_cases.loom",
        "testdata/scalar_cases.loom",
    ],
    manifests = ["iree-test-loom.test.json"],
    tags = ["hostonly"],
    tools = {
        "iree-test-loom": ":iree-test-loom",
        "loom-link": "//loom/src/loom/tools/loom-link",
    },
)
