# GENERATED FILE: DO NOT EDIT.
# Generator: loom.gen.python.builders_pyi.
# Regenerate: python3 loom/py/loom/gen/run.py builders_pyi --in-place

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from loom.builder import IRBuilder, ValueRef
from loom.dialect.buffer.builders import BufferBuilder
from loom.dialect.cfg.builders import CfgBuilder
from loom.dialect.check.builders import CheckBuilder
from loom.dialect.encoding.builders import EncodingBuilder
from loom.dialect.func.builders import FuncBuilder
from loom.dialect.globals.builders import GlobalBuilder
from loom.dialect.index.builders import IndexBuilder
from loom.dialect.kernel.builders import KernelBuilder
from loom.dialect.llvmir.builders import LlvmirBuilder
from loom.dialect.low.builders import LowBuilder
from loom.dialect.pass_.builders import PassBuilder
from loom.dialect.pool.builders import PoolBuilder
from loom.dialect.sanitizer.builders import SanitizerBuilder
from loom.dialect.scalar.builders import ScalarBuilder
from loom.dialect.scf.builders import ScfBuilder
from loom.dialect.target.builders import TargetBuilder
from loom.dialect.test.builders import TestBuilder
from loom.dialect.vector.builders import VectorBuilder
from loom.dialect.view.builders import ViewBuilder
from loom.dsl import Op, TypeDef
from loom.ir import Block, Module, Region, Type

def module_builder(
    *,
    module: Module | None = ...,
    insertion_block: Block | None = ...,
    ops: Sequence[Op] | None = ...,
    types: Sequence[TypeDef] | None = ...,
) -> tuple[Module, LoomBuilder]: ...
def default_ops() -> tuple[Op, ...]: ...
def default_types() -> tuple[TypeDef, ...]: ...

class LoomBuilder:
    @property
    def module(self) -> Module: ...
    @property
    def ir(self) -> IRBuilder: ...
    def value(self, name: str, value_type: Type, **kwargs: Any) -> ValueRef: ...
    def region(self, args: Sequence[tuple[str, Type]] = ...) -> Region: ...
    def insertion_block(self, block: Block | None) -> Any: ...
    def location(self, location_id: int) -> Any: ...
    @property
    def buffer(self) -> BufferBuilder: ...
    @property
    def cfg(self) -> CfgBuilder: ...
    @property
    def check(self) -> CheckBuilder: ...
    @property
    def encoding(self) -> EncodingBuilder: ...
    @property
    def func(self) -> FuncBuilder: ...
    @property
    def global_(self) -> GlobalBuilder: ...
    @property
    def index(self) -> IndexBuilder: ...
    @property
    def kernel(self) -> KernelBuilder: ...
    @property
    def llvmir(self) -> LlvmirBuilder: ...
    @property
    def low(self) -> LowBuilder: ...
    @property
    def pass_(self) -> PassBuilder: ...
    @property
    def pool(self) -> PoolBuilder: ...
    @property
    def sanitizer(self) -> SanitizerBuilder: ...
    @property
    def scalar(self) -> ScalarBuilder: ...
    @property
    def scf(self) -> ScfBuilder: ...
    @property
    def target(self) -> TargetBuilder: ...
    @property
    def test(self) -> TestBuilder: ...
    @property
    def vector(self) -> VectorBuilder: ...
    @property
    def view(self) -> ViewBuilder: ...

class DialectBuilder:
    @property
    def name(self) -> str: ...

class OpCallable:
    @property
    def op_name(self) -> str: ...
    def __call__(self, **kwargs: Any) -> ValueRef | list[ValueRef] | None: ...
