// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// Target-independent numeric format facts used by encoded operand schemas.
//
// These describe the semantic value represented by payload, scale, table, or
// sparse metadata fields. They are not promises that a physical vector or
// buffer value uses unpacked lanes of this type.

#ifndef LOOM_UTIL_NUMERIC_FORMAT_H_
#define LOOM_UTIL_NUMERIC_FORMAT_H_

#include "iree/base/api.h"

typedef enum loom_value_fact_numeric_format_bits_e {
  // Zero: unknown for required fields, none for optional fields.
  LOOM_VALUE_FACT_NUMERIC_FORMAT_UNKNOWN = 0,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_NONE = 0,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_F64 = 1ull << 0,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_F32 = 1ull << 1,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_TF32 = 1ull << 2,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_F16 = 1ull << 3,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_BF16 = 1ull << 4,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_I32 = 1ull << 5,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_U32 = 1ull << 6,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_I16 = 1ull << 7,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_U16 = 1ull << 8,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_I8 = 1ull << 9,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_U8 = 1ull << 10,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_I6 = 1ull << 11,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_U6 = 1ull << 12,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_I5 = 1ull << 13,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_U5 = 1ull << 14,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_I4 = 1ull << 15,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_U4 = 1ull << 16,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_I3 = 1ull << 17,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_U3 = 1ull << 18,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_I2 = 1ull << 19,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_U2 = 1ull << 20,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_I1 = 1ull << 21,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_U1 = 1ull << 22,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_F8_E4M3 = 1ull << 23,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_F8_E5M2 = 1ull << 24,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_F8_E4M3FN = 1ull << 25,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_F8_E8M0 = 1ull << 26,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_BF8 = 1ull << 27,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_F6_E3M2 = 1ull << 28,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_F6_E2M3 = 1ull << 29,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_BF6 = 1ull << 30,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_F4_E2M1 = 1ull << 31,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_TERNARY = 1ull << 32,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_SIGN_BIT = 1ull << 33,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_CODEBOOK_INDEX = 1ull << 34,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_QUANT_I8 = 1ull << 35,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_QUANT_I6 = 1ull << 36,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_QUANT_I4 = 1ull << 37,
  LOOM_VALUE_FACT_NUMERIC_FORMAT_ALL =
      (LOOM_VALUE_FACT_NUMERIC_FORMAT_F64 | LOOM_VALUE_FACT_NUMERIC_FORMAT_F32 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_TF32 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_F16 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_BF16 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_I32 | LOOM_VALUE_FACT_NUMERIC_FORMAT_U32 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_I16 | LOOM_VALUE_FACT_NUMERIC_FORMAT_U16 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_I8 | LOOM_VALUE_FACT_NUMERIC_FORMAT_U8 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_I6 | LOOM_VALUE_FACT_NUMERIC_FORMAT_U6 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_I5 | LOOM_VALUE_FACT_NUMERIC_FORMAT_U5 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_I4 | LOOM_VALUE_FACT_NUMERIC_FORMAT_U4 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_I3 | LOOM_VALUE_FACT_NUMERIC_FORMAT_U3 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_I2 | LOOM_VALUE_FACT_NUMERIC_FORMAT_U2 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_I1 | LOOM_VALUE_FACT_NUMERIC_FORMAT_U1 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_F8_E4M3 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_F8_E5M2 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_F8_E4M3FN |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_F8_E8M0 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_BF8 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_F6_E3M2 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_F6_E2M3 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_BF6 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_F4_E2M1 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_TERNARY |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_SIGN_BIT |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_CODEBOOK_INDEX |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_QUANT_I8 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_QUANT_I6 |
       LOOM_VALUE_FACT_NUMERIC_FORMAT_QUANT_I4),
} loom_value_fact_numeric_format_bits_t;

typedef uint64_t loom_value_fact_numeric_format_flags_t;

#endif  // LOOM_UTIL_NUMERIC_FORMAT_H_
