// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// Target-independent numeric format facts used by encoded operand schemas.
//
// These describe the semantic value represented by payload, scale, table, or
// sparse metadata fields. They are not promises that a physical vector or
// buffer value uses unpacked lanes of this type.

#ifndef LOOM_UTIL_NUMERIC_FORMAT_H_
#define LOOM_UTIL_NUMERIC_FORMAT_H_

#include "iree/base/api.h"

// Numeric format bit values use macros because C enums cannot portably
// represent values wider than int.
typedef uint64_t loom_value_fact_numeric_format_bits_t;

// Zero: unknown for required fields, none for optional fields.
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_UNKNOWN UINT64_C(0)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_NONE UINT64_C(0)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_F64 (UINT64_C(1) << 0)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_F32 (UINT64_C(1) << 1)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_TF32 (UINT64_C(1) << 2)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_F16 (UINT64_C(1) << 3)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_BF16 (UINT64_C(1) << 4)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_I32 (UINT64_C(1) << 5)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_U32 (UINT64_C(1) << 6)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_I16 (UINT64_C(1) << 7)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_U16 (UINT64_C(1) << 8)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_I8 (UINT64_C(1) << 9)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_U8 (UINT64_C(1) << 10)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_I6 (UINT64_C(1) << 11)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_U6 (UINT64_C(1) << 12)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_I5 (UINT64_C(1) << 13)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_U5 (UINT64_C(1) << 14)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_I4 (UINT64_C(1) << 15)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_U4 (UINT64_C(1) << 16)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_I3 (UINT64_C(1) << 17)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_U3 (UINT64_C(1) << 18)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_I2 (UINT64_C(1) << 19)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_U2 (UINT64_C(1) << 20)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_I1 (UINT64_C(1) << 21)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_U1 (UINT64_C(1) << 22)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_F8_E4M3 (UINT64_C(1) << 23)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_F8_E5M2 (UINT64_C(1) << 24)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_F8_E4M3FN (UINT64_C(1) << 25)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_F8_E4M3FNUZ (UINT64_C(1) << 26)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_F8_E5M2FNUZ (UINT64_C(1) << 27)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_F8_E8M0 (UINT64_C(1) << 28)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_BF8 (UINT64_C(1) << 29)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_F6_E3M2 (UINT64_C(1) << 30)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_F6_E2M3 (UINT64_C(1) << 31)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_BF6 (UINT64_C(1) << 32)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_F4_E2M1 (UINT64_C(1) << 33)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_TERNARY (UINT64_C(1) << 34)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_SIGN_BIT (UINT64_C(1) << 35)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_CODEBOOK_INDEX (UINT64_C(1) << 36)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_QUANT_I8 (UINT64_C(1) << 37)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_QUANT_I6 (UINT64_C(1) << 38)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_QUANT_I4 (UINT64_C(1) << 39)
#define LOOM_VALUE_FACT_NUMERIC_FORMAT_ALL                                    \
  (LOOM_VALUE_FACT_NUMERIC_FORMAT_F64 | LOOM_VALUE_FACT_NUMERIC_FORMAT_F32 |  \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_TF32 | LOOM_VALUE_FACT_NUMERIC_FORMAT_F16 | \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_BF16 | LOOM_VALUE_FACT_NUMERIC_FORMAT_I32 | \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_U32 | LOOM_VALUE_FACT_NUMERIC_FORMAT_I16 |  \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_U16 | LOOM_VALUE_FACT_NUMERIC_FORMAT_I8 |   \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_U8 | LOOM_VALUE_FACT_NUMERIC_FORMAT_I6 |    \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_U6 | LOOM_VALUE_FACT_NUMERIC_FORMAT_I5 |    \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_U5 | LOOM_VALUE_FACT_NUMERIC_FORMAT_I4 |    \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_U4 | LOOM_VALUE_FACT_NUMERIC_FORMAT_I3 |    \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_U3 | LOOM_VALUE_FACT_NUMERIC_FORMAT_I2 |    \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_U2 | LOOM_VALUE_FACT_NUMERIC_FORMAT_I1 |    \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_U1 |                                        \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_F8_E4M3 |                                   \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_F8_E5M2 |                                   \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_F8_E4M3FN |                                 \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_F8_E4M3FNUZ |                               \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_F8_E5M2FNUZ |                               \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_F8_E8M0 |                                   \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_BF8 |                                       \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_F6_E3M2 |                                   \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_F6_E2M3 |                                   \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_BF6 |                                       \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_F4_E2M1 |                                   \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_TERNARY |                                   \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_SIGN_BIT |                                  \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_CODEBOOK_INDEX |                            \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_QUANT_I8 |                                  \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_QUANT_I6 |                                  \
   LOOM_VALUE_FACT_NUMERIC_FORMAT_QUANT_I4)

typedef uint64_t loom_value_fact_numeric_format_flags_t;

#endif  // LOOM_UTIL_NUMERIC_FORMAT_H_
