# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""Migration metadata and validation for Loom source and bytecode formats."""

from loom.migration.driver import (
    LOOM_BYTECODE_SUFFIX,
    LOOM_SOURCE_SUFFIX,
    LOOM_TEST_SUFFIX,
    FileMigrationResult,
    MigrationFileDiagnostic,
    MigrationFileKind,
    MigrationRunResult,
    SourceMigrationResult,
    check_bytecode_version,
    classify_file,
    default_migration_ops,
    default_migration_rules,
    default_migration_types,
    discover_migration_files,
    migrate_file,
    migrate_files,
    migrate_loom_test_text,
    migrate_source_text,
    validate_current_source,
)
from loom.migration.manifest import (
    CURRENT_BYTECODE_VERSION,
    CURRENT_MANIFEST,
    CURRENT_TEXT_BASELINE,
    DIAGNOSTIC_ERROR,
    DIAGNOSTIC_WARNING,
    REQUIRED_ACTIVE_RULE_TEST_KINDS,
    RULE_TEST_CURRENT_NOOP,
    RULE_TEST_CURRENT_PARSE,
    RULE_TEST_IDEMPOTENCE,
    RULE_TEST_LEGACY_REWRITE,
    LoomRelease,
    MigrationDiagnostic,
    MigrationLintReport,
    MigrationManifest,
    MigrationRuleMetadata,
    TextBaseline,
    lint_current_manifest,
    lint_legacy_formats,
    migration_rule_metadata_from_ops,
)
from loom.migration.rules import (
    BUFFER_ASSUME_MEMORY_SPACE_ATTR_DICT_RULE_ID,
    MigrationRewrite,
    MigrationRule,
    MigrationRuleApplication,
    migration_rules_from_ops,
)
from loom.migration.source import (
    MigrationSourceDiagnostic,
    SourceDocument,
    SourceEdit,
    apply_source_edits,
)

__all__ = [
    "CURRENT_BYTECODE_VERSION",
    "CURRENT_MANIFEST",
    "CURRENT_TEXT_BASELINE",
    "DIAGNOSTIC_ERROR",
    "DIAGNOSTIC_WARNING",
    "BUFFER_ASSUME_MEMORY_SPACE_ATTR_DICT_RULE_ID",
    "LOOM_BYTECODE_SUFFIX",
    "LOOM_SOURCE_SUFFIX",
    "LOOM_TEST_SUFFIX",
    "REQUIRED_ACTIVE_RULE_TEST_KINDS",
    "RULE_TEST_CURRENT_NOOP",
    "RULE_TEST_CURRENT_PARSE",
    "RULE_TEST_IDEMPOTENCE",
    "RULE_TEST_LEGACY_REWRITE",
    "FileMigrationResult",
    "LoomRelease",
    "MigrationDiagnostic",
    "MigrationFileDiagnostic",
    "MigrationFileKind",
    "MigrationLintReport",
    "MigrationManifest",
    "MigrationRule",
    "MigrationRuleApplication",
    "MigrationRewrite",
    "MigrationRuleMetadata",
    "MigrationRunResult",
    "MigrationSourceDiagnostic",
    "SourceDocument",
    "SourceEdit",
    "SourceMigrationResult",
    "TextBaseline",
    "apply_source_edits",
    "check_bytecode_version",
    "classify_file",
    "default_migration_ops",
    "default_migration_rules",
    "default_migration_types",
    "discover_migration_files",
    "lint_legacy_formats",
    "lint_current_manifest",
    "migrate_file",
    "migrate_files",
    "migrate_loom_test_text",
    "migrate_source_text",
    "migration_rule_metadata_from_ops",
    "migration_rules_from_ops",
    "validate_current_source",
]
