# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# bazel-to-cmake: skip

load(
    "@hrx//loom/build_tools/bazel:defs.bzl",
    "loom_library",
    "loom_test_library",
)

package(
    default_visibility = ["//visibility:private"],
    licenses = ["notice"],  # Apache 2.0
)

loom_library(
    name = "kernel",
    srcs = ["kernel.loom"],
)

loom_test_library(
    name = "tests",
    srcs = ["tests.loom"],
    deps = [":kernel"],
)
