# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# bazel-to-cmake: skip

# --8<-- [start:products]
load(
    "@hrx//loom/build_tools/bazel:defs.bzl",
    "loom_command_binary",
    "loom_kernel_binary",
    "loom_library",
    "loom_vm_binary",
)
load("@rules_shell//shell:sh_test.bzl", "sh_test")

package(
    default_visibility = ["//visibility:private"],
    licenses = ["notice"],  # Apache 2.0
)

loom_library(
    name = "motif",
    srcs = ["motif.loom"],
)

loom_library(
    name = "kernel",
    srcs = ["kernel.loom"],
    deps = [":motif"],
)

loom_library(
    name = "model",
    srcs = ["model.loom"],
    deps = [":kernel"],
)

loom_kernel_binary(
    name = "elementwise_kernel",
    target = "@hrx//loom/target/amdgpu:gfx11-generic",
    deps = [":kernel"],
)

loom_command_binary(
    name = "elementwise_command",
    roots = ["@elementwise_transform"],
    target = "@hrx//loom/target/amdgpu:gfx11-generic",
    deps = [":model"],
)

loom_library(
    name = "vm",
    srcs = ["vm.loom"],
)

loom_vm_binary(
    name = "elementwise_vm",
    deps = [":vm"],
)
# --8<-- [end:products]

sh_test(
    name = "product_test",
    srcs = ["product_test.sh"],
    args = ["$(rootpath //tools:iree-dump-module)"],
    data = [
        ":elementwise_command",
        ":elementwise_kernel",
        ":elementwise_vm",
        "//tools:iree-dump-module",
    ],
)

test_suite(
    name = "test",
    tests = [
        ":kernel_test",
        ":model_test",
        ":motif_test",
        ":product_test",
    ],
)
