# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""Declarative IREE VM bytecode specification.

The package contains architectural facts and projection utilities only. It
does not generate or implement runtime, loader, verifier, or compiler control
flow.
"""

from model.schema import (
    BYTES_ARGUMENT,
    ENTITY_ARGUMENT,
    FIELD_ARGUMENT,
    I16,
    I32,
    INTEGER_ARGUMENT,
    SCALAR_ENCODINGS,
    TEXT_ARGUMENT,
    U8,
    U16,
    U32,
    U64,
    ArgumentKind,
    ArgumentShape,
    EntityReference,
    FieldReference,
    NumericTable,
    NumericTableKind,
    NumericValue,
    RuleParameter,
    RuleUse,
    ScalarEncoding,
    UnknownNumericValuePolicy,
    ValidationRule,
    ValidationScope,
    WireField,
    WireRecord,
    WireRecordLayout,
    selected_numeric_values,
    selected_record_layouts,
)
from model.specification import (
    ARCHITECTURAL_EXTENSION_PAGE_MAX,
    ARCHITECTURAL_EXTENSION_PAGE_MIN,
    CORE_0,
    CORE_DOMAIN,
    CORE_PAGE_ID,
    HAL_0,
    HAL_DOMAIN,
    RESERVED_EXPERIMENT_PAGE_ID,
    RESERVED_EXTENDED_ESCAPE_PAGE_ID,
    VERSION_DOMAINS,
    Entity,
    NormativeClause,
    Projection,
    ReleaseDiff,
    Specification,
    Version,
    VersionDomain,
    compare_projections,
)

__all__ = [
    "ARCHITECTURAL_EXTENSION_PAGE_MAX",
    "ARCHITECTURAL_EXTENSION_PAGE_MIN",
    "ArgumentKind",
    "ArgumentShape",
    "BYTES_ARGUMENT",
    "CORE_0",
    "CORE_DOMAIN",
    "CORE_PAGE_ID",
    "Entity",
    "ENTITY_ARGUMENT",
    "EntityReference",
    "FIELD_ARGUMENT",
    "FieldReference",
    "HAL_0",
    "HAL_DOMAIN",
    "I16",
    "I32",
    "INTEGER_ARGUMENT",
    "NumericTable",
    "NumericTableKind",
    "NumericValue",
    "NormativeClause",
    "Projection",
    "ReleaseDiff",
    "RESERVED_EXPERIMENT_PAGE_ID",
    "RESERVED_EXTENDED_ESCAPE_PAGE_ID",
    "RuleParameter",
    "RuleUse",
    "SCALAR_ENCODINGS",
    "Specification",
    "TEXT_ARGUMENT",
    "U8",
    "U16",
    "U32",
    "U64",
    "ScalarEncoding",
    "UnknownNumericValuePolicy",
    "ValidationRule",
    "ValidationScope",
    "Version",
    "VersionDomain",
    "VERSION_DOMAINS",
    "WireField",
    "WireRecord",
    "WireRecordLayout",
    "compare_projections",
    "selected_numeric_values",
    "selected_record_layouts",
]
