#!/usr/bin/env python3
# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
"""Generates Loom AMDGPU target configuration fragments.

The root `build_tools/amdgpu` target map owns shared AMDGPU selector vocabulary
and exact-target to code-object mapping. Loom's target-info table owns the
compiler-supported processors and their descriptor-set assignments. This script
joins those facts into small Bazel/CMake fragments consumed by Loom config and
target packages.
"""

from __future__ import annotations

import argparse
import difflib
import importlib.util
import sys
from pathlib import Path

TARGET_SOURCE_LOOM_DEFAULTS = "loom_defaults"
TARGET_SOURCE_IREE_HAL = "iree_hal"
_AMDGPU_NAMES = None


def find_repo_root() -> Path:
    current = Path(__file__).resolve()
    while current != current.parent:
        if (current / "runtime" / "src" / "iree").exists():
            return current
        current = current.parent
    print("error: could not find IREE repository root", file=sys.stderr)
    sys.exit(1)


def load_module(module_name: str, path: Path):
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"could not load module {module_name} from {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


def configure_name_helpers(repo_root: Path) -> None:
    global _AMDGPU_NAMES
    _AMDGPU_NAMES = load_module(
        "loom_amdgpu_names",
        repo_root / "loom/py/loom/target/arch/amdgpu/names.py",
    )


def name_helpers():
    if _AMDGPU_NAMES is None:
        raise RuntimeError("AMDGPU name helpers were not configured")
    return _AMDGPU_NAMES


def generated_header(comment_prefix: str, output_path: str) -> str:
    return "\n".join(
        [
            f"{comment_prefix} Generated by loom/build_tools/amdgpu/target_config.py.",
            f"{comment_prefix} Do not edit directly; edit Loom AMDGPU target-info rows and regenerate.",
            f"{comment_prefix} Output: {output_path}",
        ]
    )


def descriptor_set_capability(key: str) -> str:
    return name_helpers().amdgpu_descriptor_set_capability(key)


def low_descriptor_header(info) -> str:
    return name_helpers().amdgpu_low_descriptor_header(info)


def low_descriptor_provider_symbol(key: str) -> str:
    return name_helpers().amdgpu_low_descriptor_provider_symbol(key)


def descriptor_set_define(capability: str) -> str:
    return "LOOM_AMDGPU_" + capability.upper()


def is_generic_processor(info) -> bool:
    return info.processor.endswith("-generic")


def is_exact_processor(info) -> bool:
    return not is_generic_processor(info)


class TargetConfig:
    def __init__(self, target_info, root_target_map):
        self._target_info = target_info
        self._root_target_map = root_target_map
        self._processor_infos = {
            info.processor: info for info in target_info.AMDGPU_PROCESSOR_INFOS
        }
        self._descriptor_set_infos = {
            info.key: info for info in target_info.AMDGPU_DESCRIPTOR_SET_INFOS
        }
        self._target_records = target_info.sorted_target_record_infos()
        self._validate()
        self._supported_processor_infos = self._compute_supported_processor_infos()
        self._supported_exact_processor_infos = [
            info for info in self._supported_processor_infos if is_exact_processor(info)
        ]
        self._supported_code_object_processor_infos = [
            info
            for info in self._supported_processor_infos
            if is_generic_processor(info)
        ]

    def _validate(self) -> None:
        exact_targets = set(self._root_target_map.exact_targets())
        code_object_targets = set(self._root_target_map.code_object_targets())
        descriptor_backed_keys = self._validate_processor_infos(
            exact_targets, code_object_targets
        )
        self._validate_target_records(exact_targets, code_object_targets)
        self._validate_descriptor_set_defaults(descriptor_backed_keys)

    def _validate_processor_infos(
        self, exact_targets: set[str], code_object_targets: set[str]
    ) -> set[str]:
        seen_processors: set[str] = set()
        descriptor_backed_keys: set[str] = set()
        for processor_info in self._target_info.AMDGPU_PROCESSOR_INFOS:
            if processor_info.processor in seen_processors:
                raise ValueError(
                    f"duplicate processor row for {processor_info.processor}"
                )
            seen_processors.add(processor_info.processor)

            if is_generic_processor(processor_info):
                if processor_info.processor not in code_object_targets:
                    raise ValueError(
                        f"Loom AMDGPU generic processor {processor_info.processor} "
                        "is absent from the shared AMDGPU code-object target map"
                    )
            if not processor_info.descriptor_set_key:
                continue
            if is_generic_processor(processor_info):
                if processor_info.processor not in code_object_targets:
                    raise ValueError(
                        f"Loom AMDGPU descriptor-backed generic processor "
                        f"{processor_info.processor} is absent from the shared "
                        "AMDGPU code-object target map"
                    )
            elif processor_info.processor not in exact_targets:
                raise ValueError(
                    f"Loom AMDGPU descriptor-backed processor "
                    f"{processor_info.processor} is absent from the shared AMDGPU "
                    "exact target map"
                )
            if processor_info.descriptor_set_key not in self._descriptor_set_infos:
                raise ValueError(
                    f"Loom AMDGPU processor {processor_info.processor} references "
                    f"unknown descriptor set {processor_info.descriptor_set_key}"
                )
            descriptor_backed_keys.add(processor_info.descriptor_set_key)

        missing_code_object_processors = sorted(code_object_targets - seen_processors)
        if missing_code_object_processors:
            raise ValueError(
                "shared AMDGPU code-object targets missing Loom processor rows: "
                + ", ".join(missing_code_object_processors)
            )
        missing_exact_processors = sorted(exact_targets - seen_processors)
        if missing_exact_processors:
            raise ValueError(
                "shared AMDGPU exact targets missing Loom processor rows: "
                + ", ".join(missing_exact_processors)
            )
        return descriptor_backed_keys

    def _validate_target_records(
        self, exact_targets: set[str], code_object_targets: set[str]
    ) -> None:
        seen_processors: set[str] = set()
        for record in self._target_records:
            if record.processor in seen_processors:
                raise ValueError(f"duplicate target record for {record.processor}")
            seen_processors.add(record.processor)
            if is_generic_processor(record):
                if record.processor not in code_object_targets:
                    raise ValueError(
                        f"Loom AMDGPU target record {record.processor} is absent "
                        "from the shared AMDGPU code-object target map"
                    )
            elif record.processor not in exact_targets:
                raise ValueError(
                    f"Loom AMDGPU target record {record.processor} is absent from "
                    "the shared AMDGPU exact target map"
                )
            processor_info = self._processor_infos.get(record.processor)
            if processor_info is None:
                raise ValueError(
                    f"Loom AMDGPU target record {record.processor} has no processor row"
                )
            if not processor_info.descriptor_set_key:
                raise ValueError(
                    f"Loom AMDGPU target record {record.processor} has no "
                    "descriptor-set key"
                )
            if processor_info.descriptor_set_key not in self._descriptor_set_infos:
                raise ValueError(
                    f"Loom AMDGPU target record {record.processor} references "
                    f"unknown descriptor set {processor_info.descriptor_set_key}"
                )

    def _validate_descriptor_set_defaults(
        self, descriptor_backed_keys: set[str]
    ) -> None:
        target_record_descriptor_set_keys = {
            self._processor_infos[record.processor].descriptor_set_key
            for record in self._target_records
        }
        missing_defaults = sorted(
            descriptor_backed_keys - target_record_descriptor_set_keys
        )
        if missing_defaults:
            raise ValueError(
                "descriptor-backed Loom AMDGPU processors need default target "
                "records for descriptor sets: " + ", ".join(missing_defaults)
            )

    def _compute_supported_processor_infos(self) -> list:
        processor_infos_by_descriptor_set = {
            key: [] for key in self.descriptor_set_keys
        }
        for processor_info in self._target_info.sorted_processor_infos():
            if not processor_info.descriptor_set_key:
                continue
            processor_infos_by_descriptor_set[processor_info.descriptor_set_key].append(
                processor_info
            )
        supported_processor_infos = []
        for key in self.descriptor_set_keys:
            supported_processor_infos.extend(processor_infos_by_descriptor_set[key])
        return supported_processor_infos

    @property
    def supported_processors(self) -> list[str]:
        return [info.processor for info in self._supported_processor_infos]

    @property
    def supported_exact_processors(self) -> list[str]:
        return [info.processor for info in self._supported_exact_processor_infos]

    @property
    def supported_code_object_processors(self) -> list[str]:
        return [info.processor for info in self._supported_code_object_processor_infos]

    @property
    def descriptor_set_capabilities(self) -> list[str]:
        return [descriptor_set_capability(key) for key in self.descriptor_set_keys]

    @property
    def descriptor_set_keys(self) -> list[str]:
        keys: list[str] = []
        for record in self._target_records:
            key = self._processor_infos[record.processor].descriptor_set_key
            if key not in keys:
                keys.append(key)
        return keys

    def exact_processors_for_descriptor_set(self, key: str) -> list[str]:
        processors: list[str] = []
        for processor_info in self._supported_exact_processor_infos:
            if processor_info.descriptor_set_key == key:
                processors.append(processor_info.processor)
        return processors

    def descriptor_set_info(self, key: str):
        return self._descriptor_set_infos[key]


def bzl_list(name: str, values: list[str]) -> str:
    lines = [f"{name} = ["]
    lines.extend([f'    "{value}",' for value in values])
    lines.append("]")
    return "\n".join(lines)


def bzl_string_dict(name: str, values: list[tuple[str, str]]) -> str:
    lines = [
        "# buildifier: disable=unsorted-dict-items",
        f"{name} = {{",
    ]
    for key, value in values:
        lines.append(f'    "{key}": "{value}",')
    lines.append("}")
    return "\n".join(lines)


def bzl_list_dict(name: str, values: list[tuple[str, list[str]]]) -> str:
    lines = [
        "# buildifier: disable=unsorted-dict-items",
        f"{name} = {{",
    ]
    for key, items in values:
        if len(items) == 1:
            lines.append(f'    "{key}": ["{items[0]}"],')
        else:
            lines.append(f'    "{key}": [')
            lines.extend([f'        "{item}",' for item in items])
            lines.append("    ],")
    lines.append("}")
    return "\n".join(lines)


def render_bzl(config: TargetConfig) -> str:
    output_path = "loom/build_tools/amdgpu/target_config.bzl"
    descriptor_capability_pairs = [
        (key, descriptor_set_capability(key)) for key in config.descriptor_set_keys
    ]
    generator_target_pairs = [
        (
            descriptor_set_capability(key),
            config.descriptor_set_info(key).generator_target,
        )
        for key in config.descriptor_set_keys
    ]
    low_descriptor_header_pairs = [
        (
            descriptor_set_capability(key),
            low_descriptor_header(config.descriptor_set_info(key)),
        )
        for key in config.descriptor_set_keys
    ]
    low_descriptor_provider_pairs = [
        (
            descriptor_set_capability(key),
            low_descriptor_provider_symbol(key),
        )
        for key in config.descriptor_set_keys
    ]
    descriptor_set_define_pairs = [
        (
            descriptor_set_capability(key),
            descriptor_set_define(descriptor_set_capability(key)),
        )
        for key in config.descriptor_set_keys
    ]
    processor_pairs = [
        (
            descriptor_set_capability(key),
            config.exact_processors_for_descriptor_set(key),
        )
        for key in config.descriptor_set_keys
    ]
    return (
        "\n\n".join(
            [
                generated_header("#", output_path),
                '"""Generated Loom AMDGPU target configuration data."""',
                f'LOOM_AMDGPU_TARGET_SOURCE_LOOM_DEFAULTS = "{TARGET_SOURCE_LOOM_DEFAULTS}"',
                f'LOOM_AMDGPU_TARGET_SOURCE_IREE_HAL = "{TARGET_SOURCE_IREE_HAL}"',
                bzl_list(
                    "LOOM_AMDGPU_TARGET_SOURCE_SELECTORS",
                    [TARGET_SOURCE_LOOM_DEFAULTS, TARGET_SOURCE_IREE_HAL],
                ),
                bzl_list(
                    "LOOM_AMDGPU_DEFAULT_TARGET_SELECTORS",
                    [TARGET_SOURCE_LOOM_DEFAULTS],
                ),
                bzl_list(
                    "LOOM_AMDGPU_SUPPORTED_EXACT_PROCESSORS",
                    config.supported_exact_processors,
                ),
                bzl_list(
                    "LOOM_AMDGPU_SUPPORTED_CODE_OBJECT_PROCESSORS",
                    config.supported_code_object_processors,
                ),
                bzl_list(
                    "LOOM_AMDGPU_SUPPORTED_DESCRIPTOR_BACKED_PROCESSORS",
                    config.supported_processors,
                ),
                bzl_list(
                    "LOOM_AMDGPU_DESCRIPTOR_SET_CAPABILITIES",
                    config.descriptor_set_capabilities,
                ),
                bzl_string_dict(
                    "LOOM_AMDGPU_DESCRIPTOR_SET_CAPABILITY_BY_KEY",
                    descriptor_capability_pairs,
                ),
                bzl_list_dict(
                    "LOOM_AMDGPU_DESCRIPTOR_SET_EXACT_PROCESSORS",
                    processor_pairs,
                ),
                bzl_string_dict(
                    "LOOM_AMDGPU_DESCRIPTOR_SET_GENERATOR_TARGETS",
                    generator_target_pairs,
                ),
                bzl_string_dict(
                    "LOOM_AMDGPU_LOW_DESCRIPTOR_HEADERS",
                    low_descriptor_header_pairs,
                ),
                bzl_string_dict(
                    "LOOM_AMDGPU_LOW_DESCRIPTOR_PROVIDER_SYMBOLS",
                    low_descriptor_provider_pairs,
                ),
                bzl_string_dict(
                    "LOOM_AMDGPU_DESCRIPTOR_SET_DEFINES",
                    descriptor_set_define_pairs,
                ),
            ]
        )
        + "\n"
    )


def cmake_list(name: str, values: list[str]) -> str:
    lines = [f"set({name}"]
    lines.extend([f'  "{value}"' for value in values])
    lines.append(")")
    return "\n".join(lines)


def cmake_set(name: str, value: str) -> str:
    return f'set({name} "{value}")'


def render_cmake(config: TargetConfig) -> str:
    output_path = "loom/build_tools/amdgpu/target_config.cmake"
    lines = [
        generated_header("#", output_path),
        "",
        cmake_set(
            "LOOM_AMDGPU_TARGET_SOURCE_LOOM_DEFAULTS", TARGET_SOURCE_LOOM_DEFAULTS
        ),
        cmake_set("LOOM_AMDGPU_TARGET_SOURCE_IREE_HAL", TARGET_SOURCE_IREE_HAL),
        "",
        cmake_list(
            "_LOOM_AMDGPU_TARGET_SOURCE_SELECTORS",
            [TARGET_SOURCE_LOOM_DEFAULTS, TARGET_SOURCE_IREE_HAL],
        ),
        "",
        cmake_list(
            "_LOOM_AMDGPU_DEFAULT_TARGET_SELECTORS",
            [TARGET_SOURCE_LOOM_DEFAULTS],
        ),
        "",
        cmake_list(
            "_LOOM_AMDGPU_SUPPORTED_EXACT_PROCESSORS",
            config.supported_exact_processors,
        ),
        "",
        cmake_list(
            "_LOOM_AMDGPU_SUPPORTED_CODE_OBJECT_PROCESSORS",
            config.supported_code_object_processors,
        ),
        "",
        cmake_list(
            "_LOOM_AMDGPU_SUPPORTED_DESCRIPTOR_BACKED_PROCESSORS",
            config.supported_processors,
        ),
        "",
        cmake_list(
            "_LOOM_AMDGPU_DESCRIPTOR_SET_CAPABILITIES",
            config.descriptor_set_capabilities,
        ),
        "",
    ]
    for key in config.descriptor_set_keys:
        capability = descriptor_set_capability(key)
        info = config.descriptor_set_info(key)
        lines.extend(
            [
                cmake_set(
                    f"_LOOM_AMDGPU_DESCRIPTOR_SET_KEY_{capability}",
                    key,
                ),
                cmake_list(
                    f"_LOOM_AMDGPU_DESCRIPTOR_SET_EXACT_PROCESSORS_{capability}",
                    config.exact_processors_for_descriptor_set(key),
                ),
                cmake_set(
                    f"_LOOM_AMDGPU_DESCRIPTOR_SET_GENERATOR_TARGET_{capability}",
                    info.generator_target,
                ),
                cmake_set(
                    f"_LOOM_AMDGPU_LOW_DESCRIPTOR_HEADER_{capability}",
                    low_descriptor_header(info),
                ),
                cmake_set(
                    f"_LOOM_AMDGPU_LOW_DESCRIPTOR_PROVIDER_SYMBOL_{capability}",
                    low_descriptor_provider_symbol(key),
                ),
                cmake_set(
                    f"_LOOM_AMDGPU_DESCRIPTOR_SET_DEFINE_{capability}",
                    descriptor_set_define(capability),
                ),
                "",
            ]
        )
    return "\n".join(lines)


def generated_outputs(repo_root: Path, config: TargetConfig) -> dict[Path, str]:
    output_dir = repo_root / "loom/build_tools/amdgpu"
    return {
        output_dir / "target_config.bzl": render_bzl(config),
        output_dir / "target_config.cmake": render_cmake(config),
    }


def check_outputs(repo_root: Path, outputs: dict[Path, str]) -> int:
    failed = False
    for path, content in outputs.items():
        if not path.exists():
            print(
                f"error: {path.relative_to(repo_root)} does not exist", file=sys.stderr
            )
            failed = True
            continue
        existing = path.read_text()
        if existing == content:
            continue
        rel_path = path.relative_to(repo_root)
        print(f"error: {rel_path} is out of date", file=sys.stderr)
        diff = difflib.unified_diff(
            existing.splitlines(keepends=True),
            content.splitlines(keepends=True),
            fromfile=str(rel_path),
            tofile=str(rel_path) + " (generated)",
        )
        sys.stderr.writelines(diff)
        failed = True
    if failed:
        print(
            "Run 'python loom/build_tools/amdgpu/target_config.py' to regenerate.",
            file=sys.stderr,
        )
        return 1
    print("Loom AMDGPU target config generated files are up to date.")
    return 0


def write_outputs(outputs: dict[Path, str]) -> int:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"Wrote {path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate Loom AMDGPU target configuration fragments."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check that generated files are up to date without modifying them.",
    )
    args = parser.parse_args()

    repo_root = find_repo_root()
    configure_name_helpers(repo_root)
    target_info = load_module(
        "loom_amdgpu_target_info",
        repo_root / "loom/py/loom/target/arch/amdgpu/target_info.py",
    )
    root_target_map = load_module(
        "iree_amdgpu_target_map",
        repo_root / "build_tools/amdgpu/target_map.py",
    )
    root_target_map.validate_target_map()
    config = TargetConfig(target_info, root_target_map)
    outputs = generated_outputs(repo_root, config)
    if args.check:
        return check_outputs(repo_root, outputs)
    return write_outputs(outputs)


if __name__ == "__main__":
    sys.exit(main())
