# Generated by loom/build_tools/amdgpu/target_config.py.
# Do not edit directly; edit Loom AMDGPU target-info rows and regenerate.
# Output: loom/build_tools/amdgpu/target_config.bzl

"""Generated Loom AMDGPU target configuration data."""

LOOM_AMDGPU_TARGET_SOURCE_LOOM_DEFAULTS = "loom_defaults"

LOOM_AMDGPU_TARGET_SOURCE_IREE_HAL = "iree_hal"

LOOM_AMDGPU_TARGET_SOURCE_SELECTORS = [
    "loom_defaults",
    "iree_hal",
]

LOOM_AMDGPU_DEFAULT_TARGET_SELECTORS = [
    "loom_defaults",
]

LOOM_AMDGPU_SUPPORTED_EXACT_PROCESSORS = [
    "gfx940",
    "gfx941",
    "gfx942",
    "gfx950",
    "gfx1100",
    "gfx1101",
    "gfx1102",
    "gfx1103",
    "gfx1150",
    "gfx1151",
    "gfx1152",
    "gfx1153",
    "gfx1200",
    "gfx1201",
    "gfx1250",
    "gfx1251",
    "gfx1170",
    "gfx1171",
    "gfx1172",
]

LOOM_AMDGPU_SUPPORTED_CODE_OBJECT_PROCESSORS = [
    "gfx11-generic",
    "gfx12-generic",
    "gfx12-5-generic",
]

LOOM_AMDGPU_SUPPORTED_DESCRIPTOR_BACKED_PROCESSORS = [
    "gfx940",
    "gfx941",
    "gfx942",
    "gfx950",
    "gfx11-generic",
    "gfx1100",
    "gfx1101",
    "gfx1102",
    "gfx1103",
    "gfx1150",
    "gfx1151",
    "gfx1152",
    "gfx1153",
    "gfx12-generic",
    "gfx1200",
    "gfx1201",
    "gfx12-5-generic",
    "gfx1250",
    "gfx1251",
    "gfx1170",
    "gfx1171",
    "gfx1172",
]

LOOM_AMDGPU_DESCRIPTOR_SET_CAPABILITIES = [
    "descriptor_set_cdna3_core",
    "descriptor_set_cdna4_core",
    "descriptor_set_rdna3_core",
    "descriptor_set_rdna4_core",
    "descriptor_set_rdna4_gfx125x_core",
    "descriptor_set_rdna3_5_core",
]

# buildifier: disable=unsorted-dict-items
LOOM_AMDGPU_DESCRIPTOR_SET_CAPABILITY_BY_KEY = {
    "amdgpu.cdna3.core": "descriptor_set_cdna3_core",
    "amdgpu.cdna4.core": "descriptor_set_cdna4_core",
    "amdgpu.rdna3.core": "descriptor_set_rdna3_core",
    "amdgpu.rdna4.core": "descriptor_set_rdna4_core",
    "amdgpu.rdna4.gfx125x.core": "descriptor_set_rdna4_gfx125x_core",
    "amdgpu.rdna3_5.core": "descriptor_set_rdna3_5_core",
}

# buildifier: disable=unsorted-dict-items
LOOM_AMDGPU_DESCRIPTOR_SET_EXACT_PROCESSORS = {
    "descriptor_set_cdna3_core": [
        "gfx940",
        "gfx941",
        "gfx942",
    ],
    "descriptor_set_cdna4_core": ["gfx950"],
    "descriptor_set_rdna3_core": [
        "gfx1100",
        "gfx1101",
        "gfx1102",
        "gfx1103",
        "gfx1150",
        "gfx1151",
        "gfx1152",
        "gfx1153",
    ],
    "descriptor_set_rdna4_core": [
        "gfx1200",
        "gfx1201",
    ],
    "descriptor_set_rdna4_gfx125x_core": [
        "gfx1250",
        "gfx1251",
    ],
    "descriptor_set_rdna3_5_core": [
        "gfx1170",
        "gfx1171",
        "gfx1172",
    ],
}

# buildifier: disable=unsorted-dict-items
LOOM_AMDGPU_DESCRIPTOR_SET_GENERATOR_TARGETS = {
    "descriptor_set_cdna3_core": "cdna3",
    "descriptor_set_cdna4_core": "cdna4",
    "descriptor_set_rdna3_core": "rdna3",
    "descriptor_set_rdna4_core": "rdna4",
    "descriptor_set_rdna4_gfx125x_core": "rdna4_gfx125x",
    "descriptor_set_rdna3_5_core": "rdna3_5",
}

# buildifier: disable=unsorted-dict-items
LOOM_AMDGPU_LOW_DESCRIPTOR_HEADERS = {
    "descriptor_set_cdna3_core": "loom/target/arch/amdgpu/descriptors/cdna3_descriptors.h",
    "descriptor_set_cdna4_core": "loom/target/arch/amdgpu/descriptors/cdna4_descriptors.h",
    "descriptor_set_rdna3_core": "loom/target/arch/amdgpu/descriptors/rdna3_descriptors.h",
    "descriptor_set_rdna4_core": "loom/target/arch/amdgpu/descriptors/rdna4_descriptors.h",
    "descriptor_set_rdna4_gfx125x_core": "loom/target/arch/amdgpu/descriptors/rdna4_gfx125x_descriptors.h",
    "descriptor_set_rdna3_5_core": "loom/target/arch/amdgpu/descriptors/rdna3_5_descriptors.h",
}

# buildifier: disable=unsorted-dict-items
LOOM_AMDGPU_LOW_DESCRIPTOR_PROVIDER_SYMBOLS = {
    "descriptor_set_cdna3_core": "loom_amdgpu_cdna3_core_descriptor_set",
    "descriptor_set_cdna4_core": "loom_amdgpu_cdna4_core_descriptor_set",
    "descriptor_set_rdna3_core": "loom_amdgpu_rdna3_core_descriptor_set",
    "descriptor_set_rdna4_core": "loom_amdgpu_rdna4_core_descriptor_set",
    "descriptor_set_rdna4_gfx125x_core": "loom_amdgpu_rdna4_gfx125x_core_descriptor_set",
    "descriptor_set_rdna3_5_core": "loom_amdgpu_rdna3_5_core_descriptor_set",
}

# buildifier: disable=unsorted-dict-items
LOOM_AMDGPU_DESCRIPTOR_SET_DEFINES = {
    "descriptor_set_cdna3_core": "LOOM_AMDGPU_DESCRIPTOR_SET_CDNA3_CORE",
    "descriptor_set_cdna4_core": "LOOM_AMDGPU_DESCRIPTOR_SET_CDNA4_CORE",
    "descriptor_set_rdna3_core": "LOOM_AMDGPU_DESCRIPTOR_SET_RDNA3_CORE",
    "descriptor_set_rdna4_core": "LOOM_AMDGPU_DESCRIPTOR_SET_RDNA4_CORE",
    "descriptor_set_rdna4_gfx125x_core": "LOOM_AMDGPU_DESCRIPTOR_SET_RDNA4_GFX125X_CORE",
    "descriptor_set_rdna3_5_core": "LOOM_AMDGPU_DESCRIPTOR_SET_RDNA3_5_CORE",
}
