# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""Bazel composition rules for statically linked external HAL drivers."""

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc/common:cc_info.bzl", "CcInfo")

visibility("public")

IreeHalDriverModuleInfo = provider(
    doc = "Registration metadata for one statically linked HAL driver module.",
    fields = {
        "registration_function": "C function that registers the module.",
        "registration_header": "C header declaring the registration function.",
    },
)

_EXTERNAL_REGISTRY_API = Label(
    "//runtime/src/iree/hal/drivers:external_registry_api",
)

def _validate_c_identifier(value, attribute_name, owner):
    if not value:
        fail("%s must set %s" % (owner, attribute_name))
    initial_characters = "_ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
    remaining_characters = initial_characters + "0123456789"
    if value[0] not in initial_characters:
        fail("%s has invalid %s %r" % (owner, attribute_name, value))
    for index in range(1, len(value)):
        character = value[index]
        if character not in remaining_characters:
            fail("%s has invalid %s %r" % (owner, attribute_name, value))

def _validate_header_path(value, owner):
    if not value:
        fail("%s must set registration_header" % owner)
    if value.startswith("/") or value.startswith("\\"):
        fail("%s registration_header must be an include path, got %r" % (owner, value))
    if "\\" in value or "\"" in value or "\n" in value or "\r" in value:
        fail("%s has invalid registration_header %r" % (owner, value))
    if ".." in value.split("/"):
        fail("%s registration_header must not escape its include tree, got %r" % (owner, value))

def _iree_hal_driver_module_impl(ctx):
    _validate_header_path(ctx.attr.registration_header, ctx.label)
    _validate_c_identifier(
        ctx.attr.registration_function,
        "registration_function",
        ctx.label,
    )
    return [
        ctx.attr.registration[CcInfo],
        IreeHalDriverModuleInfo(
            registration_function = ctx.attr.registration_function,
            registration_header = ctx.attr.registration_header,
        ),
    ]

iree_hal_driver_module = rule(
    implementation = _iree_hal_driver_module_impl,
    attrs = {
        "registration": attr.label(
            mandatory = True,
            providers = [CcInfo],
            doc = "C/C++ library implementing the registration function.",
        ),
        "registration_function": attr.string(
            mandatory = True,
            doc = "C function that registers the module with an IREE HAL registry.",
        ),
        "registration_header": attr.string(
            mandatory = True,
            doc = "C include path declaring registration_function.",
        ),
    },
    doc = "Attaches static HAL driver registration metadata to a C/C++ library.",
    provides = [CcInfo, IreeHalDriverModuleInfo],
)

def _iree_hal_driver_registry_source_impl(ctx):
    headers = []
    seen_headers = {}
    seen_functions = {}
    modules = []
    for target in ctx.attr.modules:
        module = target[IreeHalDriverModuleInfo]
        previous_target = seen_functions.get(module.registration_function)
        if previous_target != None:
            fail(
                "%s and %s both use registration function %s" %
                (previous_target, target.label, module.registration_function),
            )
        seen_functions[module.registration_function] = target.label
        if module.registration_header not in seen_headers:
            headers.append(module.registration_header)
            seen_headers[module.registration_header] = True
        modules.append(module)

    lines = [
        "// Generated by iree_hal_driver_registry. Do not edit.",
        "",
        '#include "iree/hal/drivers/external_registry.h"',
    ]
    for header in headers:
        lines.append('#include "%s"' % header)
    lines.extend([
        "",
        "iree_status_t iree_hal_register_external_drivers(",
        "    iree_hal_driver_registry_t* registry) {",
    ])
    for module in modules:
        lines.append(
            "  IREE_RETURN_IF_ERROR(%s(registry));" %
            module.registration_function,
        )
    lines.extend([
        "  return iree_ok_status();",
        "}",
        "",
    ])

    output = ctx.actions.declare_file(ctx.label.name + ".c")
    ctx.actions.write(output = output, content = "\n".join(lines))
    return [DefaultInfo(files = depset([output]))]

_iree_hal_driver_registry_source = rule(
    implementation = _iree_hal_driver_registry_source_impl,
    attrs = {
        "modules": attr.label_list(
            providers = [IreeHalDriverModuleInfo],
            doc = "Ordered external HAL driver modules to register.",
        ),
    },
)

def iree_hal_driver_registry(name, modules, **kwargs):
    """Generates a C/C++ library registering an ordered set of HAL modules.

    The resulting library defines `iree_hal_register_external_drivers`. Exactly
    one such library should be selected for a final runtime binary. Modules are
    called in list order, so later modules take precedence when factories expose
    the same driver name.

    Args:
      name: Target name for the generated C/C++ library.
      modules: Ordered labels providing IreeHalDriverModuleInfo.
      **kwargs: Additional cc_library attributes.
    """
    source_target = name + "_source"
    source_kwargs = {
        "modules": modules,
        "name": source_target,
        "visibility": ["//visibility:private"],
    }
    if "tags" in kwargs:
        source_kwargs["tags"] = kwargs["tags"]
    if "testonly" in kwargs:
        source_kwargs["testonly"] = kwargs["testonly"]
    _iree_hal_driver_registry_source(**source_kwargs)

    if "srcs" in kwargs:
        fail("iree_hal_driver_registry owns its generated srcs")
    additional_deps = kwargs.pop("deps", [])
    cc_library(
        name = name,
        srcs = [":" + source_target],
        deps = [_EXTERNAL_REGISTRY_API] + modules + additional_deps,
        **kwargs
    )
