# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load(":build_defs.bzl", "xdna_cc_binary", "xdna_execution_test_suite")

package(
    default_visibility = ["//visibility:private"],
    features = ["layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

xdna_execution_test_suite(
    name = "cli_test",
    manifests = ["iree-xdna-run.test.json"],
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "@platforms//os:windows": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    tools = {"iree-xdna-run": ":iree-xdna-run"},
)

xdna_cc_binary(
    name = "iree-xdna-run",
    srcs = ["iree-xdna-run.c"],
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "@platforms//os:windows": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    visibility = ["//experimental/xdna/cts:__pkg__"],
    deps = [
        "//libamdf:amdf_static",
        "//libamdf:headers",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/tooling:flags",
        "//runtime/src/iree/hal",
        "//runtime/src/iree/hal/drivers/amd:status",
        "//runtime/src/iree/hal/drivers/amd/xdna:executable_storage",
        "//runtime/src/iree/hal/drivers/amd/xdna/image/aie2p:npu2",
        "//runtime/src/iree/io:file_handle",
    ],
)
