// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#include "loom/format/text/printer/format_signatures.h"

#include "loom/format/text/printer/atoms.h"
#include "loom/ir/module.h"
#include "loom/ops/op_defs.h"

//===----------------------------------------------------------------------===//
// Generated-format signature payloads
//===----------------------------------------------------------------------===//

// Returns the signature argument IDs for a FuncArgs element. Bodyful func-like
// ops use the entry block args; bodyless declarations store signature args as
// op operands.
static const loom_value_id_t* loom_print_func_arg_ids(
    const loom_op_t* op, const loom_op_vtable_t* vtable,
    uint16_t* out_arg_count) {
  *out_arg_count = 0;
  if (vtable->func_like) {
    if (vtable->func_like->args_as_operands) {
      *out_arg_count = op->operand_count;
      return loom_op_const_operands(op);
    }
    uint8_t body_index = vtable->func_like->body_region_index;
    if (body_index == LOOM_REGION_INDEX_NONE ||
        body_index >= op->region_count) {
      return NULL;
    }
    loom_region_t* body = loom_op_regions(op)[body_index];
    if (!body || body->block_count == 0) {
      return NULL;
    }
    const loom_block_t* block = loom_region_const_entry_block(body);
    *out_arg_count = block->arg_count;
    return block->arg_ids;
  }

  loom_region_t** regions = loom_op_regions(op);
  if (op->region_count > 0 && regions[0] && regions[0]->block_count > 0) {
    const loom_block_t* block = loom_region_const_entry_block(regions[0]);
    *out_arg_count = block->arg_count;
    return block->arg_ids;
  }
  if (op->operand_count > 0) {
    *out_arg_count = op->operand_count;
    return loom_op_const_operands(op);
  }
  return NULL;
}

static const loom_value_id_t* loom_print_region_entry_arg_ids(
    const loom_op_t* op, uint8_t region_index, uint16_t* out_arg_count) {
  *out_arg_count = 0;
  if (region_index >= op->region_count) {
    return NULL;
  }
  loom_region_t* region = loom_op_regions(op)[region_index];
  if (!region || region->block_count == 0) {
    return NULL;
  }
  const loom_block_t* block = loom_region_const_entry_block(region);
  *out_arg_count = block->arg_count;
  return block->arg_ids;
}

// Returns the operand domain used for tied-result printing. Regular body ops
// tie to op operands; symbol-defining func-like ops tie to signature args.
static const loom_value_id_t* loom_print_tied_operand_ids(
    const loom_op_t* op, const loom_op_vtable_t* vtable,
    uint16_t* out_operand_count) {
  if (vtable->func_like &&
      iree_any_bit_set(vtable->traits, LOOM_TRAIT_SYMBOL_DEFINE)) {
    return loom_print_func_arg_ids(op, vtable, out_operand_count);
  }
  *out_operand_count = op->operand_count;
  return loom_op_const_operands(op);
}

// Returns true if |value_id| has a user-assigned SSA name in the module's
// string table instead of an autogenerated numeric fallback.
static bool loom_print_value_has_name(const loom_module_t* module,
                                      loom_value_id_t value_id) {
  if (value_id >= module->values.count) {
    return false;
  }
  loom_string_id_t name_id = module->values.entries[value_id].name_id;
  return name_id != LOOM_STRING_ID_INVALID && name_id < module->strings.count;
}

iree_status_t loom_print_result_type_list(
    loom_print_context_t* ctx, const loom_op_t* op,
    const loom_op_vtable_t* vtable, const loom_format_element_t* element) {
  bool use_parens = (element->data & LOOM_RESULT_TYPE_LIST_PARENS) != 0;
  if (use_parens) {
    IREE_RETURN_IF_ERROR(loom_print_emit_cstr(ctx, "(", false));
  }
  const bool is_symbol_definition =
      iree_any_bit_set(vtable->traits, LOOM_TRAIT_SYMBOL_DEFINE);
  uint16_t tied_operand_count = 0;
  const loom_value_id_t* tied_operand_ids =
      loom_print_tied_operand_ids(op, vtable, &tied_operand_count);
  for (uint16_t j = 0; j < op->result_count; ++j) {
    if (j > 0) {
      IREE_RETURN_IF_ERROR(loom_print_emit_cstr(ctx, ",", false));
    }

    const loom_tied_result_t* tied = loom_op_tied_results(op);
    bool is_tied = false;
    for (uint8_t t = 0; t < op->tied_result_count; ++t) {
      if (tied[t].result_index == j) {
        if (tied[t].operand_index >= tied_operand_count || !tied_operand_ids) {
          return iree_make_status(
              IREE_STATUS_INVALID_ARGUMENT,
              "tied result %u references operand %u but op has %u operands",
              tied[t].result_index, tied[t].operand_index, tied_operand_count);
        }
        loom_value_id_t tied_operand_id =
            tied_operand_ids[tied[t].operand_index];
        IREE_RETURN_IF_ERROR(loom_print_value_name(ctx, tied_operand_id));
        IREE_RETURN_IF_ERROR(loom_print_emit_cstr(ctx, "as", false));
        is_tied = true;
        break;
      }
    }
    if (!is_tied && is_symbol_definition &&
        loom_print_value_has_name(ctx->module, loom_op_const_results(op)[j])) {
      IREE_RETURN_IF_ERROR(
          loom_print_value_name(ctx, loom_op_const_results(op)[j]));
      IREE_RETURN_IF_ERROR(loom_print_emit_cstr(ctx, ":", true));
    }
    IREE_RETURN_IF_ERROR(loom_print_space_if_needed(ctx));
    IREE_RETURN_IF_ERROR(
        loom_print_result_value_type(ctx, loom_op_const_results(op)[j]));
    loom_print_did_write(ctx);
  }
  if (use_parens) {
    IREE_RETURN_IF_ERROR(loom_print_emit_cstr(ctx, ")", false));
  }
  return iree_ok_status();
}

iree_status_t loom_print_binding_list(loom_print_context_t* ctx,
                                      const loom_op_t* op,
                                      const loom_op_vtable_t* vtable,
                                      const loom_format_element_t* element) {
  loom_value_slice_t operands =
      loom_op_operand_field_span(vtable, op, element->field_index);
  uint16_t binding_count = operands.count;
  loom_region_t** regions = loom_op_regions(op);
  const loom_block_t* block = NULL;
  if (op->region_count > 0 && regions[0] && regions[0]->block_count > 0) {
    block = loom_region_const_entry_block(regions[0]);
  }
  uint16_t block_arg_offset = 0;
  if (block && block->arg_count > binding_count) {
    block_arg_offset = block->arg_count - binding_count;
  }
  IREE_RETURN_IF_ERROR(loom_print_emit_cstr(ctx, "(", true));
  for (uint16_t j = 0; j < binding_count; ++j) {
    if (j > 0) {
      IREE_RETURN_IF_ERROR(loom_print_emit_cstr(ctx, ",", false));
    }
    if (block && (block_arg_offset + j) < block->arg_count) {
      IREE_RETURN_IF_ERROR(loom_print_value_name(
          ctx, loom_block_arg_id(block, (uint16_t)(block_arg_offset + j))));
    }
    IREE_RETURN_IF_ERROR(loom_print_emit_cstr(ctx, "=", false));
    const loom_value_id_t* operand_ptr = &operands.values[j];
    uint16_t operand_index =
        (uint16_t)(operand_ptr - loom_op_const_operands(op));
    IREE_RETURN_IF_ERROR(loom_print_value_name_with_field(
        ctx, *operand_ptr,
        loom_print_field_ref(LOOM_PRINT_FIELD_OPERAND, operand_index)));
    IREE_RETURN_IF_ERROR(loom_print_emit_cstr(ctx, ":", false));
    IREE_RETURN_IF_ERROR(loom_print_space_if_needed(ctx));
    IREE_RETURN_IF_ERROR(loom_print_value_type(ctx, *operand_ptr));
    loom_print_did_write(ctx);
  }
  return loom_print_emit_cstr(ctx, ")", false);
}

iree_status_t loom_print_block_args(loom_print_context_t* ctx,
                                    const loom_op_t* op,
                                    const loom_format_element_t* element) {
  uint16_t arg_count = 0;
  const loom_value_id_t* arg_ids =
      loom_print_region_entry_arg_ids(op, element->field_index, &arg_count);
  IREE_RETURN_IF_ERROR(loom_print_emit_cstr(ctx, "(", true));
  for (uint16_t j = 0; j < arg_count; ++j) {
    if (j > 0) {
      IREE_RETURN_IF_ERROR(loom_print_emit_cstr(ctx, ",", false));
    }
    IREE_RETURN_IF_ERROR(loom_print_value_name(ctx, arg_ids[j]));
    IREE_RETURN_IF_ERROR(loom_print_emit_cstr(ctx, ":", true));
    IREE_RETURN_IF_ERROR(loom_print_space_if_needed(ctx));
    IREE_RETURN_IF_ERROR(loom_print_value_type(ctx, arg_ids[j]));
    loom_print_did_write(ctx);
  }
  return loom_print_emit_cstr(ctx, ")", false);
}

iree_status_t loom_print_func_args(loom_print_context_t* ctx,
                                   const loom_op_t* op,
                                   const loom_op_vtable_t* vtable) {
  uint16_t arg_count = 0;
  const loom_value_id_t* arg_ids =
      loom_print_func_arg_ids(op, vtable, &arg_count);
  IREE_RETURN_IF_ERROR(loom_print_emit_cstr(ctx, "(", true));
  for (uint16_t j = 0; j < arg_count; ++j) {
    if (j > 0) {
      IREE_RETURN_IF_ERROR(loom_print_emit_cstr(ctx, ",", false));
    }
    bool args_as_operands =
        vtable->func_like && vtable->func_like->args_as_operands;
    if (args_as_operands) {
      IREE_RETURN_IF_ERROR(loom_print_value_name_with_field(
          ctx, arg_ids[j], loom_print_field_ref(LOOM_PRINT_FIELD_OPERAND, j)));
    } else {
      IREE_RETURN_IF_ERROR(loom_print_value_name(ctx, arg_ids[j]));
    }
    IREE_RETURN_IF_ERROR(loom_print_emit_cstr(ctx, ":", true));
    IREE_RETURN_IF_ERROR(loom_print_space_if_needed(ctx));
    IREE_RETURN_IF_ERROR(loom_print_value_type(ctx, arg_ids[j]));
    loom_print_did_write(ctx);
  }
  return loom_print_emit_cstr(ctx, ")", false);
}
