# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""Repository rule exposing the LLVM install used by clang-tidy plugins."""

load(
    "//build_tools/bazel:elf_dynamic_library_closure.bzl",
    "elf_loader_environment",
    "resolve_elf_dynamic_library_closure",
)

_STUB_BUILD = """\
# AUTO-GENERATED by llvm_repo.bzl - do not edit.

load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "host_dynamic_libraries",
    srcs = [],
)

filegroup(
    name = "clang_resource_headers",
    srcs = [],
)

filegroup(
    name = "clang_resource_overlay",
    srcs = ["clang_resource_overlay.yaml"],
)

filegroup(
    name = "clang-tidy",
    srcs = [],
)

filegroup(
    name = "clang++",
    srcs = [],
)

filegroup(
    name = "llvm-config",
    srcs = [],
)

cc_library(
    name = "llvm_headers",
    hdrs = [],
)
"""

_STUB_CONFIG = """\
# AUTO-GENERATED by llvm_repo.bzl - do not edit.

CLANG_TIDY_LLVM_AVAILABLE = False
CLANG_TIDY_LLVM_ERROR = "Set --repo_env=IREE_CLANG_TIDY_LLVM=auto or --repo_env=IREE_CLANG_TIDY_LLVM_CONFIG=/path/to/llvm-config to enable clang-tidy plugin builds."
CLANG_TIDY_LLVM_VERSION = ""
CLANG_TIDY_LLVM_HAS_RTTI = ""
CLANG_TIDY_CLANG_RESOURCE_DIR = ""
CLANG_TIDY_LLVM_COPTS = []
CLANG_TIDY_LLVM_TARGET_COMPATIBLE_WITH = ["@platforms//:incompatible"]
CLANG_TIDY_TOOL = ""
CLANG_TIDY_CLANGXX_TOOL = ""
CLANG_TIDY_LLVM_CONFIG_TOOL = ""
"""

_PREBUILT_TOOL_BZL = """\
\"\"\"Rule for exposing relocatable pre-built LLVM tools.\"\"\"

def _prebuilt_tool_impl(ctx):
    output = ctx.actions.declare_file(ctx.label.name)
    wrapper = \"\"\"#!/bin/sh
set -eu

runfiles_dir=
if [ -d \"$0.runfiles\" ]; then
  runfiles_dir=\"$0.runfiles\"
elif [ -n \"${RUNFILES_DIR:-}\" ] && [ -d \"$RUNFILES_DIR\" ]; then
  runfiles_dir=\"$RUNFILES_DIR\"
else
  case \"$0\" in
    *.runfiles/*)
      runfiles_dir=\"${0%%%%.runfiles/*}.runfiles\"
      ;;
  esac
fi
if [ -z \"$runfiles_dir\" ] || [ ! -d \"$runfiles_dir\" ]; then
  echo \"LLVM tool wrapper: unable to locate Bazel runfiles\" >&2
  exit 1
fi

tool_path=
for candidate in \"$runfiles_dir\"/*/bin/%s; do
  if [ ! -x \"$candidate\" ]; then
    continue
  fi
  if [ -n \"$tool_path\" ]; then
    echo \"LLVM tool wrapper: multiple runfiles match bin/%s\" >&2
    exit 1
  fi
  tool_path=\"$candidate\"
done
if [ -z \"$tool_path\" ]; then
  echo \"LLVM tool wrapper: missing runfile bin/%s\" >&2
  exit 1
fi

tool_root=$(dirname \"$(dirname \"$tool_path\")\")
dynamic_library_dir=\"$tool_root/host_dynamic_libraries\"
if [ -d \"$dynamic_library_dir\" ]; then
  export LD_LIBRARY_PATH=\"$dynamic_library_dir\"
fi
exec \"$tool_path\" \"$@\"
\"\"\" % (
        ctx.file.src.basename,
        ctx.file.src.basename,
        ctx.file.src.basename,
    )
    ctx.actions.write(
        output = output,
        content = wrapper,
        is_executable = True,
    )
    runfiles = ctx.runfiles(files = ctx.files.data + [ctx.file.src])
    return [DefaultInfo(
        executable = output,
        files = depset([output]),
        runfiles = runfiles,
    )]

prebuilt_tool = rule(
    implementation = _prebuilt_tool_impl,
    executable = True,
    attrs = {
        "src": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "The pre-built binary file.",
        ),
        "data": attr.label_list(
            allow_files = True,
            doc = "Additional files the tool needs at runtime.",
        ),
    },
    doc = "Wraps a pre-built LLVM tool with its exact host dynamic libraries.",
)
"""

_LOCAL_BUILD = """\
# AUTO-GENERATED by llvm_repo.bzl - do not edit.

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load(":prebuilt_tool.bzl", "prebuilt_tool")

package(default_visibility = ["//visibility:public"])

prebuilt_tool(
    name = "clang-tidy",
    src = "bin/clang-tidy",
    data = [":host_dynamic_libraries"],
)

prebuilt_tool(
    name = "clang++",
    src = "bin/clang++",
    data = [":host_dynamic_libraries"],
)

prebuilt_tool(
    name = "llvm-config",
    src = "bin/llvm-config",
    data = [":host_dynamic_libraries"],
)

filegroup(
    name = "host_dynamic_libraries",
    srcs = glob(["host_dynamic_libraries/**"]),
)

filegroup(
    name = "clang_resource_headers",
    srcs = glob(["clang-resource/**"]),
)

filegroup(
    name = "clang_resource_overlay",
    srcs = ["clang_resource_overlay.yaml"],
)

cc_library(
    name = "llvm_headers",
    hdrs = glob([
        "include/**/*.def",
        "include/**/*.h",
        "include/**/*.inc",
        "include/**/*.td",
    ]),
    includes = ["include"],
)
"""

def _join_path(left, right):
    if left.endswith("/"):
        return left + right
    return left + "/" + right

def _is_executable(repository_ctx, path):
    result = repository_ctx.execute(["test", "-x", path], quiet = True)
    return result.return_code == 0

def _executable_from_directory(repository_ctx, directory, names):
    for name in names:
        candidate = _join_path(directory, name)
        if _is_executable(repository_ctx, candidate):
            return candidate
    return ""

def _find_llvm_config(repository_ctx):
    configured = []
    for name in [
        "IREE_CLANG_TIDY_LLVM_CONFIG",
        "LLVM_CONFIG",
    ]:
        value = repository_ctx.getenv(name)
        if not value:
            continue
        if not _is_executable(repository_ctx, value):
            fail("{} is not executable: {}".format(name, value))
        configured.append((name, _canonical_path(repository_ctx, value, name)))
    for name in [
        "IREE_CLANG_TIDY_LLVM_ROOT",
        "IREE_LLVM_ROOT",
        "LLVM_ROOT",
    ]:
        root = repository_ctx.getenv(name)
        if not root:
            continue
        candidate = _executable_from_directory(
            repository_ctx,
            _join_path(root, "bin"),
            ["llvm-config", "llvm-config-22"],
        )
        if not candidate:
            fail("{} does not provide an LLVM config tool under bin/: {}".format(
                name,
                root,
            ))
        configured.append((name, _canonical_path(
            repository_ctx,
            candidate,
            name + " llvm-config",
        )))
    if configured:
        selected_path = configured[0][1]
        for name, path in configured[1:]:
            if path != selected_path:
                fail("Configured clang-tidy LLVM installations disagree: {} and {}={}".format(
                    configured[0][0] + "=" + selected_path,
                    name,
                    path,
                ))
        return selected_path

    for name in ["llvm-config", "llvm-config-22"]:
        llvm_config = repository_ctx.which(name)
        if llvm_config:
            return str(llvm_config)
    return ""

def _execute(repository_ctx, argv, description, loader_environment):
    result = repository_ctx.execute(
        argv,
        environment = loader_environment,
        quiet = True,
    )
    if result.return_code != 0:
        fail("Failed to {} with {}:\n{}".format(
            description,
            " ".join(argv),
            result.stderr,
        ))
    return result.stdout.strip()

def _required_tool(repository_ctx, bindir, names, description):
    candidate = _executable_from_directory(repository_ctx, bindir, names)
    if not candidate:
        fail("LLVM {} is not executable under {} (tried {})".format(
            description,
            bindir,
            ", ".join(names),
        ))
    return _canonical_path(repository_ctx, candidate, description)

def _filtered_copts(cxxflags):
    raw_flags = cxxflags.split(" ")
    filtered = []
    skip_next = False
    for flag in raw_flags:
        if not flag:
            continue
        if skip_next:
            skip_next = False
            continue
        if flag == "-I":
            skip_next = True
            continue
        if flag.startswith("-I"):
            continue
        filtered.append(flag)
    return filtered

def _starlark_string(value):
    return "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

def _starlark_list(values):
    if not values:
        return "[]"
    return "[\n    " + ",\n    ".join([_starlark_string(value) for value in values]) + ",\n]"

def _canonical_path(repository_ctx, path, description):
    path = repository_ctx.path(path)
    if not path.exists:
        fail("{} does not exist: {}".format(description, path))
    return str(path.realpath)

def _local_config(info):
    return """\
# AUTO-GENERATED by llvm_repo.bzl - do not edit.

CLANG_TIDY_LLVM_AVAILABLE = True
CLANG_TIDY_LLVM_ERROR = ""
CLANG_TIDY_LLVM_VERSION = {version}
CLANG_TIDY_LLVM_HAS_RTTI = {has_rtti}
CLANG_TIDY_CLANG_RESOURCE_DIR = "/__iree_clang_resource__"
CLANG_TIDY_LLVM_COPTS = {copts}
CLANG_TIDY_LLVM_TARGET_COMPATIBLE_WITH = []
CLANG_TIDY_TOOL = "@iree_clang_tidy_llvm//:clang-tidy"
CLANG_TIDY_CLANGXX_TOOL = "@iree_clang_tidy_llvm//:clang++"
CLANG_TIDY_LLVM_CONFIG_TOOL = "@iree_clang_tidy_llvm//:llvm-config"
""".format(
        version = _starlark_string(info["version"]),
        has_rtti = _starlark_string(info["has_rtti"]),
        copts = _starlark_list(info["copts"]),
    )

def _write_stub(repository_ctx):
    repository_ctx.file("BUILD.bazel", _STUB_BUILD)
    repository_ctx.file("config.bzl", _STUB_CONFIG)
    repository_ctx.file("clang_resource_overlay.yaml", "{}\n")

def _resource_overlay():
    return """\
{
  "version": 0,
  "use-external-names": false,
  "overlay-relative": true,
  "roots": [
    {
      "type": "directory-remap",
      "name": "/__iree_clang_resource__",
      "external-contents": "clang-resource"
    }
  ]
}
"""

def _write_local(repository_ctx, info):
    repository_ctx.file("prebuilt_tool.bzl", _PREBUILT_TOOL_BZL)
    repository_ctx.file("bin/.keep", "")
    repository_ctx.symlink(repository_ctx.path(info["clang_tidy"]), "bin/clang-tidy")
    repository_ctx.symlink(repository_ctx.path(info["clangxx"]), "bin/clang++")
    repository_ctx.symlink(repository_ctx.path(info["llvm_config"]), "bin/llvm-config")
    repository_ctx.symlink(repository_ctx.path(info["include_dir"]), "include")
    repository_ctx.file("host_dynamic_libraries/.keep", "")
    for name in sorted(info["host_dynamic_libraries"].keys()):
        repository_ctx.symlink(
            repository_ctx.path(info["host_dynamic_libraries"][name]),
            "host_dynamic_libraries/" + name,
        )
    repository_ctx.file("clang-resource/.keep", "")
    repository_ctx.symlink(
        repository_ctx.path(info["resource_include_dir"]),
        "clang-resource/include",
    )
    repository_ctx.file("BUILD.bazel", _LOCAL_BUILD)
    repository_ctx.file("config.bzl", _local_config(info))
    repository_ctx.file("clang_resource_overlay.yaml", _resource_overlay())

def _clang_tidy_llvm_repo_impl(repository_ctx):
    mode = repository_ctx.getenv("IREE_CLANG_TIDY_LLVM") or "none"
    if mode == "none" and repository_ctx.getenv("IREE_CLANG_TIDY_LLVM_CONFIG"):
        mode = "auto"
    if mode not in ["none", "auto"]:
        fail("Unknown IREE_CLANG_TIDY_LLVM '{}'. Available: none, auto.".format(mode))

    if mode == "none":
        _write_stub(repository_ctx)
        return

    llvm_config = _find_llvm_config(repository_ctx)
    if not llvm_config:
        fail("IREE_CLANG_TIDY_LLVM=auto could not find llvm-config. Set IREE_CLANG_TIDY_LLVM_CONFIG or IREE_CLANG_TIDY_LLVM_ROOT.")

    llvm_config = _canonical_path(
        repository_ctx,
        llvm_config,
        "llvm-config",
    )
    loader_environment = elf_loader_environment()

    version = _execute(
        repository_ctx,
        [llvm_config, "--version"],
        "query LLVM version",
        loader_environment,
    )
    version_suffix = version.split(".")[0]
    info = {
        "bindir": _canonical_path(
            repository_ctx,
            _execute(repository_ctx, [llvm_config, "--bindir"], "query LLVM binary directory", loader_environment),
            "LLVM binary directory",
        ),
        "copts": _filtered_copts(_execute(repository_ctx, [llvm_config, "--cxxflags"], "query LLVM C++ flags", loader_environment)),
        "has_rtti": _execute(repository_ctx, [llvm_config, "--has-rtti"], "query LLVM RTTI mode", loader_environment),
        "include_dir": _canonical_path(
            repository_ctx,
            _execute(repository_ctx, [llvm_config, "--includedir"], "query LLVM include directory", loader_environment),
            "LLVM include directory",
        ),
        "llvm_config": llvm_config,
        "version": version,
    }
    info["clang_tidy"] = _required_tool(
        repository_ctx,
        info["bindir"],
        ["clang-tidy", "clang-tidy-" + version_suffix],
        "clang-tidy",
    )
    info["clangxx"] = _required_tool(
        repository_ctx,
        info["bindir"],
        ["clang++", "clang++-" + version_suffix],
        "clang++",
    )
    info["resource_dir"] = _canonical_path(
        repository_ctx,
        _execute(
            repository_ctx,
            [info["clangxx"], "-print-resource-dir"],
            "query Clang resource directory",
            loader_environment,
        ),
        "Clang resource directory",
    )
    info["resource_include_dir"] = _canonical_path(
        repository_ctx,
        _join_path(info["resource_dir"], "include"),
        "Clang resource include directory",
    )
    info["host_dynamic_libraries"] = resolve_elf_dynamic_library_closure(
        repository_ctx,
        {
            "clang++": info["clangxx"],
            "clang-tidy": info["clang_tidy"],
            "llvm-config": info["llvm_config"],
        },
    )
    _write_local(repository_ctx, info)

clang_tidy_llvm_repo = repository_rule(
    implementation = _clang_tidy_llvm_repo_impl,
    environ = [
        "IREE_CLANG_TIDY_LLVM",
        "IREE_CLANG_TIDY_LLVM_CONFIG",
        "IREE_CLANG_TIDY_LLVM_ROOT",
        "IREE_LLVM_ROOT",
        "LLVM_CONFIG",
        "LLVM_ROOT",
        "PATH",
    ],
    doc = "Exposes an optional LLVM install for IREE clang-tidy plugin builds.",
)
