# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""Repository rule exposing the LLVM install used by clang-tidy plugins."""

_STUB_BUILD = """\
# AUTO-GENERATED by llvm_repo.bzl - do not edit.

load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "llvm_identity",
    srcs = ["llvm_identity.txt"],
)

filegroup(
    name = "llvm_runtime",
    srcs = [],
)

filegroup(
    name = "clang-tidy",
    srcs = [],
)

filegroup(
    name = "clang++",
    srcs = [],
)

filegroup(
    name = "llvm-config",
    srcs = [],
)

cc_library(
    name = "llvm_headers",
    hdrs = [],
)
"""

_STUB_CONFIG = """\
# AUTO-GENERATED by llvm_repo.bzl - do not edit.

CLANG_TIDY_LLVM_AVAILABLE = False
CLANG_TIDY_LLVM_ERROR = "Set --repo_env=IREE_CLANG_TIDY_LLVM=auto or --repo_env=IREE_CLANG_TIDY_LLVM_CONFIG=/path/to/llvm-config to enable clang-tidy plugin builds."
CLANG_TIDY_LLVM_VERSION = ""
CLANG_TIDY_LLVM_HAS_RTTI = ""
CLANG_TIDY_LLVM_INCLUDE_DIR = ""
CLANG_TIDY_LLVM_LIB_DIR = ""
CLANG_TIDY_LLVM_CMAKE_DIR = ""
CLANG_TIDY_LLVM_BINDIR = ""
CLANG_TIDY_LLVM_COPTS = []
CLANG_TIDY_LLVM_TARGET_COMPATIBLE_WITH = ["@platforms//:incompatible"]
CLANG_TIDY_TOOL = ""
CLANG_TIDY_CLANGXX_TOOL = ""
CLANG_TIDY_LLVM_CONFIG_TOOL = ""
"""

_PREBUILT_TOOL_BZL = """\
\"\"\"Rule for exposing pre-built binaries as executable Bazel targets.\"\"\"

def _prebuilt_tool_impl(ctx):
    out = ctx.actions.declare_file(ctx.label.name)
    ctx.actions.symlink(
        output = out,
        target_file = ctx.file.src,
        is_executable = True,
    )
    runfiles = ctx.runfiles(files = ctx.files.data + [ctx.file.src])
    return [DefaultInfo(
        executable = out,
        files = depset([out]),
        runfiles = runfiles,
    )]

prebuilt_tool = rule(
    implementation = _prebuilt_tool_impl,
    executable = True,
    attrs = {
        "src": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "The pre-built binary file.",
        ),
        "data": attr.label_list(
            allow_files = True,
            doc = "Additional files the tool needs at runtime.",
        ),
    },
    doc = "Wraps a pre-built binary as an executable Bazel target.",
)
"""

_LOCAL_BUILD = """\
# AUTO-GENERATED by llvm_repo.bzl - do not edit.

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load(":prebuilt_tool.bzl", "prebuilt_tool")

package(default_visibility = ["//visibility:public"])

prebuilt_tool(
    name = "clang-tidy",
    src = "bin/clang-tidy",
    data = [":llvm_runtime"],
)

prebuilt_tool(
    name = "clang++",
    src = "bin/clang++",
    data = [":llvm_runtime"],
)

prebuilt_tool(
    name = "llvm-config",
    src = "bin/llvm-config",
    data = [":llvm_runtime"],
)

filegroup(
    name = "llvm_identity",
    srcs = [
        "config.bzl",
        "llvm_identity.txt",
    ],
)

filegroup(
    name = "llvm_runtime",
    srcs = glob(["lib/**"]),
)

cc_library(
    name = "llvm_headers",
    hdrs = glob([
        "include/**/*.def",
        "include/**/*.h",
        "include/**/*.inc",
        "include/**/*.td",
    ]),
    includes = ["include"],
)
"""

def _join_path(left, right):
    if left.endswith("/"):
        return left + right
    return left + "/" + right

def _is_executable(repository_ctx, path):
    result = repository_ctx.execute(["test", "-x", path], quiet = True)
    return result.return_code == 0

def _tool_from_env(repository_ctx, names):
    for name in names:
        value = repository_ctx.getenv(name)
        if value and _is_executable(repository_ctx, value):
            return str(repository_ctx.path(value))
    return ""

def _tool_from_root(repository_ctx, root_names, tool_names):
    for root_name in root_names:
        root = repository_ctx.getenv(root_name)
        if not root:
            continue
        for tool_name in tool_names:
            candidate = _join_path(_join_path(root, "bin"), tool_name)
            if _is_executable(repository_ctx, candidate):
                return str(repository_ctx.path(candidate))
    return ""

def _tool_from_path(repository_ctx, tool_names):
    for tool_name in tool_names:
        path = repository_ctx.which(tool_name)
        if path:
            return str(path)
    return ""

def _find_llvm_config(repository_ctx):
    explicit = _tool_from_env(repository_ctx, [
        "IREE_CLANG_TIDY_LLVM_CONFIG",
        "LLVM_CONFIG",
    ])
    if explicit:
        return explicit

    rooted = _tool_from_root(repository_ctx, [
        "IREE_CLANG_TIDY_LLVM_ROOT",
        "IREE_LLVM_ROOT",
        "LLVM_ROOT",
    ], [
        "llvm-config",
        "llvm-config-22",
    ])
    if rooted:
        return rooted

    return _tool_from_path(repository_ctx, [
        "llvm-config",
        "llvm-config-22",
    ])

def _execute(repository_ctx, argv, description):
    result = repository_ctx.execute(argv, quiet = True)
    if result.return_code != 0:
        fail("Failed to {} with {}:\n{}".format(
            description,
            " ".join(argv),
            result.stderr,
        ))
    return result.stdout.strip()

def _find_tool(repository_ctx, bindir, names, explicit_env_vars, description):
    explicit = _tool_from_env(repository_ctx, explicit_env_vars)
    if explicit:
        return explicit
    for name in names:
        candidate = _join_path(bindir, name)
        if _is_executable(repository_ctx, candidate):
            return str(repository_ctx.path(candidate))
    path_tool = _tool_from_path(repository_ctx, names)
    if path_tool:
        return path_tool
    fail("Could not find {}. Tried [{}] and PATH names [{}].".format(
        description,
        ", ".join([_join_path(bindir, name) for name in names] + explicit_env_vars),
        ", ".join(names),
    ))

def _filtered_copts(cxxflags):
    raw_flags = cxxflags.split(" ")
    filtered = []
    skip_next = False
    for flag in raw_flags:
        if not flag:
            continue
        if skip_next:
            skip_next = False
            continue
        if flag == "-I":
            skip_next = True
            continue
        if flag.startswith("-I"):
            continue
        filtered.append(flag)
    return filtered

def _starlark_string(value):
    return "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

def _starlark_list(values):
    if not values:
        return "[]"
    return "[\n    " + ",\n    ".join([_starlark_string(value) for value in values]) + ",\n]"

def _local_config(info):
    return """\
# AUTO-GENERATED by llvm_repo.bzl - do not edit.

CLANG_TIDY_LLVM_AVAILABLE = True
CLANG_TIDY_LLVM_ERROR = ""
CLANG_TIDY_LLVM_VERSION = {version}
CLANG_TIDY_LLVM_HAS_RTTI = {has_rtti}
CLANG_TIDY_LLVM_INCLUDE_DIR = {include_dir}
CLANG_TIDY_LLVM_LIB_DIR = {lib_dir}
CLANG_TIDY_LLVM_CMAKE_DIR = {cmake_dir}
CLANG_TIDY_LLVM_BINDIR = {bindir}
CLANG_TIDY_LLVM_COPTS = {copts}
CLANG_TIDY_LLVM_TARGET_COMPATIBLE_WITH = []
CLANG_TIDY_TOOL = "@iree_clang_tidy_llvm//:clang-tidy"
CLANG_TIDY_CLANGXX_TOOL = "@iree_clang_tidy_llvm//:clang++"
CLANG_TIDY_LLVM_CONFIG_TOOL = "@iree_clang_tidy_llvm//:llvm-config"
""".format(
        version = _starlark_string(info["version"]),
        has_rtti = _starlark_string(info["has_rtti"]),
        include_dir = _starlark_string(info["include_dir"]),
        lib_dir = _starlark_string(info["lib_dir"]),
        cmake_dir = _starlark_string(info["cmake_dir"]),
        bindir = _starlark_string(info["bindir"]),
        copts = _starlark_list(info["copts"]),
    )

def _identity_text(info):
    lines = [
        "version={}".format(info["version"]),
        "has_rtti={}".format(info["has_rtti"]),
        "include_dir={}".format(info["include_dir"]),
        "lib_dir={}".format(info["lib_dir"]),
        "cmake_dir={}".format(info["cmake_dir"]),
        "bindir={}".format(info["bindir"]),
        "clang_tidy={}".format(info["clang_tidy"]),
        "clangxx={}".format(info["clangxx"]),
        "llvm_config={}".format(info["llvm_config"]),
        "copts={}".format(" ".join(info["copts"])),
    ]
    return "\n".join(lines) + "\n"

def _write_stub(repository_ctx):
    repository_ctx.file("BUILD.bazel", _STUB_BUILD)
    repository_ctx.file("config.bzl", _STUB_CONFIG)
    repository_ctx.file("llvm_identity.txt", "available=false\n")

def _write_local(repository_ctx, info):
    repository_ctx.file("prebuilt_tool.bzl", _PREBUILT_TOOL_BZL)
    repository_ctx.file("bin/.keep", "")
    repository_ctx.symlink(repository_ctx.path(info["clang_tidy"]), "bin/clang-tidy")
    repository_ctx.symlink(repository_ctx.path(info["clangxx"]), "bin/clang++")
    repository_ctx.symlink(repository_ctx.path(info["llvm_config"]), "bin/llvm-config")
    repository_ctx.symlink(repository_ctx.path(info["include_dir"]), "include")
    repository_ctx.symlink(repository_ctx.path(info["lib_dir"]), "lib")
    repository_ctx.file("BUILD.bazel", _LOCAL_BUILD)
    repository_ctx.file("config.bzl", _local_config(info))
    repository_ctx.file("llvm_identity.txt", _identity_text(info))

def _clang_tidy_llvm_repo_impl(repository_ctx):
    mode = repository_ctx.getenv("IREE_CLANG_TIDY_LLVM") or "none"
    if mode == "none" and repository_ctx.getenv("IREE_CLANG_TIDY_LLVM_CONFIG"):
        mode = "auto"
    if mode not in ["none", "auto"]:
        fail("Unknown IREE_CLANG_TIDY_LLVM '{}'. Available: none, auto.".format(mode))

    if mode == "none":
        _write_stub(repository_ctx)
        return

    llvm_config = _find_llvm_config(repository_ctx)
    if not llvm_config:
        fail("IREE_CLANG_TIDY_LLVM=auto could not find llvm-config. Set IREE_CLANG_TIDY_LLVM_CONFIG or IREE_CLANG_TIDY_LLVM_ROOT.")

    info = {
        "bindir": _execute(repository_ctx, [llvm_config, "--bindir"], "query LLVM binary directory"),
        "cmake_dir": _execute(repository_ctx, [llvm_config, "--cmakedir"], "query LLVM CMake directory"),
        "copts": _filtered_copts(_execute(repository_ctx, [llvm_config, "--cxxflags"], "query LLVM C++ flags")),
        "has_rtti": _execute(repository_ctx, [llvm_config, "--has-rtti"], "query LLVM RTTI mode"),
        "include_dir": _execute(repository_ctx, [llvm_config, "--includedir"], "query LLVM include directory"),
        "lib_dir": _execute(repository_ctx, [llvm_config, "--libdir"], "query LLVM library directory"),
        "llvm_config": llvm_config,
        "version": _execute(repository_ctx, [llvm_config, "--version"], "query LLVM version"),
    }
    info["clang_tidy"] = _find_tool(
        repository_ctx,
        info["bindir"],
        ["clang-tidy", "clang-tidy-22"],
        ["IREE_CLANG_TIDY_BINARY", "CLANG_TIDY"],
        "clang-tidy",
    )
    info["clangxx"] = _find_tool(
        repository_ctx,
        info["bindir"],
        ["clang++", "clang++-22"],
        ["IREE_CLANG_TIDY_CLANGXX_BINARY", "IREE_CLANGXX_BINARY", "CLANGXX"],
        "clang++",
    )
    _write_local(repository_ctx, info)

clang_tidy_llvm_repo = repository_rule(
    implementation = _clang_tidy_llvm_repo_impl,
    environ = [
        "CLANGXX",
        "CLANG_TIDY",
        "IREE_CLANG_TIDY_BINARY",
        "IREE_CLANG_TIDY_CLANGXX_BINARY",
        "IREE_CLANG_TIDY_LLVM",
        "IREE_CLANG_TIDY_LLVM_CONFIG",
        "IREE_CLANG_TIDY_LLVM_ROOT",
        "IREE_CLANGXX_BINARY",
        "IREE_LLVM_ROOT",
        "LLVM_CONFIG",
        "LLVM_ROOT",
    ],
    doc = "Exposes an optional LLVM install for IREE clang-tidy plugin builds.",
)
