# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# bazel-to-cmake: skip

load(":cc_benchmark_rules_test.bzl", "cc_benchmark_rules_test_suite")
load(":cc_fuzz_rules_test.bzl", "cc_fuzz_rules_test_suite")
load(":cc_rules_test.bzl", "cc_rules_test_suite")

package(default_visibility = ["//visibility:public"])

cc_benchmark_rules_test_suite(name = "cc_benchmark_tests")

cc_fuzz_rules_test_suite(name = "cc_fuzz_tests")

cc_rules_test_suite(name = "cc_tests")

test_suite(
    name = "hal_cts_tests",
    tests = ["//runtime/build_tools/bazel/test/hal_cts:hal_cts_tests"],
)
