# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//build_tools/embed_data:build_defs.bzl", "iree_c_embed_data")
load("//runtime/build_tools/bazel:cc_test.bzl", "iree_runtime_cc_test")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

iree_c_embed_data(
    name = "testdata_vmvx",
    testonly = True,
    srcs = [
        "testdata/command_buffer_dispatch_test.bin",
        "testdata/dispatch_wide_bindings_test.bin",
    ],
    c_file_output = "testdata_vmvx.c",
    flatten = True,
    h_file_output = "testdata_vmvx.h",
    identifier = "iree_remote_testdata_vmvx",
)

iree_runtime_cc_test(
    name = "remote_session_test",
    srcs = ["remote_session_test.cc"],
    deps = [
        ":testdata_vmvx",
        "//runtime/src/iree/async",
        "//runtime/src/iree/async:platform",
        "//runtime/src/iree/async/util:proactor_pool",
        "//runtime/src/iree/async/util:proactor_thread",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/threading",
        "//runtime/src/iree/hal",
        "//runtime/src/iree/hal/drivers/local_task/registration",
        "//runtime/src/iree/hal/memory:slab_provider",
        "//runtime/src/iree/hal/remote/client",
        "//runtime/src/iree/hal/remote/client:command_buffer_test_util",
        "//runtime/src/iree/hal/remote/protocol:commands",
        "//runtime/src/iree/hal/remote/protocol:common",
        "//runtime/src/iree/hal/remote/server",
        "//runtime/src/iree/hal/remote/util:recv_pool",
        "//runtime/src/iree/hal/testing:mock_device",
        "//runtime/src/iree/io:file_handle",
        "//runtime/src/iree/net:session",
        "//runtime/src/iree/net/carrier/loopback:factory",
        "//runtime/src/iree/net/carrier/shm:factory",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
        "//runtime/src/iree/testing:temp_file",
    ],
)
