# Copyright 2026 The HRX Authors
# SPDX-License-Identifier: Apache-2.0

# Helpers for installing a relocatable CTest tree. The build-tree tests remain
# registered through the normal IREE-style macros; this module records enough
# metadata from those same macro calls to emit an installed CTest tree under
# share/hrx-system/tests.

include(GNUInstallDirs)

set(_HRX_INSTALLED_TESTS_BUILD_DIR "${CMAKE_BINARY_DIR}/hrx-installed-tests")
set(_HRX_INSTALLED_TESTS_ROOT_FILE "${_HRX_INSTALLED_TESTS_BUILD_DIR}/CTestTestfile.cmake")
set(_HRX_INSTALLED_TESTS_CTEST_DIR "${_HRX_INSTALLED_TESTS_BUILD_DIR}/ctest")
set(_HRX_INSTALLED_TESTS_CTEST_FILE "${_HRX_INSTALLED_TESTS_CTEST_DIR}/CTestTestfile.cmake")
set(_HRX_INSTALLED_TESTS_CUSTOM_FILE "${_HRX_INSTALLED_TESTS_BUILD_DIR}/CTestCustom.cmake")

file(MAKE_DIRECTORY "${_HRX_INSTALLED_TESTS_CTEST_DIR}")
file(WRITE "${_HRX_INSTALLED_TESTS_ROOT_FILE}"
  "# Generated by hrx_installed_tests.cmake.\n"
  "subdirs(\"ctest\")\n")
file(WRITE "${_HRX_INSTALLED_TESTS_CTEST_FILE}"
  "# Generated by hrx_installed_tests.cmake.\n"
  "get_filename_component(_HRX_INSTALLED_TEST_ROOT \"\${CMAKE_CURRENT_LIST_DIR}/..\" ABSOLUTE)\n"
  "if(DEFINED ENV{HRX_TEST_TMPDIR} AND NOT \"\$ENV{HRX_TEST_TMPDIR}\" STREQUAL \"\")\n"
  "  file(TO_CMAKE_PATH \"\$ENV{HRX_TEST_TMPDIR}\" _HRX_INSTALLED_TEST_TMP_ROOT)\n"
  "else()\n"
  "  set(_HRX_INSTALLED_TEST_TMP_ROOT \"\${_HRX_INSTALLED_TEST_ROOT}/tmp\")\n"
  "endif()\n"
  "get_filename_component(_HRX_INSTALLED_TEST_TMP_ROOT \"\${_HRX_INSTALLED_TEST_TMP_ROOT}\" ABSOLUTE)\n"
  "set(_HRX_INSTALLED_TEST_DATA_ROOT \"\${_HRX_INSTALLED_TEST_ROOT}/testdata\")\n"
  "get_filename_component(_HRX_INSTALLED_TEST_DATA_ROOT \"\${_HRX_INSTALLED_TEST_DATA_ROOT}\" ABSOLUTE)\n"
  "set(_HRX_INSTALLED_TEST_LIB_ROOT \"\${_HRX_INSTALLED_TEST_ROOT}/lib\")\n"
  "get_filename_component(_HRX_INSTALLED_TEST_LIB_ROOT \"\${_HRX_INSTALLED_TEST_LIB_ROOT}\" ABSOLUTE)\n"
  "set(_HRX_INSTALLED_TEST_BIN_ROOT \"\${_HRX_INSTALLED_TEST_ROOT}/bin\")\n"
  "get_filename_component(_HRX_INSTALLED_TEST_BIN_ROOT \"\${_HRX_INSTALLED_TEST_BIN_ROOT}\" ABSOLUTE)\n")

set_property(GLOBAL PROPERTY HRX_INSTALLED_TEST_TARGETS "")
set_property(GLOBAL PROPERTY HRX_INSTALLED_TEST_DEFERRED_TARGETS "")
set_property(GLOBAL PROPERTY HRX_INSTALLED_TEST_DEFERRED_TARGET_PATHS "")
set_property(GLOBAL PROPERTY HRX_INSTALLED_TEST_FILES "")
set_property(GLOBAL PROPERTY HRX_INSTALLED_TEST_TMPDIRS "")

set(IREE_TEST_REGISTRATION_FUNCTION hrx_register_installed_test)
set(IREE_PYTHON_TEST_REGISTRATION_FUNCTION hrx_register_installed_python_test)
set(IREE_BENCHMARK_INSTALL_COMPONENT "${HRX_INSTALL_TESTS_COMPONENT}")

function(hrx_installed_tests_is_enabled OUT_VAR)
  if(HRX_INSTALL_TESTS AND IREE_BUILD_TESTS)
    set(${OUT_VAR} ON PARENT_SCOPE)
  else()
    set(${OUT_VAR} OFF PARENT_SCOPE)
  endif()
endfunction()

function(hrx_installed_tests_quote OUT_VAR VALUE)
  string(REPLACE "\\" "\\\\" _VALUE "${VALUE}")
  string(REPLACE "\"" "\\\"" _VALUE "${_VALUE}")
  set(${OUT_VAR} "\"${_VALUE}\"" PARENT_SCOPE)
endfunction()

function(hrx_installed_tests_append_quoted OUT_VAR)
  set(_RESULT "${${OUT_VAR}}")
  foreach(_VALUE IN LISTS ARGN)
    hrx_installed_tests_quote(_QUOTED "${_VALUE}")
    string(APPEND _RESULT " ${_QUOTED}")
  endforeach()
  set(${OUT_VAR} "${_RESULT}" PARENT_SCOPE)
endfunction()

function(hrx_installed_tests_append_property OUT_VAR NAME VALUE)
  set(_RESULT "${${OUT_VAR}}")
  hrx_installed_tests_quote(_QUOTED_NAME "${NAME}")
  hrx_installed_tests_quote(_QUOTED_VALUE "${VALUE}")
  string(APPEND _RESULT " ${_QUOTED_NAME} ${_QUOTED_VALUE}")
  set(${OUT_VAR} "${_RESULT}" PARENT_SCOPE)
endfunction()

function(hrx_installed_tests_target_filename OUT_VAR TARGET_NAME)
  set(_TARGET "${TARGET_NAME}")
  get_target_property(_ALIASED_TARGET "${_TARGET}" ALIASED_TARGET)
  if(_ALIASED_TARGET)
    set(_TARGET "${_ALIASED_TARGET}")
  endif()

  get_target_property(_TYPE "${_TARGET}" TYPE)
  get_target_property(_OUTPUT_NAME "${_TARGET}" OUTPUT_NAME)
  if(NOT _OUTPUT_NAME)
    set(_OUTPUT_NAME "${_TARGET}")
  endif()

  if(_TYPE STREQUAL "EXECUTABLE")
    set(_PREFIX "")
    set(_SUFFIX "${CMAKE_EXECUTABLE_SUFFIX}")
  elseif(_TYPE STREQUAL "SHARED_LIBRARY" OR _TYPE STREQUAL "MODULE_LIBRARY")
    get_target_property(_PREFIX "${_TARGET}" PREFIX)
    if(NOT _PREFIX)
      set(_PREFIX "${CMAKE_SHARED_LIBRARY_PREFIX}")
    endif()
    get_target_property(_SUFFIX "${_TARGET}" SUFFIX)
    if(NOT _SUFFIX)
      set(_SUFFIX "${CMAKE_SHARED_LIBRARY_SUFFIX}")
    endif()
  else()
    message(FATAL_ERROR
      "Target '${TARGET_NAME}' has type '${_TYPE}', which cannot be used as an installed test artifact")
  endif()

  set(${OUT_VAR} "${_PREFIX}${_OUTPUT_NAME}${_SUFFIX}" PARENT_SCOPE)
endfunction()

function(hrx_installed_tests_deferred_target_filename OUT_VAR TARGET_NAME)
  if("${TARGET_NAME}" MATCHES "::([^:]+)$")
    set(_FILENAME "${CMAKE_MATCH_1}${CMAKE_EXECUTABLE_SUFFIX}")
  else()
    set(_FILENAME "${TARGET_NAME}${CMAKE_EXECUTABLE_SUFFIX}")
  endif()
  set(${OUT_VAR} "${_FILENAME}" PARENT_SCOPE)
endfunction()

function(hrx_installed_tests_install_target TARGET_NAME OUT_VAR)
  hrx_installed_tests_is_enabled(_ENABLED)
  if(NOT _ENABLED)
    return()
  endif()

  if(NOT TARGET "${TARGET_NAME}")
    string(MAKE_C_IDENTIFIER "${TARGET_NAME}" _SAFE_TARGET)
    hrx_installed_tests_deferred_target_filename(_FILENAME "${TARGET_NAME}")
    set(_INSTALLED_PATH "\${CMAKE_CURRENT_LIST_DIR}/../bin/${_SAFE_TARGET}/${_FILENAME}")
    set_property(GLOBAL APPEND PROPERTY HRX_INSTALLED_TEST_DEFERRED_TARGETS "${TARGET_NAME}")
    set_property(GLOBAL APPEND PROPERTY HRX_INSTALLED_TEST_DEFERRED_TARGET_PATHS
      "${TARGET_NAME}|${_INSTALLED_PATH}")
    set(${OUT_VAR} "${_INSTALLED_PATH}" PARENT_SCOPE)
    return()
  endif()

  set(_TARGET "${TARGET_NAME}")
  get_target_property(_ALIASED_TARGET "${_TARGET}" ALIASED_TARGET)
  if(_ALIASED_TARGET)
    set(_TARGET "${_ALIASED_TARGET}")
  endif()

  get_target_property(_TYPE "${_TARGET}" TYPE)
  hrx_installed_tests_target_filename(_FILENAME "${_TARGET}")

  if(_TYPE STREQUAL "EXECUTABLE")
    string(MAKE_C_IDENTIFIER "${TARGET_NAME}" _SAFE_TARGET)
    set(_DESTINATION "${HRX_INSTALL_TESTS_DIR}/bin/${_SAFE_TARGET}")
    set(_INSTALLED_PATH "\${CMAKE_CURRENT_LIST_DIR}/../bin/${_SAFE_TARGET}/${_FILENAME}")
    set(_INSTALL_KIND "RUNTIME")
  elseif(_TYPE STREQUAL "SHARED_LIBRARY" OR _TYPE STREQUAL "MODULE_LIBRARY")
    set(_DESTINATION "${HRX_INSTALL_TESTS_DIR}/lib")
    set(_INSTALLED_PATH "\${CMAKE_CURRENT_LIST_DIR}/../lib/${_FILENAME}")
    set(_INSTALL_KIND "LIBRARY")
  endif()

  get_property(_INSTALLED_TARGETS GLOBAL PROPERTY HRX_INSTALLED_TEST_TARGETS)
  if(NOT "${_TARGET}" IN_LIST _INSTALLED_TARGETS)
    if(_TYPE STREQUAL "EXECUTABLE")
      install(TARGETS "${_TARGET}"
        RUNTIME DESTINATION "${_DESTINATION}" COMPONENT "${HRX_INSTALL_TESTS_COMPONENT}"
        BUNDLE DESTINATION "${_DESTINATION}" COMPONENT "${HRX_INSTALL_TESTS_COMPONENT}")
    else()
      install(TARGETS "${_TARGET}"
        LIBRARY DESTINATION "${_DESTINATION}" COMPONENT "${HRX_INSTALL_TESTS_COMPONENT}"
        RUNTIME DESTINATION "${_DESTINATION}" COMPONENT "${HRX_INSTALL_TESTS_COMPONENT}"
        BUNDLE DESTINATION "${_DESTINATION}" COMPONENT "${HRX_INSTALL_TESTS_COMPONENT}")
    endif()
    set_property(GLOBAL APPEND PROPERTY HRX_INSTALLED_TEST_TARGETS "${_TARGET}")
  endif()

  set(${OUT_VAR} "${_INSTALLED_PATH}" PARENT_SCOPE)
endfunction()

function(hrx_installed_tests_install_source_file SOURCE_PATH DEST_REL OUT_VAR)
  hrx_installed_tests_is_enabled(_ENABLED)
  if(NOT _ENABLED)
    return()
  endif()

  set(_KEY "${SOURCE_PATH}|${DEST_REL}")
  get_property(_INSTALLED_FILES GLOBAL PROPERTY HRX_INSTALLED_TEST_FILES)
  if(NOT "${_KEY}" IN_LIST _INSTALLED_FILES)
    get_filename_component(_DEST_DIR "${DEST_REL}" DIRECTORY)
    install(FILES "${SOURCE_PATH}"
      DESTINATION "${HRX_INSTALL_TESTS_DIR}/testdata/${_DEST_DIR}"
      COMPONENT "${HRX_INSTALL_TESTS_COMPONENT}")
    set_property(GLOBAL APPEND PROPERTY HRX_INSTALLED_TEST_FILES "${_KEY}")
  endif()

  set(${OUT_VAR} "\${CMAKE_CURRENT_LIST_DIR}/../testdata/${DEST_REL}" PARENT_SCOPE)
endfunction()

function(hrx_installed_tests_install_source_tree SOURCE_DIR DEST_REL OUT_VAR)
  hrx_installed_tests_is_enabled(_ENABLED)
  if(NOT _ENABLED)
    return()
  endif()

  set(_KEY "${SOURCE_DIR}|${DEST_REL}/")
  get_property(_INSTALLED_FILES GLOBAL PROPERTY HRX_INSTALLED_TEST_FILES)
  if(NOT "${_KEY}" IN_LIST _INSTALLED_FILES)
    install(DIRECTORY "${SOURCE_DIR}/"
      DESTINATION "${HRX_INSTALL_TESTS_DIR}/testdata/${DEST_REL}"
      COMPONENT "${HRX_INSTALL_TESTS_COMPONENT}")
    set_property(GLOBAL APPEND PROPERTY HRX_INSTALLED_TEST_FILES "${_KEY}")
  endif()

  set(${OUT_VAR} "\${CMAKE_CURRENT_LIST_DIR}/../testdata/${DEST_REL}" PARENT_SCOPE)
endfunction()

function(hrx_installed_tests_project_relative_path SOURCE_PATH OUT_VAR)
  get_filename_component(_ABS_SOURCE "${SOURCE_PATH}" ABSOLUTE)
  set(_PROJECT_SOURCE_DIR "${PROJECT_SOURCE_DIR}")
  cmake_path(IS_PREFIX _PROJECT_SOURCE_DIR "${_ABS_SOURCE}" NORMALIZE _IN_PROJECT)
  if(_IN_PROJECT)
    cmake_path(RELATIVE_PATH _ABS_SOURCE
      BASE_DIRECTORY "${PROJECT_SOURCE_DIR}"
      OUTPUT_VARIABLE _REL_PATH)
  else()
    iree_package_path(_PACKAGE_PATH)
    get_filename_component(_SOURCE_NAME "${_ABS_SOURCE}" NAME)
    set(_REL_PATH "${_PACKAGE_PATH}/${_SOURCE_NAME}")
  endif()
  set(${OUT_VAR} "${_REL_PATH}" PARENT_SCOPE)
endfunction()

function(hrx_installed_tests_source_relative_path SOURCE_PATH OUT_VAR)
  get_filename_component(_ABS_SOURCE "${SOURCE_PATH}" ABSOLUTE)
  set(_PROJECT_SOURCE_DIR "${PROJECT_SOURCE_DIR}")
  set(_BINARY_DIR "${CMAKE_BINARY_DIR}")
  cmake_path(IS_PREFIX _PROJECT_SOURCE_DIR "${_ABS_SOURCE}" NORMALIZE _IN_PROJECT)
  if(_IN_PROJECT)
    cmake_path(RELATIVE_PATH _ABS_SOURCE
      BASE_DIRECTORY "${PROJECT_SOURCE_DIR}"
      OUTPUT_VARIABLE _REL_PATH)
  else()
    cmake_path(IS_PREFIX _BINARY_DIR "${_ABS_SOURCE}" NORMALIZE _IN_BINARY_TREE)
    if(_IN_BINARY_TREE)
      cmake_path(RELATIVE_PATH _ABS_SOURCE
        BASE_DIRECTORY "${CMAKE_BINARY_DIR}"
        OUTPUT_VARIABLE _REL_PATH)
    else()
      iree_package_path(_PACKAGE_PATH)
      get_filename_component(_SOURCE_NAME "${_ABS_SOURCE}" NAME)
      set(_REL_PATH "${_PACKAGE_PATH}/${_SOURCE_NAME}")
    endif()
  endif()
  set(${OUT_VAR} "${_REL_PATH}" PARENT_SCOPE)
endfunction()

function(hrx_installed_tests_python_package_relative_path PACKAGE_DIR OUT_VAR)
  get_filename_component(_ABS_PACKAGE_DIR "${PACKAGE_DIR}" ABSOLUTE)
  set(_PROJECT_SOURCE_DIR "${PROJECT_SOURCE_DIR}")
  set(_BINARY_DIR "${CMAKE_BINARY_DIR}")
  cmake_path(IS_PREFIX _BINARY_DIR "${_ABS_PACKAGE_DIR}"
    NORMALIZE _IN_BINARY_TREE)
  if(_IN_BINARY_TREE)
    cmake_path(RELATIVE_PATH _ABS_PACKAGE_DIR
      BASE_DIRECTORY "${CMAKE_BINARY_DIR}"
      OUTPUT_VARIABLE _REL_PATH)
    set(_REL_PATH "build/${_REL_PATH}")
  else()
    cmake_path(IS_PREFIX _PROJECT_SOURCE_DIR "${_ABS_PACKAGE_DIR}"
      NORMALIZE _IN_PROJECT)
    if(_IN_PROJECT)
      cmake_path(RELATIVE_PATH _ABS_PACKAGE_DIR
        BASE_DIRECTORY "${PROJECT_SOURCE_DIR}"
        OUTPUT_VARIABLE _REL_PATH)
    else()
      iree_package_path(_PACKAGE_PATH)
      get_filename_component(_SOURCE_NAME "${_ABS_PACKAGE_DIR}" NAME)
      set(_REL_PATH "${_PACKAGE_PATH}/${_SOURCE_NAME}")
    endif()
  endif()
  set(${OUT_VAR} "${_REL_PATH}" PARENT_SCOPE)
endfunction()

function(hrx_installed_tests_resolve_data DATA OUT_SOURCE_PATH OUT_REL_PATH)
  if(IS_ABSOLUTE "${DATA}")
    set(_SOURCE_PATH "${DATA}")
    hrx_installed_tests_source_relative_path("${_SOURCE_PATH}" _REL_PATH)
  elseif(EXISTS "${PROJECT_SOURCE_DIR}/${DATA}")
    set(_SOURCE_PATH "${PROJECT_SOURCE_DIR}/${DATA}")
    set(_REL_PATH "${DATA}")
  elseif(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${DATA}")
    set(_SOURCE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/${DATA}")
    hrx_installed_tests_source_relative_path("${_SOURCE_PATH}" _REL_PATH)
  else()
    set(_SOURCE_PATH "${CMAKE_CURRENT_BINARY_DIR}/${DATA}")
    cmake_path(RELATIVE_PATH _SOURCE_PATH
      BASE_DIRECTORY "${CMAKE_BINARY_DIR}"
      OUTPUT_VARIABLE _REL_PATH)
  endif()
  set(${OUT_SOURCE_PATH} "${_SOURCE_PATH}" PARENT_SCOPE)
  set(${OUT_REL_PATH} "${_REL_PATH}" PARENT_SCOPE)
endfunction()

function(hrx_installed_tests_append_data_map MAP_VAR SOURCE_PATH DATA INSTALLED_PATH)
  set(_MAP "${${MAP_VAR}}")
  list(APPEND _MAP "${DATA}|${INSTALLED_PATH}")
  if(NOT "${SOURCE_PATH}" STREQUAL "${DATA}")
    list(APPEND _MAP "${SOURCE_PATH}|${INSTALLED_PATH}")
  endif()
  set(${MAP_VAR} "${_MAP}" PARENT_SCOPE)
endfunction()

function(hrx_installed_tests_install_data OUT_VAR OUT_MAP_VAR)
  hrx_installed_tests_is_enabled(_ENABLED)
  if(NOT _ENABLED)
    return()
  endif()

  iree_package_path(_PACKAGE_PATH)
  set(_INSTALLED_DATA)
  set(_DATA_MAP)
  foreach(_DATA IN LISTS ARGN)
    if(TARGET "${_DATA}")
      hrx_installed_tests_install_target("${_DATA}" _INSTALLED_PATH)
    else()
      hrx_installed_tests_resolve_data("${_DATA}" _SOURCE_PATH _REL_PATH)
      if(IS_DIRECTORY "${_SOURCE_PATH}")
        hrx_installed_tests_install_source_tree(
          "${_SOURCE_PATH}" "${_REL_PATH}" _INSTALLED_PATH)
      else()
        hrx_installed_tests_install_source_file(
          "${_SOURCE_PATH}" "${_REL_PATH}" _INSTALLED_PATH)
      endif()
      hrx_installed_tests_append_data_map(
        _DATA_MAP "${_SOURCE_PATH}" "${_DATA}" "${_INSTALLED_PATH}")
    endif()
    list(APPEND _INSTALLED_DATA "${_INSTALLED_PATH}")
  endforeach()

  set(${OUT_VAR} "${_INSTALLED_DATA}" PARENT_SCOPE)
  set(${OUT_MAP_VAR} "${_DATA_MAP}" PARENT_SCOPE)
endfunction()

function(hrx_installed_tests_should_install_arg_path ARG OUT_VAR)
  if(NOT IS_ABSOLUTE "${ARG}" OR NOT EXISTS "${ARG}")
    set(${OUT_VAR} OFF PARENT_SCOPE)
    return()
  endif()

  get_filename_component(_ABS_ARG "${ARG}" ABSOLUTE)
  set(_PROJECT_SOURCE_DIR "${PROJECT_SOURCE_DIR}")
  set(_BINARY_DIR "${CMAKE_BINARY_DIR}")
  cmake_path(IS_PREFIX _PROJECT_SOURCE_DIR "${_ABS_ARG}" NORMALIZE _IN_PROJECT)
  cmake_path(IS_PREFIX _BINARY_DIR "${_ABS_ARG}" NORMALIZE _IN_BINARY_TREE)
  if(_IN_PROJECT OR _IN_BINARY_TREE)
    set(${OUT_VAR} ON PARENT_SCOPE)
  else()
    set(${OUT_VAR} OFF PARENT_SCOPE)
  endif()
endfunction()

function(hrx_installed_tests_install_arg_data OUT_VAR OUT_MAP_VAR)
  hrx_installed_tests_is_enabled(_ENABLED)
  if(NOT _ENABLED)
    return()
  endif()

  set(_INSTALLED_DATA)
  set(_DATA_MAP)
  foreach(_ARG IN LISTS ARGN)
    hrx_installed_tests_should_install_arg_path("${_ARG}" _SHOULD_INSTALL)
    if(NOT _SHOULD_INSTALL)
      continue()
    endif()
    hrx_installed_tests_resolve_data("${_ARG}" _SOURCE_PATH _REL_PATH)
    if(IS_DIRECTORY "${_SOURCE_PATH}")
      hrx_installed_tests_install_source_tree(
        "${_SOURCE_PATH}" "${_REL_PATH}" _INSTALLED_PATH)
    else()
      hrx_installed_tests_install_source_file(
        "${_SOURCE_PATH}" "${_REL_PATH}" _INSTALLED_PATH)
    endif()
    hrx_installed_tests_append_data_map(
      _DATA_MAP "${_SOURCE_PATH}" "${_ARG}" "${_INSTALLED_PATH}")
    list(APPEND _INSTALLED_DATA "${_INSTALLED_PATH}")
  endforeach()

  set(${OUT_VAR} "${_INSTALLED_DATA}" PARENT_SCOPE)
  set(${OUT_MAP_VAR} "${_DATA_MAP}" PARENT_SCOPE)
endfunction()

function(hrx_installed_tests_map_args OUT_VAR)
  hrx_installed_tests_is_enabled(_ENABLED)
  if(NOT _ENABLED)
    return()
  endif()

  set(_MAPPED_ARGS)
  foreach(_ARG IN LISTS ARGN)
    set(_MAPPED_ARG "${_ARG}")
    while(_MAPPED_ARG MATCHES "\\$<TARGET_FILE:([^>]+)>")
      set(_TARGET "${CMAKE_MATCH_1}")
      hrx_installed_tests_install_target("${_TARGET}" _INSTALLED_PATH)
      string(REPLACE "$<TARGET_FILE:${_TARGET}>" "${_INSTALLED_PATH}"
        _MAPPED_ARG "${_MAPPED_ARG}")
    endwhile()
    while(_MAPPED_ARG MATCHES "\\$<TARGET_FILE_DIR:([^>]+)>")
      set(_TARGET "${CMAKE_MATCH_1}")
      hrx_installed_tests_install_target("${_TARGET}" _INSTALLED_PATH)
      get_filename_component(_INSTALLED_DIR "${_INSTALLED_PATH}" DIRECTORY)
      string(REPLACE "$<TARGET_FILE_DIR:${_TARGET}>" "${_INSTALLED_DIR}"
        _MAPPED_ARG "${_MAPPED_ARG}")
    endwhile()
    if(_MAPPED_ARG MATCHES "\\$<")
      message(FATAL_ERROR
        "Installed tests cannot preserve generator expression in argument '${_ARG}'")
    endif()
    list(APPEND _MAPPED_ARGS "${_MAPPED_ARG}")
  endforeach()

  set(${OUT_VAR} "${_MAPPED_ARGS}" PARENT_SCOPE)
endfunction()

function(hrx_installed_tests_map_data_args OUT_VAR DATA_MAP)
  set(_MAPPED_ARGS)
  foreach(_ARG IN LISTS ARGN)
    set(_MAPPED_ARG "${_ARG}")
    foreach(_ENTRY IN LISTS DATA_MAP)
      string(FIND "${_ENTRY}" "|" _PATH_SEPARATOR_INDEX)
      if(_PATH_SEPARATOR_INDEX LESS 0)
        message(FATAL_ERROR
          "Installed test data path record is malformed: ${_ENTRY}")
      endif()
      string(SUBSTRING "${_ENTRY}" 0 ${_PATH_SEPARATOR_INDEX} _SOURCE_PATH)
      math(EXPR _INSTALLED_PATH_INDEX "${_PATH_SEPARATOR_INDEX} + 1")
      string(SUBSTRING "${_ENTRY}" ${_INSTALLED_PATH_INDEX} -1 _INSTALLED_PATH)
      if(NOT "${_SOURCE_PATH}" STREQUAL "")
        string(REPLACE "${_SOURCE_PATH}" "${_INSTALLED_PATH}"
          _MAPPED_ARG "${_MAPPED_ARG}")
      endif()
    endforeach()
    list(APPEND _MAPPED_ARGS "${_MAPPED_ARG}")
  endforeach()

  set(${OUT_VAR} "${_MAPPED_ARGS}" PARENT_SCOPE)
endfunction()

function(hrx_installed_tests_standard_environment TEST_NAME OUT_ENV OUT_ENV_MOD)
  string(MAKE_C_IDENTIFIER "${TEST_NAME}" _SAFE_TEST_NAME)
  set(_ENV
    "TEST_TMPDIR=\${_HRX_INSTALLED_TEST_TMP_ROOT}/${_SAFE_TEST_NAME}"
    "IREE_BINARY_DIR=\${_HRX_INSTALLED_TEST_ROOT}"
    "IREE_DYLIB_EXT=${CMAKE_SHARED_LIBRARY_SUFFIX}"
    "TEST_SRCDIR=\${_HRX_INSTALLED_TEST_DATA_ROOT}"
    "RUNFILES_DIR=\${_HRX_INSTALLED_TEST_DATA_ROOT}"
  )
  if(NOT IREE_HAL_DRIVER_VULKAN)
    list(APPEND _ENV "IREE_VULKAN_DISABLE=1")
  endif()
  if(NOT IREE_HAL_DRIVER_METAL)
    list(APPEND _ENV "IREE_METAL_DISABLE=1")
  endif()

  set(_HRX_INSTALL_TESTS_DIR "${HRX_INSTALL_TESTS_DIR}")
  cmake_path(IS_ABSOLUTE _HRX_INSTALL_TESTS_DIR _TESTS_DIR_IS_ABSOLUTE)
  if(_TESTS_DIR_IS_ABSOLUTE)
    set(_TESTS_CTEST_INSTALL_DIR "${HRX_INSTALL_TESTS_DIR}/ctest")
  else()
    set(_TESTS_CTEST_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/${HRX_INSTALL_TESTS_DIR}/ctest")
  endif()
  file(RELATIVE_PATH _PREFIX_LIB_FROM_CTEST
    "${_TESTS_CTEST_INSTALL_DIR}" "${CMAKE_INSTALL_FULL_LIBDIR}")
  file(RELATIVE_PATH _PREFIX_BIN_FROM_CTEST
    "${_TESTS_CTEST_INSTALL_DIR}" "${CMAKE_INSTALL_FULL_BINDIR}")
  set(_ENV_MOD
    "PATH=path_list_prepend:\${_HRX_INSTALLED_TEST_BIN_ROOT}"
    "PATH=path_list_prepend:\${CMAKE_CURRENT_LIST_DIR}/${_PREFIX_BIN_FROM_CTEST}"
    "LD_LIBRARY_PATH=path_list_prepend:\${_HRX_INSTALLED_TEST_LIB_ROOT}"
    "LD_LIBRARY_PATH=path_list_prepend:\${CMAKE_CURRENT_LIST_DIR}/${_PREFIX_LIB_FROM_CTEST}"
  )

  set_property(GLOBAL APPEND PROPERTY HRX_INSTALLED_TEST_TMPDIRS
    "\${_HRX_INSTALLED_TEST_TMP_ROOT}/${_SAFE_TEST_NAME}")
  set(${OUT_ENV} "${_ENV}" PARENT_SCOPE)
  set(${OUT_ENV_MOD} "${_ENV_MOD}" PARENT_SCOPE)
endfunction()

function(hrx_register_installed_test)
  hrx_installed_tests_is_enabled(_ENABLED)
  if(NOT _ENABLED OR HRX_SKIP_INSTALLED_TEST_REGISTRATION)
    return()
  endif()

  cmake_parse_arguments(
    _RULE
    "WILL_FAIL;DISABLED"
    "NAME;TARGET;COMMAND;TIMEOUT;RESOURCE_GROUP;WORKING_DIRECTORY"
    "ARGS;DATA;ENVIRONMENT;ENVIRONMENT_MODIFICATION;LABELS;REQUIRED_FILES"
    ${ARGN}
  )

  if(NOT _RULE_NAME)
    message(FATAL_ERROR "hrx_register_installed_test requires NAME")
  endif()

  if(_RULE_TARGET)
    hrx_installed_tests_install_target("${_RULE_TARGET}" _COMMAND)
  elseif(_RULE_COMMAND)
    set(_COMMAND "${_RULE_COMMAND}")
  else()
    message(FATAL_ERROR "hrx_register_installed_test requires TARGET or COMMAND")
  endif()

  hrx_installed_tests_map_args(_ARGS ${_RULE_ARGS})
  hrx_installed_tests_install_data(_INSTALLED_DATA _DATA_MAP ${_RULE_DATA})
  hrx_installed_tests_install_arg_data(_INSTALLED_ARG_DATA _ARG_DATA_MAP ${_ARGS})
  list(APPEND _INSTALLED_DATA ${_INSTALLED_ARG_DATA})
  list(APPEND _DATA_MAP ${_ARG_DATA_MAP})
  if(_INSTALLED_DATA)
    list(REMOVE_DUPLICATES _INSTALLED_DATA)
  endif()
  hrx_installed_tests_map_data_args(_ARGS "${_DATA_MAP}" ${_ARGS})

  hrx_installed_tests_standard_environment(
    "${_RULE_NAME}" _STANDARD_ENV _STANDARD_ENV_MOD)
  list(APPEND _STANDARD_ENV ${_RULE_ENVIRONMENT})
  list(APPEND _STANDARD_ENV_MOD ${_RULE_ENVIRONMENT_MODIFICATION})
  list(APPEND _INSTALLED_DATA ${_RULE_REQUIRED_FILES})

  set(_LINE "add_test(")
  hrx_installed_tests_append_quoted(_LINE "${_RULE_NAME}" "${_COMMAND}" ${_ARGS})
  string(APPEND _LINE ")\n")
  file(APPEND "${_HRX_INSTALLED_TESTS_CTEST_FILE}" "${_LINE}")

  set(_PROPS_LINE "set_tests_properties(")
  hrx_installed_tests_append_quoted(_PROPS_LINE "${_RULE_NAME}")
  string(APPEND _PROPS_LINE " PROPERTIES")
  if(_RULE_WORKING_DIRECTORY)
    hrx_installed_tests_append_property(
      _PROPS_LINE "WORKING_DIRECTORY" "${_RULE_WORKING_DIRECTORY}")
  else()
    hrx_installed_tests_append_property(
      _PROPS_LINE "WORKING_DIRECTORY" "\${CMAKE_CURRENT_LIST_DIR}")
  endif()
  if(_STANDARD_ENV)
    list(JOIN _STANDARD_ENV ";" _ENV_JOINED)
    hrx_installed_tests_append_property(_PROPS_LINE "ENVIRONMENT" "${_ENV_JOINED}")
  endif()
  if(_STANDARD_ENV_MOD)
    list(JOIN _STANDARD_ENV_MOD ";" _ENV_MOD_JOINED)
    hrx_installed_tests_append_property(
      _PROPS_LINE "ENVIRONMENT_MODIFICATION" "${_ENV_MOD_JOINED}")
  endif()
  if(_RULE_LABELS)
    list(JOIN _RULE_LABELS ";" _LABELS_JOINED)
    hrx_installed_tests_append_property(_PROPS_LINE "LABELS" "${_LABELS_JOINED}")
  endif()
  if(_RULE_TIMEOUT)
    hrx_installed_tests_append_property(_PROPS_LINE "TIMEOUT" "${_RULE_TIMEOUT}")
  endif()
  if(_RULE_RESOURCE_GROUP)
    hrx_installed_tests_append_property(
      _PROPS_LINE "RESOURCE_LOCK" "${_RULE_RESOURCE_GROUP}")
  endif()
  if(_INSTALLED_DATA)
    list(JOIN _INSTALLED_DATA ";" _REQUIRED_JOINED)
    hrx_installed_tests_append_property(
      _PROPS_LINE "REQUIRED_FILES" "${_REQUIRED_JOINED}")
  endif()
  if(_RULE_WILL_FAIL)
    hrx_installed_tests_append_property(_PROPS_LINE "WILL_FAIL" "TRUE")
  endif()
  if(_RULE_DISABLED)
    hrx_installed_tests_append_property(_PROPS_LINE "DISABLED" "TRUE")
  endif()

  string(APPEND _PROPS_LINE ")\n")
  file(APPEND "${_HRX_INSTALLED_TESTS_CTEST_FILE}" "${_PROPS_LINE}")
endfunction()

function(hrx_register_installed_python_test)
  hrx_installed_tests_is_enabled(_ENABLED)
  if(NOT _ENABLED OR HRX_SKIP_INSTALLED_TEST_REGISTRATION)
    return()
  endif()

  cmake_parse_arguments(
    _RULE
    ""
    "NAME;SRC;TIMEOUT"
    "ARGS;LABELS;PACKAGE_DIRS"
    ${ARGN}
  )

  if(NOT IS_ABSOLUTE "${_RULE_SRC}")
    set(_SOURCE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/${_RULE_SRC}")
  else()
    set(_SOURCE_PATH "${_RULE_SRC}")
  endif()
  hrx_installed_tests_project_relative_path("${_SOURCE_PATH}" _SRC_REL_PATH)
  hrx_installed_tests_install_source_file(
    "${_SOURCE_PATH}" "${_SRC_REL_PATH}" _INSTALLED_SRC)

  set(_PYTHONPATH_MODS)
  set(_INSTALLED_PACKAGE_DIRS)
  foreach(_PACKAGE_DIR IN LISTS _RULE_PACKAGE_DIRS)
    if(NOT IS_ABSOLUTE "${_PACKAGE_DIR}")
      set(_PACKAGE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/${_PACKAGE_DIR}")
    endif()
    hrx_installed_tests_python_package_relative_path(
      "${_PACKAGE_DIR}" _PACKAGE_REL_PATH)
    hrx_installed_tests_install_source_tree(
      "${_PACKAGE_DIR}" "${_PACKAGE_REL_PATH}" _INSTALLED_PACKAGE_DIR)
    list(APPEND _INSTALLED_PACKAGE_DIRS "${_INSTALLED_PACKAGE_DIR}")
  endforeach()
  # CTest applies ENVIRONMENT_MODIFICATION entries sequentially. Since each
  # package path is prepended to PYTHONPATH, emit them in reverse so the final
  # installed test environment preserves the PACKAGE_DIRS order used by the
  # build-tree test. This matters when a generated tree contains partial Python
  # packages that must not shadow the source tree.
  list(REVERSE _INSTALLED_PACKAGE_DIRS)
  foreach(_INSTALLED_PACKAGE_DIR IN LISTS _INSTALLED_PACKAGE_DIRS)
    list(APPEND _PYTHONPATH_MODS
      "PYTHONPATH=path_list_prepend:${_INSTALLED_PACKAGE_DIR}")
  endforeach()

  hrx_register_installed_test(
    NAME "${_RULE_NAME}"
    COMMAND "python3"
    ARGS "${_INSTALLED_SRC}" ${_RULE_ARGS}
    LABELS ${_RULE_LABELS}
    TIMEOUT "${_RULE_TIMEOUT}"
    ENVIRONMENT "PYTHONDONTWRITEBYTECODE=1"
    ENVIRONMENT_MODIFICATION ${_PYTHONPATH_MODS}
  )
endfunction()

function(hrx_create_installed_tests)
  hrx_installed_tests_is_enabled(_ENABLED)
  if(NOT _ENABLED)
    return()
  endif()

  get_property(_DEFERRED_TARGETS GLOBAL PROPERTY HRX_INSTALLED_TEST_DEFERRED_TARGETS)
  foreach(_DEFERRED_TARGET IN LISTS _DEFERRED_TARGETS)
    if(NOT TARGET "${_DEFERRED_TARGET}")
      message(FATAL_ERROR
        "Installed test target was referenced before it existed and was never created: ${_DEFERRED_TARGET}")
    endif()
    hrx_installed_tests_install_target("${_DEFERRED_TARGET}" _INSTALLED_PATH)
    get_property(_DEFERRED_TARGET_PATHS GLOBAL PROPERTY HRX_INSTALLED_TEST_DEFERRED_TARGET_PATHS)
    foreach(_DEFERRED_TARGET_PATH IN LISTS _DEFERRED_TARGET_PATHS)
      string(FIND "${_DEFERRED_TARGET_PATH}" "|" _PATH_SEPARATOR_INDEX)
      if(_PATH_SEPARATOR_INDEX LESS 0)
        message(FATAL_ERROR
          "Installed test target path record is malformed: ${_DEFERRED_TARGET_PATH}")
      endif()
      string(SUBSTRING "${_DEFERRED_TARGET_PATH}" 0 ${_PATH_SEPARATOR_INDEX} _PATH_TARGET)
      math(EXPR _PATH_VALUE_INDEX "${_PATH_SEPARATOR_INDEX} + 1")
      string(LENGTH "${_DEFERRED_TARGET_PATH}" _DEFERRED_TARGET_PATH_LENGTH)
      math(EXPR _PATH_VALUE_LENGTH "${_DEFERRED_TARGET_PATH_LENGTH} - ${_PATH_VALUE_INDEX}")
      string(SUBSTRING "${_DEFERRED_TARGET_PATH}" ${_PATH_VALUE_INDEX} ${_PATH_VALUE_LENGTH} _EXPECTED_PATH)
      if(_PATH_TARGET STREQUAL _DEFERRED_TARGET)
        if(NOT _EXPECTED_PATH STREQUAL _INSTALLED_PATH)
          message(FATAL_ERROR
            "Installed test target '${_DEFERRED_TARGET}' resolved to '${_INSTALLED_PATH}' "
            "after a test had already recorded '${_EXPECTED_PATH}'. Add the target before "
            "the test registration or update the deferred path inference.")
        endif()
      endif()
    endforeach()
  endforeach()

  get_property(_TMPDIRS GLOBAL PROPERTY HRX_INSTALLED_TEST_TMPDIRS)
  set(_CUSTOM "# Generated by hrx_installed_tests.cmake.\n")
  string(APPEND _CUSTOM
    "get_filename_component(_HRX_INSTALLED_TEST_ROOT \"\${CMAKE_CURRENT_LIST_DIR}\" ABSOLUTE)\n"
    "if(DEFINED ENV{HRX_TEST_TMPDIR} AND NOT \"\$ENV{HRX_TEST_TMPDIR}\" STREQUAL \"\")\n"
    "  file(TO_CMAKE_PATH \"\$ENV{HRX_TEST_TMPDIR}\" _HRX_INSTALLED_TEST_TMP_ROOT)\n"
    "else()\n"
    "  set(_HRX_INSTALLED_TEST_TMP_ROOT \"\${_HRX_INSTALLED_TEST_ROOT}/tmp\")\n"
    "endif()\n"
    "get_filename_component(_HRX_INSTALLED_TEST_TMP_ROOT \"\${_HRX_INSTALLED_TEST_TMP_ROOT}\" ABSOLUTE)\n")
  string(APPEND _CUSTOM "set(CTEST_CUSTOM_PRE_TEST\n")
  set(_CUR_RM_CMD "  \"cmake -E rm -rf")
  set(_CUR_CMD "  \"cmake -E make_directory")
  set(_CMD_LEN_LIMIT 8191)
  foreach(_TMPDIR IN LISTS _TMPDIRS)
    string(LENGTH "${_CUR_RM_CMD}" _CUR_RM_CMD_LEN)
    string(LENGTH "${_TMPDIR}" _DIR_LEN)
    math(EXPR _NEW_RM_CMD_LEN "${_CUR_RM_CMD_LEN} + ${_DIR_LEN} + 3")
    if(_NEW_RM_CMD_LEN GREATER _CMD_LEN_LIMIT)
      string(APPEND _CUSTOM "${_CUR_RM_CMD}\"\n")
      set(_CUR_RM_CMD "  \"cmake -E rm -rf")
    endif()
    string(APPEND _CUR_RM_CMD " \\\"${_TMPDIR}\\\"")

    string(LENGTH "${_CUR_CMD}" _CUR_CMD_LEN)
    math(EXPR _NEW_CMD_LEN "${_CUR_CMD_LEN} + ${_DIR_LEN} + 3")
    if(_NEW_CMD_LEN GREATER _CMD_LEN_LIMIT)
      string(APPEND _CUSTOM "${_CUR_CMD}\"\n")
      set(_CUR_CMD "  \"cmake -E make_directory")
    endif()
    string(APPEND _CUR_CMD " \\\"${_TMPDIR}\\\"")
  endforeach()
  if(NOT _CUR_RM_CMD STREQUAL "  \"cmake -E rm -rf")
    string(APPEND _CUSTOM "${_CUR_RM_CMD}\"\n")
  endif()
  if(NOT _CUR_CMD STREQUAL "  \"cmake -E make_directory")
    string(APPEND _CUSTOM "${_CUR_CMD}\"\n")
  endif()
  string(APPEND _CUSTOM ")\n")
  file(WRITE "${_HRX_INSTALLED_TESTS_CUSTOM_FILE}" "${_CUSTOM}")

  install(FILES
    "${_HRX_INSTALLED_TESTS_ROOT_FILE}"
    "${_HRX_INSTALLED_TESTS_CUSTOM_FILE}"
    DESTINATION "${HRX_INSTALL_TESTS_DIR}"
    COMPONENT "${HRX_INSTALL_TESTS_COMPONENT}")
  install(FILES
    "${_HRX_INSTALLED_TESTS_CTEST_FILE}"
    DESTINATION "${HRX_INSTALL_TESTS_DIR}/ctest"
    COMPONENT "${HRX_INSTALL_TESTS_COMPONENT}")
endfunction()
