# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//build_tools/bazel:python.bzl", "iree_py_library", "iree_py_test")

package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],  # Apache 2.0
)

iree_py_library(
    name = "reporting",
    srcs = [
        "__init__.py",
        "compile_report.py",
        "compile_report_bank_service.py",
        "compile_report_capabilities.py",
        "compile_report_move_causes.py",
        "compile_report_suggestions.py",
        "compile_report_view.py",
        "compile_report_workload.py",
    ],
    imports = ["../.."],
)

iree_py_test(
    name = "reporting_test",
    srcs = [
        "compile_report_bank_service_test.py",
        "compile_report_suggestions_test.py",
        "compile_report_test.py",
        "//loom/py/loom/tools:pytest_style_runner.py",
    ],
    args = [
        "loom.reporting.compile_report_bank_service_test",
        "loom.reporting.compile_report_suggestions_test",
        "loom.reporting.compile_report_test",
    ],
    main = "pytest_style_runner.py",
    deps = [":reporting"],
)
