# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""Repository rule exposing optional AMDGPU builtin device compiler tools."""

load(
    "//build_tools/bazel:elf_dynamic_library_closure.bzl",
    "elf_loader_environment",
    "try_resolve_elf_dynamic_library_closure",
)

_DEFAULT_STUB_ERROR = "AMDGPU device binary source mode requires --repo_env=IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN=auto, rocm, llvm-tools, or llvm-project."

_STUB_BUILD = """\
# AUTO-GENERATED by device_toolchain_repository.bzl - do not edit.

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "unused",
    srcs = [],
)
"""

_STUB_PATHS_TEMPLATE = """\
# AUTO-GENERATED by device_toolchain_repository.bzl - do not edit.

AMDGPU_DEVICE_TOOLCHAIN_AVAILABLE = False
AMDGPU_DEVICE_TOOLCHAIN_ERROR = {ERROR}
AMDGPU_CLANG_TOOL = ""
AMDGPU_LLVM_AR_TOOL = ""
AMDGPU_LLVM_LINK_TOOL = ""
AMDGPU_LLD_TOOL = ""
AMDGPU_LLVM_OBJCOPY_TOOL = ""
AMDGPU_CLANG_RESOURCE_HEADERS = ""
AMDGPU_CLANG_RESOURCE_MARKER = ""
AMDGPU_CLANG_RESOURCE_INCLUDE_ARGS = []
AMDGPU_HIP_DEVICE_LIBRARIES_AVAILABLE = False
AMDGPU_HIP_DEVICE_LIBRARIES = ""
AMDGPU_HIP_DEVICE_LIBRARIES_MARKER = ""
AMDGPU_CLANG_OFFLOAD_BUNDLER_TOOL = ""
"""

_PREBUILT_TOOL_BZL = """\
\"\"\"Rule for exposing pre-built binaries as executable Bazel tools.\"\"\"

def _prebuilt_tool_impl(ctx):
{PREBUILT_TOOL_IMPLEMENTATION}
    runfiles = ctx.runfiles(files = ctx.files.data + [ctx.file.src])
    return [DefaultInfo(
        executable = output,
        files = depset([output]),
        runfiles = runfiles,
    )]

prebuilt_tool = rule(
    implementation = _prebuilt_tool_impl,
    executable = True,
    attrs = {
        "src": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "The pre-built binary file.",
        ),
        "data": attr.label_list(
            allow_files = True,
            doc = "Additional files the tool needs at runtime.",
        ),
    },
    doc = "Wraps a pre-built binary as an executable Bazel target.",
)
"""

_POSIX_PREBUILT_TOOL_IMPLEMENTATION = """\
    output = ctx.actions.declare_file(ctx.label.name)
    wrapper = \"\"\"#!/bin/sh
set -eu

runfiles_dir=
if [ -d \"$0.runfiles\" ]; then
  runfiles_dir=\"$0.runfiles\"
elif [ -n \"${RUNFILES_DIR:-}\" ] && [ -d \"$RUNFILES_DIR\" ]; then
  runfiles_dir=\"$RUNFILES_DIR\"
else
  case \"$0\" in
    *.runfiles/*)
      runfiles_dir=\"${0%%%%.runfiles/*}.runfiles\"
      ;;
  esac
fi
if [ -z \"$runfiles_dir\" ] || [ ! -d \"$runfiles_dir\" ]; then
  echo \"prebuilt tool wrapper: unable to locate Bazel runfiles\" >&2
  exit 1
fi

tool_path=
for candidate in \"$runfiles_dir\"/*/bin/%s; do
  if [ ! -x \"$candidate\" ]; then
    continue
  fi
  if [ -n \"$tool_path\" ]; then
    echo \"prebuilt tool wrapper: multiple runfiles match bin/%s\" >&2
    exit 1
  fi
  tool_path=\"$candidate\"
done
if [ -z \"$tool_path\" ]; then
  echo \"prebuilt tool wrapper: missing runfile bin/%s\" >&2
  exit 1
fi

tool_root=$(dirname \"$(dirname \"$tool_path\")\")
dynamic_library_dir=\"$tool_root/host_dynamic_libraries\"
if [ -d \"$dynamic_library_dir\" ]; then
  export LD_LIBRARY_PATH=\"$dynamic_library_dir\"
fi
exec \"$tool_path\" \"$@\"
\"\"\" % (
        ctx.file.src.basename,
        ctx.file.src.basename,
        ctx.file.src.basename,
    )
    ctx.actions.write(
        output = output,
        content = wrapper,
        is_executable = True,
    )
"""

_WINDOWS_PREBUILT_TOOL_IMPLEMENTATION = """\
    output = ctx.actions.declare_file(ctx.label.name + ".exe")
    ctx.actions.symlink(
        output = output,
        target_file = ctx.file.src,
        is_executable = True,
    )
"""

_LOCAL_BUILD_TEMPLATE = """\
# AUTO-GENERATED by device_toolchain_repository.bzl - do not edit.

load(":prebuilt_tool.bzl", "prebuilt_tool")

package(default_visibility = ["//visibility:public"])

prebuilt_tool(
    name = "clang",
    src = "bin/clang{EXECUTABLE_SUFFIX}",
    data = [":host_dynamic_libraries"],
)

prebuilt_tool(
    name = "llvm-ar",
    src = "bin/llvm-ar{EXECUTABLE_SUFFIX}",
    data = [":host_dynamic_libraries"],
)

prebuilt_tool(
    name = "llvm-link",
    src = "bin/llvm-link{EXECUTABLE_SUFFIX}",
    data = [":host_dynamic_libraries"],
)

prebuilt_tool(
    name = "lld",
    src = "bin/lld{EXECUTABLE_SUFFIX}",
    data = [":host_dynamic_libraries"],
)

prebuilt_tool(
    name = "llvm-objcopy",
    src = "bin/llvm-objcopy{EXECUTABLE_SUFFIX}",
    data = [":host_dynamic_libraries"],
)

filegroup(
    name = "host_dynamic_libraries",
    srcs = glob(["host_dynamic_libraries/**"]),
)

filegroup(
    name = "clang_resource_headers",
    srcs = glob(["clang_resource_include/**"]),
)

filegroup(
    name = "clang_resource_include_marker",
    srcs = ["clang_resource_include/stddef.h"],
)
"""

_ROCM_DEVICE_LIBRARIES_BUILD = """\

prebuilt_tool(
    name = "clang-offload-bundler",
    src = "bin/clang-offload-bundler{EXECUTABLE_SUFFIX}",
    data = [":host_dynamic_libraries"],
)

filegroup(
    name = "hip_device_libraries",
    srcs = glob(["hip_device_libraries/**"]),
)

filegroup(
    name = "hip_device_libraries_marker",
    srcs = ["hip_device_libraries/ockl.bc"],
)
"""

_LOCAL_PATHS_TEMPLATE = """\
# AUTO-GENERATED by device_toolchain_repository.bzl - do not edit.

AMDGPU_DEVICE_TOOLCHAIN_AVAILABLE = True
AMDGPU_DEVICE_TOOLCHAIN_ERROR = ""
AMDGPU_CLANG_TOOL = "@iree_amdgpu_device_toolchain//:clang"
AMDGPU_LLVM_AR_TOOL = "@iree_amdgpu_device_toolchain//:llvm-ar"
AMDGPU_LLVM_LINK_TOOL = "@iree_amdgpu_device_toolchain//:llvm-link"
AMDGPU_LLD_TOOL = "@iree_amdgpu_device_toolchain//:lld"
AMDGPU_LLVM_OBJCOPY_TOOL = "@iree_amdgpu_device_toolchain//:llvm-objcopy"
AMDGPU_CLANG_RESOURCE_HEADERS = "@iree_amdgpu_device_toolchain//:clang_resource_headers"
AMDGPU_CLANG_RESOURCE_MARKER = "@iree_amdgpu_device_toolchain//:clang_resource_include_marker"
AMDGPU_CLANG_RESOURCE_INCLUDE_ARGS = [
    "--clang-resource-include",
    "$$(dirname $(location @iree_amdgpu_device_toolchain//:clang_resource_include_marker))",
]
"""

_ROCM_DEVICE_LIBRARIES_PATHS = """\
AMDGPU_HIP_DEVICE_LIBRARIES_AVAILABLE = True
AMDGPU_HIP_DEVICE_LIBRARIES = "@iree_amdgpu_device_toolchain//:hip_device_libraries"
AMDGPU_HIP_DEVICE_LIBRARIES_MARKER = "@iree_amdgpu_device_toolchain//:hip_device_libraries_marker"
AMDGPU_CLANG_OFFLOAD_BUNDLER_TOOL = "@iree_amdgpu_device_toolchain//:clang-offload-bundler"
"""

_NO_ROCM_DEVICE_LIBRARIES_PATHS = """\
AMDGPU_HIP_DEVICE_LIBRARIES_AVAILABLE = False
AMDGPU_HIP_DEVICE_LIBRARIES = ""
AMDGPU_HIP_DEVICE_LIBRARIES_MARKER = ""
AMDGPU_CLANG_OFFLOAD_BUNDLER_TOOL = ""
"""

_LLVM_PROJECT_BUILD = """\
# AUTO-GENERATED by device_toolchain_repository.bzl - do not edit.

package(default_visibility = ["//visibility:public"])

alias(
    name = "clang",
    actual = "@llvm-project//clang:clang",
)

alias(
    name = "llvm-ar",
    actual = "@llvm-project//llvm:llvm-ar",
)

alias(
    name = "llvm-link",
    actual = "@llvm-project//llvm:llvm-link",
)

alias(
    name = "lld",
    actual = "@llvm-project//lld:lld",
)

alias(
    name = "llvm-objcopy",
    actual = "@llvm-project//llvm:llvm-objcopy",
)
"""

_LLVM_PROJECT_PATHS = """\
# AUTO-GENERATED by device_toolchain_repository.bzl - do not edit.

AMDGPU_DEVICE_TOOLCHAIN_AVAILABLE = True
AMDGPU_DEVICE_TOOLCHAIN_ERROR = ""
AMDGPU_CLANG_TOOL = "@iree_amdgpu_device_toolchain//:clang"
AMDGPU_LLVM_AR_TOOL = "@iree_amdgpu_device_toolchain//:llvm-ar"
AMDGPU_LLVM_LINK_TOOL = "@iree_amdgpu_device_toolchain//:llvm-link"
AMDGPU_LLD_TOOL = "@iree_amdgpu_device_toolchain//:lld"
AMDGPU_LLVM_OBJCOPY_TOOL = "@iree_amdgpu_device_toolchain//:llvm-objcopy"
AMDGPU_CLANG_RESOURCE_HEADERS = "@llvm-project//clang:builtin_headers_gen"
AMDGPU_CLANG_RESOURCE_MARKER = ""
AMDGPU_CLANG_RESOURCE_INCLUDE_ARGS = [
    "--clang-resource-include",
    "$(BINDIR)/external/+_repo_rules+llvm-project/clang/staging/include/",
]
AMDGPU_HIP_DEVICE_LIBRARIES_AVAILABLE = False
AMDGPU_HIP_DEVICE_LIBRARIES = ""
AMDGPU_HIP_DEVICE_LIBRARIES_MARKER = ""
AMDGPU_CLANG_OFFLOAD_BUNDLER_TOOL = ""
"""

def _write_stub_repository(repository_ctx, error = _DEFAULT_STUB_ERROR):
    repository_ctx.file("BUILD.bazel", _STUB_BUILD)
    repository_ctx.file(
        "paths.bzl",
        _STUB_PATHS_TEMPLATE.replace("{ERROR}", repr(error)),
    )

def _normalize_path(path):
    return path.replace("\\", "/")

def _join_path(left, right):
    left = _normalize_path(left)
    if left.endswith("/"):
        return left + right
    return left + "/" + right

def _dirname(path):
    path = _normalize_path(path)
    if "/" not in path:
        return "."
    return path.rsplit("/", 1)[0]

def _basename(path):
    path = _normalize_path(path)
    if "/" not in path:
        return path
    return path.rsplit("/", 1)[1]

def _append_unique(values, new_values):
    for value in new_values:
        if value not in values:
            values.append(value)

def _is_windows(repository_ctx):
    return repository_ctx.os.name.lower().startswith("windows")

def _tool_environment(repository_ctx):
    if _is_windows(repository_ctx):
        return {}
    return elf_loader_environment()

def _canonical_path(repository_ctx, path, description):
    path = repository_ctx.path(path)
    if not path.exists:
        return struct(
            error = "{} does not exist: {}".format(description, path),
            path = "",
        )
    repository_ctx.watch(path)
    canonical_path = repository_ctx.path(path.realpath)
    if not canonical_path.exists:
        return struct(
            error = "{} resolves to a missing path: {}".format(
                description,
                canonical_path,
            ),
            path = "",
        )
    repository_ctx.watch(canonical_path)
    return struct(
        error = "",
        path = _normalize_path(str(canonical_path.realpath)),
    )

def _resolve_executable(repository_ctx, candidate):
    candidate = _normalize_path(candidate)
    candidates = [candidate]
    if _is_windows(repository_ctx) and not candidate.lower().endswith(".exe"):
        candidates.append(candidate + ".exe")
    for path in candidates:
        candidate_path = repository_ctx.path(path)
        if not candidate_path.exists:
            continue
        if _is_windows(repository_ctx):
            repository_ctx.watch(candidate_path)
            return _normalize_path(str(candidate_path.realpath))
        result = repository_ctx.execute(["test", "-x", path], quiet = True)
        if result.return_code == 0:
            repository_ctx.watch(candidate_path)
            return _normalize_path(str(candidate_path.realpath))
    return ""

def _candidate_rocm_roots(repository_ctx):
    roots = []
    for name in [
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_ROCM_PATH",
        "IREE_ROCM_PATH",
        "ROCM_PATH",
        "ROCM_ROOT",
        "ROCM_HOME",
        "HIP_PATH",
    ]:
        value = repository_ctx.getenv(name)
        if not value:
            continue
        value = _normalize_path(value)
        _append_unique(roots, [value])
        if name == "HIP_PATH" and _basename(value) == "hip":
            _append_unique(roots, [_dirname(value)])

    hipcc = repository_ctx.which("hipcc")
    if hipcc:
        _append_unique(roots, [_dirname(_dirname(str(hipcc)))])
    if not _is_windows(repository_ctx) and repository_ctx.path("/opt/rocm").exists:
        _append_unique(roots, ["/opt/rocm"])
    return roots

def _rocm_tool_directories(root):
    return [
        _join_path(root, "lib/llvm/bin"),
        _join_path(root, "llvm/bin"),
        _join_path(root, "bin"),
    ]

def _configured_tool_directories(repository_ctx):
    directories = []
    for name in [
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_LLVM_TOOLS_DIR",
        "IREE_HOST_BIN_DIR",
        "IREE_HOST_TOOLS",
        "IREE_HOST_TOOLS_DIR",
        "IREE_BINARY_DIR",
        "IREE_LLVM_TOOLS_DIR",
        "IREE_LLVM_TOOL_DIR",
        "LLVM_TOOLS_BINARY_DIR",
        "LLVM_BINARY_DIR",
    ]:
        value = repository_ctx.getenv(name)
        if not value:
            continue
        value = _normalize_path(value)
        _append_unique(directories, [
            value,
            _join_path(value, "bin"),
            _join_path(value, "llvm-project/bin"),
            _join_path(value, "llvm/bin"),
            _join_path(value, "lib/llvm/bin"),
        ])
    return directories

def _candidate_clang_paths(repository_ctx, mode):
    candidates = []
    for name in [
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_CLANG_BINARY",
        "IREE_CLANG_BINARY",
        "CLANG",
    ]:
        value = repository_ctx.getenv(name)
        if value:
            _append_unique(candidates, [value])

    directories = []
    if mode in ["auto", "llvm-tools"]:
        _append_unique(directories, _configured_tool_directories(repository_ctx))
    if mode in ["auto", "rocm"]:
        for root in _candidate_rocm_roots(repository_ctx):
            _append_unique(directories, _rocm_tool_directories(root))
    for directory in directories:
        for name in ["clang", "amdclang"]:
            _append_unique(candidates, [_join_path(directory, name)])

    if mode == "auto":
        for name in ["clang", "amdclang"]:
            path = repository_ctx.which(name)
            if path:
                _append_unique(candidates, [str(path)])
    return candidates

def _find_clang(repository_ctx, mode):
    rejected = []
    for candidate in _candidate_clang_paths(repository_ctx, mode):
        resolved = _resolve_executable(repository_ctx, candidate)
        if not resolved:
            continue
        clang_result = _canonical_path(
            repository_ctx,
            resolved,
            "clang candidate",
        )
        if clang_result.error:
            rejected.append(clang_result.error)
            continue
        clang = clang_result.path
        result = repository_ctx.execute(
            [clang, "--print-targets"],
            environment = _tool_environment(repository_ctx),
            quiet = True,
        )
        if result.return_code == 0 and "amdgcn" in result.stdout:
            return struct(error = "", path = clang)
        rejected.append(clang)
    return struct(
        error = (
            "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN={} could not find clang with " +
            "AMDGPU support; configure a ROCm root, LLVM tools directory, or " +
            "explicit clang binary. Rejected candidates: {}"
        ).format(mode, ", ".join(rejected)),
        path = "",
    )

def _clang_reported_tool(repository_ctx, clang, name, description):
    result = repository_ctx.execute(
        [clang, "--print-prog-name=" + name],
        environment = _tool_environment(repository_ctx),
        quiet = True,
    )
    if result.return_code != 0:
        return struct(
            error = "Failed to query {} from {}:\n{}".format(
                description,
                clang,
                result.stderr,
            ),
            path = "",
        )
    printed_path = result.stdout.strip()
    if not printed_path:
        return struct(
            error = "{} returned an empty path for {}".format(
                clang,
                description,
            ),
            path = "",
        )
    for candidate in [
        printed_path,
        _join_path(_dirname(clang), printed_path),
    ]:
        resolved = _resolve_executable(repository_ctx, candidate)
        if resolved:
            return _canonical_path(repository_ctx, resolved, description)
    return struct(
        error = "{} reported a missing {} executable: {}".format(
            clang,
            description,
            printed_path,
        ),
        path = "",
    )

def _detect_clang_resource_dir(repository_ctx, clang):
    result = repository_ctx.execute(
        [clang, "-print-resource-dir"],
        environment = _tool_environment(repository_ctx),
        quiet = True,
    )
    if result.return_code != 0:
        return struct(
            error = "Failed to query clang resource directory from {}:\n{}".format(
                clang,
                result.stderr,
            ),
            path = "",
        )
    resource_dir = result.stdout.strip()
    if not resource_dir:
        return struct(
            error = "clang resource directory query returned an empty path from {}".format(clang),
            path = "",
        )
    return struct(error = "", path = _normalize_path(resource_dir))

def _detect_clang_resource_include(repository_ctx, clang):
    resource_dir_result = _detect_clang_resource_dir(repository_ctx, clang)
    if resource_dir_result.error:
        return resource_dir_result
    include_dir = _join_path(
        resource_dir_result.path,
        "include",
    )
    include_result = _canonical_path(
        repository_ctx,
        include_dir,
        "clang resource include directory",
    )
    if include_result.error:
        return include_result
    marker_result = _canonical_path(
        repository_ctx,
        _join_path(include_result.path, "stddef.h"),
        "clang resource include marker",
    )
    if marker_result.error:
        return marker_result
    return include_result

def _is_rocm_device_library_dir(repository_ctx, candidate):
    path = repository_ctx.path(candidate)
    if not path.exists:
        return False
    for filename in ["hip.bc", "ockl.bc", "ocml.bc"]:
        if not repository_ctx.path(_join_path(candidate, filename)).exists:
            return False
    return True

def _detect_rocm_device_libraries(
        repository_ctx,
        clang_resource_include):
    candidates = []
    explicit = repository_ctx.getenv(
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_ROCM_DEVICE_LIB_PATH",
    )
    if explicit:
        candidates.append(explicit)

    resource_dir = _dirname(clang_resource_include)
    llvm_root = _dirname(_dirname(_dirname(resource_dir)))
    candidates.append(_join_path(llvm_root, "amdgcn/bitcode"))

    for rocm_root in _candidate_rocm_roots(repository_ctx):
        candidates.extend([
            _join_path(rocm_root, "amdgcn/bitcode"),
            _join_path(rocm_root, "lib/amdgcn/bitcode"),
            _join_path(rocm_root, "llvm/amdgcn/bitcode"),
            _join_path(rocm_root, "lib/llvm/amdgcn/bitcode"),
        ])

    for candidate in candidates:
        if _is_rocm_device_library_dir(repository_ctx, candidate):
            candidate_result = _canonical_path(
                repository_ctx,
                candidate,
                "ROCm device library directory",
            )
            if not candidate_result.error:
                return candidate_result.path
    return ""

def _unavailable_device_toolchain(error):
    return struct(
        available = False,
        clang_resource_include = "",
        error = error,
        rocm_device_libraries = "",
        tools = {},
    )

def discover_amdgpu_device_toolchain(repository_ctx, mode):
    """Discovers one coherent local AMDGPU device toolchain.

    Args:
      repository_ctx: Repository context used to inspect and invoke tools.
      mode: Local discovery mode: auto, rocm, or llvm-tools.

    Returns:
      A struct describing either the complete base AMDGPU toolchain or why it
      is unavailable. Optional HIP device-library support is present only when
      both the ROCm bitcode libraries and Clang-reported offload bundler exist.
    """
    clang_result = _find_clang(repository_ctx, mode)
    if clang_result.error:
        return _unavailable_device_toolchain(clang_result.error)
    clang = clang_result.path

    tools = {"clang": clang}
    for tool_name, clang_name, description in [
        ("llvm-ar", "llvm-ar", "llvm-ar"),
        ("llvm-link", "llvm-link", "llvm-link"),
        ("lld", "ld.lld", "ld.lld"),
        ("llvm-objcopy", "llvm-objcopy", "llvm-objcopy"),
    ]:
        tool_result = _clang_reported_tool(
            repository_ctx,
            clang,
            clang_name,
            description,
        )
        if tool_result.error:
            return _unavailable_device_toolchain(tool_result.error)
        tools[tool_name] = tool_result.path

    clang_resource_result = _detect_clang_resource_include(
        repository_ctx,
        clang,
    )
    if clang_resource_result.error:
        return _unavailable_device_toolchain(clang_resource_result.error)
    clang_resource_include = clang_resource_result.path

    rocm_device_libraries = _detect_rocm_device_libraries(
        repository_ctx,
        clang_resource_include,
    )
    if rocm_device_libraries:
        bundler_result = _clang_reported_tool(
            repository_ctx,
            clang,
            "clang-offload-bundler",
            "clang-offload-bundler",
        )
        if bundler_result.error:
            rocm_device_libraries = ""
        else:
            tools["clang-offload-bundler"] = bundler_result.path

    return struct(
        available = True,
        clang_resource_include = clang_resource_include,
        error = "",
        rocm_device_libraries = rocm_device_libraries,
        tools = tools,
    )

def _write_local_toolchain_repo(
        repository_ctx,
        tools,
        host_dynamic_libraries,
        clang_resource_include,
        rocm_device_libraries):
    executable_suffix = ".exe" if _is_windows(repository_ctx) else ""
    prebuilt_tool_implementation = (
        _WINDOWS_PREBUILT_TOOL_IMPLEMENTATION if _is_windows(repository_ctx) else _POSIX_PREBUILT_TOOL_IMPLEMENTATION
    )
    repository_ctx.file(
        "prebuilt_tool.bzl",
        _PREBUILT_TOOL_BZL.replace(
            "{PREBUILT_TOOL_IMPLEMENTATION}",
            prebuilt_tool_implementation,
        ),
    )
    repository_ctx.file("bin/.keep", "")
    for name in sorted(tools.keys()):
        repository_ctx.symlink(
            repository_ctx.path(tools[name]),
            "bin/" + name + executable_suffix,
        )
    repository_ctx.file("host_dynamic_libraries/.keep", "")
    for name in sorted(host_dynamic_libraries.keys()):
        repository_ctx.symlink(
            repository_ctx.path(host_dynamic_libraries[name]),
            "host_dynamic_libraries/" + name,
        )
    repository_ctx.symlink(
        repository_ctx.path(clang_resource_include),
        "clang_resource_include",
    )
    if rocm_device_libraries:
        repository_ctx.symlink(
            repository_ctx.path(rocm_device_libraries),
            "hip_device_libraries",
        )
    repository_ctx.file(
        "BUILD.bazel",
        (_LOCAL_BUILD_TEMPLATE +
         (_ROCM_DEVICE_LIBRARIES_BUILD if rocm_device_libraries else ""))
            .replace("{EXECUTABLE_SUFFIX}", executable_suffix),
    )
    repository_ctx.file(
        "paths.bzl",
        _LOCAL_PATHS_TEMPLATE +
        (_ROCM_DEVICE_LIBRARIES_PATHS if rocm_device_libraries else _NO_ROCM_DEVICE_LIBRARIES_PATHS),
    )

def _amdgpu_device_toolchain_repo_impl(repository_ctx):
    mode = repository_ctx.getenv("IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN") or "none"
    if mode not in ["none", "auto", "rocm", "llvm-tools", "llvm-project"]:
        fail("Unknown IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN '{}'. Available: none, auto, rocm, llvm-tools, llvm-project.".format(mode))

    if mode == "none":
        _write_stub_repository(repository_ctx)
        return

    if mode == "llvm-project":
        repository_ctx.file("BUILD.bazel", _LLVM_PROJECT_BUILD)
        repository_ctx.file("paths.bzl", _LLVM_PROJECT_PATHS)
        return

    toolchain = discover_amdgpu_device_toolchain(repository_ctx, mode)
    if not toolchain.available:
        if mode == "auto":
            _write_stub_repository(repository_ctx, toolchain.error)
            return
        fail(toolchain.error)

    host_dynamic_libraries = {}
    if not _is_windows(repository_ctx):
        closure_result = try_resolve_elf_dynamic_library_closure(
            repository_ctx,
            toolchain.tools,
        )
        if closure_result.error:
            if mode == "auto":
                _write_stub_repository(repository_ctx, closure_result.error)
                return
            fail(closure_result.error)
        host_dynamic_libraries = closure_result.libraries

    _write_local_toolchain_repo(
        repository_ctx,
        toolchain.tools,
        host_dynamic_libraries,
        toolchain.clang_resource_include,
        toolchain.rocm_device_libraries,
    )

amdgpu_device_toolchain_repo = repository_rule(
    implementation = _amdgpu_device_toolchain_repo_impl,
    environ = [
        "CLANG",
        "HIP_PATH",
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN",
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_CLANG_BINARY",
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_LLVM_TOOLS_DIR",
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_ROCM_PATH",
        "IREE_HAL_AMDGPU_DEVICE_TOOLCHAIN_ROCM_DEVICE_LIB_PATH",
        "IREE_BINARY_DIR",
        "IREE_CLANG_BINARY",
        "IREE_HOST_BIN_DIR",
        "IREE_HOST_TOOLS",
        "IREE_HOST_TOOLS_DIR",
        "IREE_LLVM_TOOL_DIR",
        "IREE_LLVM_TOOLS_DIR",
        "IREE_ROCM_PATH",
        "LLVM_BINARY_DIR",
        "LLVM_TOOLS_BINARY_DIR",
        "PATH",
        "ROCM_HOME",
        "ROCM_PATH",
        "ROCM_ROOT",
    ],
    doc = "Exposes optional AMDGPU builtin device compiler tools.",
)
