// Generated by build_tools/amdgpu/target_map.py.
// Do not edit directly; edit the map in that script and regenerate.
// Output: build_tools/amdgpu/target_map.h

#ifndef IREE_BUILD_TOOLS_AMDGPU_TARGET_MAP_H_
#define IREE_BUILD_TOOLS_AMDGPU_TARGET_MAP_H_

#include <stddef.h>
#include <string.h>

static inline const char* iree_amdgpu_code_object_target_for_exact(
    const char* exact_target) {
  if (!exact_target) return NULL;
  if (strcmp(exact_target, "gfx900") == 0) return "gfx9-generic";
  if (strcmp(exact_target, "gfx902") == 0) return "gfx9-generic";
  if (strcmp(exact_target, "gfx904") == 0) return "gfx9-generic";
  if (strcmp(exact_target, "gfx90c") == 0) return "gfx9-generic";
  if (strcmp(exact_target, "gfx906") == 0) return "gfx9-generic";
  if (strcmp(exact_target, "gfx908") == 0) return "gfx908";
  if (strcmp(exact_target, "gfx909") == 0) return "gfx9-generic";
  if (strcmp(exact_target, "gfx90a") == 0) return "gfx90a";
  if (strcmp(exact_target, "gfx940") == 0) return "gfx9-4-generic";
  if (strcmp(exact_target, "gfx941") == 0) return "gfx9-4-generic";
  if (strcmp(exact_target, "gfx942") == 0) return "gfx9-4-generic";
  if (strcmp(exact_target, "gfx950") == 0) return "gfx9-4-generic";
  if (strcmp(exact_target, "gfx1010") == 0) return "gfx10-1-generic";
  if (strcmp(exact_target, "gfx1011") == 0) return "gfx10-1-generic";
  if (strcmp(exact_target, "gfx1012") == 0) return "gfx10-1-generic";
  if (strcmp(exact_target, "gfx1013") == 0) return "gfx10-1-generic";
  if (strcmp(exact_target, "gfx1030") == 0) return "gfx10-3-generic";
  if (strcmp(exact_target, "gfx1031") == 0) return "gfx10-3-generic";
  if (strcmp(exact_target, "gfx1032") == 0) return "gfx10-3-generic";
  if (strcmp(exact_target, "gfx1033") == 0) return "gfx10-3-generic";
  if (strcmp(exact_target, "gfx1034") == 0) return "gfx10-3-generic";
  if (strcmp(exact_target, "gfx1035") == 0) return "gfx10-3-generic";
  if (strcmp(exact_target, "gfx1036") == 0) return "gfx10-3-generic";
  if (strcmp(exact_target, "gfx1100") == 0) return "gfx11-generic";
  if (strcmp(exact_target, "gfx1101") == 0) return "gfx11-generic";
  if (strcmp(exact_target, "gfx1102") == 0) return "gfx11-generic";
  if (strcmp(exact_target, "gfx1103") == 0) return "gfx11-generic";
  if (strcmp(exact_target, "gfx1150") == 0) return "gfx11-generic";
  if (strcmp(exact_target, "gfx1151") == 0) return "gfx11-generic";
  if (strcmp(exact_target, "gfx1152") == 0) return "gfx11-generic";
  if (strcmp(exact_target, "gfx1153") == 0) return "gfx11-generic";
  if (strcmp(exact_target, "gfx1170") == 0) return "gfx1170";
  if (strcmp(exact_target, "gfx1171") == 0) return "gfx1171";
  if (strcmp(exact_target, "gfx1172") == 0) return "gfx1172";
  if (strcmp(exact_target, "gfx1200") == 0) return "gfx12-generic";
  if (strcmp(exact_target, "gfx1201") == 0) return "gfx12-generic";
  if (strcmp(exact_target, "gfx1250") == 0) return "gfx12-5-generic";
  if (strcmp(exact_target, "gfx1251") == 0) return "gfx12-5-generic";
  return NULL;
}

static inline int iree_amdgpu_target_label_fragment(const char* target,
                                                    char* buffer,
                                                    size_t capacity) {
  if (!target || !buffer || capacity == 0) return 0;
  size_t i = 0;
  for (; target[i] != '\0'; ++i) {
    if (i + 1 >= capacity) {
      buffer[0] = '\0';
      return 0;
    }
    const char c = target[i];
    buffer[i] = (c == '-' || c == '.') ? '_' : c;
  }
  buffer[i] = '\0';
  return 1;
}

#endif  // IREE_BUILD_TOOLS_AMDGPU_TARGET_MAP_H_
