# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""Repository rule exposing pinned wasi-sdk host tools."""

load(
    "//build_tools/wasm:wasi_sdk_version.bzl",
    "WASI_SDK_SHA256",
    "WASI_SDK_TAG",
    "WASI_SDK_URL_TEMPLATE",
    "WASI_SDK_VERSION",
)

_BUILD_TEMPLATE = """\
# AUTO-GENERATED by wasi_sdk_repo.bzl; do not edit.

load("@bazel_skylib//rules:copy_file.bzl", "copy_file")

package(default_visibility = ["//visibility:public"])

copy_file(
    name = "llvm-objdump",
    allow_symlink = __ALLOW_SYMLINK__,
    is_executable = True,
    out = "llvm-objdump__OUTPUT_SUFFIX__",
    src = "bin/llvm-objdump__SOURCE_SUFFIX__",
)
"""

def _detect_host_platform(repository_ctx):
    os_name = repository_ctx.os.name.lower()
    architecture = repository_ctx.os.arch

    if "linux" in os_name:
        os_key = "linux"
    elif "mac" in os_name or "darwin" in os_name:
        os_key = "macos"
    elif "windows" in os_name:
        os_key = "windows"
    else:
        fail("wasi-sdk: unsupported host OS: {}".format(os_name))

    if architecture in ("amd64", "x86_64"):
        architecture_key = "x86_64"
    elif architecture in ("aarch64", "arm64"):
        architecture_key = "arm64"
    else:
        fail("wasi-sdk: unsupported host architecture: {}".format(architecture))

    return architecture_key, os_key

def _wasi_sdk_repo_impl(repository_ctx):
    architecture, os = _detect_host_platform(repository_ctx)
    platform_key = "{}-{}".format(architecture, os)
    sha256 = WASI_SDK_SHA256.get(platform_key, "")
    if not sha256:
        fail("wasi-sdk: no SHA-256 digest for {}".format(platform_key))

    archive_prefix = "wasi-sdk-{}-{}-{}".format(
        WASI_SDK_VERSION,
        architecture,
        os,
    )
    rename_files = {}
    source_suffix = ""
    output_suffix = ".tool"
    allow_symlink = "True"
    if os == "windows":
        # Executing a repository PE through a symlink can update its NTFS
        # metadata, which makes Bazel treat the repository as modified. Keep
        # the repository input under a non-executable name and expose it
        # through an executable action-output copy instead.
        source_suffix = ".payload"
        output_suffix = ".exe"
        allow_symlink = "False"
        source_path = "{}/bin/llvm-objdump.exe".format(archive_prefix)
        rename_files[source_path] = "{}/bin/llvm-objdump{}".format(
            archive_prefix,
            source_suffix,
        )

    repository_ctx.download_and_extract(
        url = WASI_SDK_URL_TEMPLATE.format(
            tag = WASI_SDK_TAG,
            version = WASI_SDK_VERSION,
            arch = architecture,
            os = os,
        ),
        sha256 = sha256,
        rename_files = rename_files,
        strip_prefix = archive_prefix,
    )
    repository_ctx.file(
        "BUILD.bazel",
        _BUILD_TEMPLATE.replace("__ALLOW_SYMLINK__", allow_symlink)
            .replace("__OUTPUT_SUFFIX__", output_suffix)
            .replace("__SOURCE_SUFFIX__", source_suffix),
    )

wasi_sdk_repo = repository_rule(
    implementation = _wasi_sdk_repo_impl,
    doc = "Downloads a pinned wasi-sdk release and exposes its host tools.",
)
