# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""Repository rule exposing pinned wasi-sdk host tools."""

load(
    "//build_tools/wasm:wasi_sdk_version.bzl",
    "WASI_SDK_SHA256",
    "WASI_SDK_TAG",
    "WASI_SDK_URL_TEMPLATE",
    "WASI_SDK_VERSION",
)

_PREBUILT_TOOL_BZL = """\
\"\"\"Rule for exposing a prebuilt binary as an executable Bazel target.\"\"\"

def _prebuilt_tool_impl(ctx):
    output = ctx.actions.declare_file(ctx.label.name)
    ctx.actions.symlink(
        output = output,
        target_file = ctx.file.src,
        is_executable = True,
    )
    return [DefaultInfo(
        executable = output,
        files = depset([output]),
        runfiles = ctx.runfiles(files = [ctx.file.src]),
    )]

prebuilt_tool = rule(
    implementation = _prebuilt_tool_impl,
    executable = True,
    attrs = {
        "src": attr.label(
            allow_single_file = True,
            mandatory = True,
        ),
    },
)
"""

_BUILD_TEMPLATE = """\
# AUTO-GENERATED by wasi_sdk_repo.bzl; do not edit.

load(":prebuilt_tool.bzl", "prebuilt_tool")

package(default_visibility = ["//visibility:public"])

prebuilt_tool(
    name = "llvm-objdump",
    src = "bin/llvm-objdump",
)
"""

def _detect_host_platform(repository_ctx):
    os_name = repository_ctx.os.name.lower()
    architecture = repository_ctx.os.arch

    if "linux" in os_name:
        os_key = "linux"
    elif "mac" in os_name or "darwin" in os_name:
        os_key = "macos"
    else:
        fail("wasi-sdk: unsupported host OS: {}".format(os_name))

    if architecture in ("amd64", "x86_64"):
        architecture_key = "x86_64"
    elif architecture in ("aarch64", "arm64"):
        architecture_key = "arm64"
    else:
        fail("wasi-sdk: unsupported host architecture: {}".format(architecture))

    return architecture_key, os_key

def _wasi_sdk_repo_impl(repository_ctx):
    architecture, os = _detect_host_platform(repository_ctx)
    platform_key = "{}-{}".format(architecture, os)
    sha256 = WASI_SDK_SHA256.get(platform_key, "")
    if not sha256:
        fail("wasi-sdk: no SHA-256 digest for {}".format(platform_key))

    repository_ctx.download_and_extract(
        url = WASI_SDK_URL_TEMPLATE.format(
            tag = WASI_SDK_TAG,
            version = WASI_SDK_VERSION,
            arch = architecture,
            os = os,
        ),
        sha256 = sha256,
        stripPrefix = "wasi-sdk-{}-{}-{}".format(
            WASI_SDK_VERSION,
            architecture,
            os,
        ),
    )
    repository_ctx.file("prebuilt_tool.bzl", _PREBUILT_TOOL_BZL)
    repository_ctx.file("BUILD.bazel", _BUILD_TEMPLATE)

wasi_sdk_repo = repository_rule(
    implementation = _wasi_sdk_repo_impl,
    doc = "Downloads a pinned wasi-sdk release and exposes its host tools.",
)
