// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// GENERATED FILE: DO NOT EDIT.
// Regenerate with:
//   iree-bazel-run //runtime/src/iree/vm/bytecode/spec:generate
// HAL ISA page identity and opcode constants.
// Multi-byte fields are little-endian and naturally aligned.
// clang-format off
#ifndef IREE_VM_BYTECODE_GENERATED_WIRE_HAL_OPCODES_H_
#define IREE_VM_BYTECODE_GENERATED_WIRE_HAL_OPCODES_H_

#include <stdint.h>

typedef uint8_t iree_vm_isa_page_t;
enum {
  IREE_VM_ISA_PAGE_HAL = 0xF0,
};

enum {
  IREE_VM_ISA_HAL_MAJOR = 0,
  IREE_VM_ISA_HAL_MINOR = 0,
};

typedef uint8_t iree_vm_isa_hal_opcode_t;
enum {
  IREE_VM_ISA_HAL_OPCODE_DEVICE_GROUP_COUNT = 0x01,
  IREE_VM_ISA_HAL_OPCODE_DEVICE_GROUP_GET = 0x02,
  IREE_VM_ISA_HAL_OPCODE_BUFFER_ALLOCATE = 0x03,
  IREE_VM_ISA_HAL_OPCODE_BUFFER_MAP = 0x04,
  IREE_VM_ISA_HAL_OPCODE_BUFFER_UNMAP = 0x05,
  IREE_VM_ISA_HAL_OPCODE_SEMAPHORE_CREATE = 0x06,
  IREE_VM_ISA_HAL_OPCODE_SEMAPHORE_QUERY = 0x07,
  IREE_VM_ISA_HAL_OPCODE_SEMAPHORE_SIGNAL = 0x08,
  IREE_VM_ISA_HAL_OPCODE_SEMAPHORE_AWAIT = 0x09,
  IREE_VM_ISA_HAL_OPCODE_EXECUTABLE_LOAD = 0x0A,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_ALLOCA = 0x0B,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_DEALLOCA = 0x0C,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_FILL = 0x0D,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_UPDATE = 0x0E,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_COPY = 0x0F,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_READ = 0x10,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_WRITE = 0x11,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_DISPATCH = 0x12,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_DISPATCH_INDIRECT_COUNT = 0x13,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_EXECUTE = 0x14,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_BARRIER = 0x15,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_FLUSH = 0x16,
  IREE_VM_ISA_HAL_OPCODE_CMD_CREATE = 0x17,
  IREE_VM_ISA_HAL_OPCODE_CMD_FINALIZE = 0x18,
  IREE_VM_ISA_HAL_OPCODE_CMD_EXECUTION_BARRIER = 0x19,
  IREE_VM_ISA_HAL_OPCODE_CMD_ADVISE_BUFFER = 0x1A,
  IREE_VM_ISA_HAL_OPCODE_CMD_FILL_BUFFER = 0x1B,
  IREE_VM_ISA_HAL_OPCODE_CMD_UPDATE_BUFFER = 0x1C,
  IREE_VM_ISA_HAL_OPCODE_CMD_COPY_BUFFER = 0x1D,
  IREE_VM_ISA_HAL_OPCODE_CMD_COLLECTIVE = 0x1E,
  IREE_VM_ISA_HAL_OPCODE_CMD_DISPATCH = 0x1F,
  IREE_VM_ISA_HAL_OPCODE_CMD_DISPATCH_INDIRECT_COUNT = 0x20,
  IREE_VM_ISA_HAL_OPCODE_CMD_DEBUG_GROUP_BEGIN = 0x21,
  IREE_VM_ISA_HAL_OPCODE_CMD_DEBUG_GROUP_END = 0x22,
};

enum {
  IREE_VM_ISA_HAL_OPCODE_DEVICE_GROUP_COUNT_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_DEVICE_GROUP_GET_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_BUFFER_ALLOCATE_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_BUFFER_MAP_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_BUFFER_UNMAP_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_SEMAPHORE_CREATE_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_SEMAPHORE_QUERY_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_SEMAPHORE_SIGNAL_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_SEMAPHORE_AWAIT_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_EXECUTABLE_LOAD_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_ALLOCA_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_DEALLOCA_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_FILL_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_UPDATE_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_COPY_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_READ_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_WRITE_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_DISPATCH_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_DISPATCH_INDIRECT_COUNT_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_EXECUTE_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_BARRIER_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_QUEUE_FLUSH_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_CMD_CREATE_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_CMD_FINALIZE_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_CMD_EXECUTION_BARRIER_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_CMD_ADVISE_BUFFER_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_CMD_FILL_BUFFER_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_CMD_UPDATE_BUFFER_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_CMD_COPY_BUFFER_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_CMD_COLLECTIVE_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_CMD_DISPATCH_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_CMD_DISPATCH_INDIRECT_COUNT_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_CMD_DEBUG_GROUP_BEGIN_SINCE_MINOR = 0,
  IREE_VM_ISA_HAL_OPCODE_CMD_DEBUG_GROUP_END_SINCE_MINOR = 0,
};

#endif  // IREE_VM_BYTECODE_GENERATED_WIRE_HAL_OPCODES_H_
// clang-format on
