# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

package(default_visibility = ["//visibility:public"])

alias(
    name = "iree-benchmark-replay",
    actual = "//runtime/src/iree/tools/iree-benchmark-replay",
)

alias(
    name = "iree-dump-cpuinfo",
    actual = "//runtime/src/iree/tools/iree-dump-cpuinfo",
)

alias(
    name = "iree-dump-replay",
    actual = "//runtime/src/iree/tools/iree-dump-replay",
)

alias(
    name = "iree-profile",
    actual = "//runtime/src/iree/tools/iree-profile",
)

alias(
    name = "iree-run-replay",
    actual = "//runtime/src/iree/tools/iree-run-replay",
)
