# Copyright 2020 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//runtime/build_tools/bazel:cc.bzl", "iree_runtime_cc_library")
load("//runtime/build_tools/bazel:cc_test.bzl", "iree_runtime_cc_test")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

iree_runtime_cc_library(
    name = "buffer_view_matchers",
    srcs = ["buffer_view_matchers.c"],
    hdrs = ["buffer_view_matchers.h"],
    deps = [
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal",
        "//runtime/src/iree/hal",
    ],
)

iree_runtime_cc_test(
    name = "buffer_view_matchers_test",
    srcs = ["buffer_view_matchers_test.cc"],
    deps = [
        ":buffer_view_matchers",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal",
        "//runtime/src/iree/base/internal:span",
        "//runtime/src/iree/hal",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
    ],
)

iree_runtime_cc_library(
    name = "device_util",
    srcs = ["device_util.c"],
    hdrs = ["device_util.h"],
    deps = [
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal",
        "//runtime/src/iree/base/threading",
        "//runtime/src/iree/base/threading:thread",
        "//runtime/src/iree/base/tooling:flags",
        "//runtime/src/iree/hal",
        "//runtime/src/iree/hal/drivers",
        "//runtime/src/iree/hal/utils:mpi_channel_provider",
        "//runtime/src/iree/hal/utils:profile_file",
        "//runtime/src/iree/hal/utils:statistics_sink",
        "//runtime/src/iree/io:file_handle",
    ],
)

iree_runtime_cc_library(
    name = "value_io",
    srcs = ["value_io.c"],
    hdrs = ["value_io.h"],
    deps = [
        ":numpy_io",
        "//runtime/src/iree/base",
        "//runtime/src/iree/hal",
        "//runtime/src/iree/io:stream",
    ],
)

iree_runtime_cc_test(
    name = "value_io_test",
    srcs = ["value_io_test.cc"],
    tags = ["requires-filesystem"],
    deps = [
        ":value_io",
        "//runtime/src/iree/base",
        "//runtime/src/iree/hal",
        "//runtime/src/iree/io:file_handle",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
        "//runtime/src/iree/testing:temp_file",
    ],
)

iree_runtime_cc_library(
    name = "numpy_io",
    srcs = ["numpy_io.c"],
    hdrs = ["numpy_io.h"],
    deps = [
        "//runtime/src/iree/base",
        "//runtime/src/iree/hal",
        "//runtime/src/iree/io:stream",
    ],
)

iree_runtime_cc_test(
    name = "numpy_io_test",
    srcs = ["numpy_io_test.cc"],
    tags = ["requires-filesystem"],
    deps = [
        ":device_util",
        ":numpy_io",
        "//runtime/src/iree/async/util:proactor_pool",
        "//runtime/src/iree/base/threading",
        "//runtime/src/iree/io:stream",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
        "//runtime/src/iree/tooling/testdata/npy",
    ],
)

iree_runtime_cc_library(
    name = "parameter_util",
    srcs = ["parameter_util.c"],
    hdrs = ["parameter_util.h"],
    deps = [
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal:json",
        "//runtime/src/iree/base/internal:path",
        "//runtime/src/iree/base/tooling:flags",
        "//runtime/src/iree/io:file_handle",
        "//runtime/src/iree/io:parameter_index",
        "//runtime/src/iree/io:scope_map",
        "//runtime/src/iree/io/formats:parser_registry",
    ],
)

iree_runtime_cc_test(
    name = "parameter_util_test",
    srcs = ["parameter_util_test.cc"],
    tags = ["requires-filesystem"],
    deps = [
        ":parameter_util",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal:path",
        "//runtime/src/iree/io:file_handle",
        "//runtime/src/iree/io:parameter_index",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
        "//runtime/src/iree/testing:temp_file",
    ],
)
