# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//runtime/build_tools/bazel:cc.bzl", "iree_runtime_cc_library")
load("//runtime/build_tools/bazel:cc_test.bzl", "iree_runtime_cc_test")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

iree_runtime_cc_library(
    name = "queue",
    srcs = ["queue.c"],
    hdrs = ["queue.h"],
    deps = [
        "//runtime/src/iree/async",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal",
        "//runtime/src/iree/base/internal:arena",
        "//runtime/src/iree/base/internal:atomic_slist",
        "//runtime/src/iree/base/internal:cpu",
        "//runtime/src/iree/base/threading",
        "//runtime/src/iree/base/threading:thread",
        "//runtime/src/iree/hal",
        "//runtime/src/iree/hal/drivers/task:atomic",
        "//runtime/src/iree/hal/drivers/task:profile",
        "//runtime/src/iree/hal/drivers/task:transient_buffer",
        "//runtime/src/iree/hal/drivers/task/command:block_builder",
        "//runtime/src/iree/hal/drivers/task/command:block_command_buffer",
        "//runtime/src/iree/hal/drivers/task/command:block_command_ops",
        "//runtime/src/iree/hal/drivers/task/command:block_processor",
        "//runtime/src/iree/hal/drivers/task/executable",
        "//runtime/src/iree/hal/utils:files",
        "//runtime/src/iree/hal/utils:resource_set",
        "//runtime/src/iree/task",
    ],
)

iree_runtime_cc_test(
    name = "queue_test",
    srcs = ["queue_test.cc"],
    deps = [
        "//runtime/src/iree/async",
        "//runtime/src/iree/async/util:proactor_pool",
        "//runtime/src/iree/base",
        "//runtime/src/iree/hal",
        "//runtime/src/iree/hal/drivers/task:device",
        "//runtime/src/iree/task",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
    ],
)
