# Copyright 2020 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Default implementations for HAL types that use the host resources.
# These are generally just wrappers around host heap memory and host threads.

load("//runtime/build_tools/bazel:cc.bzl", "iree_runtime_cc_library")
load("//runtime/build_tools/bazel:cc_benchmark.bzl", "iree_runtime_cc_benchmark")
load("//runtime/build_tools/bazel:cc_test.bzl", "iree_runtime_cc_test")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

iree_runtime_cc_library(
    name = "atomic",
    srcs = ["atomic.c"],
    hdrs = ["atomic.h"],
    deps = [
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal",
        "//runtime/src/iree/base/threading",
        "//runtime/src/iree/hal",
    ],
)

iree_runtime_cc_test(
    name = "atomic_test",
    srcs = ["atomic_test.cc"],
    deps = [
        ":atomic",
        "//runtime/src/iree/base/internal",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
    ],
)

iree_runtime_cc_library(
    name = "cpu_device_spec",
    srcs = ["cpu_device_spec.c"],
    hdrs = ["cpu_device_spec.h"],
    deps = [
        "//runtime/src/iree/base",
        "//runtime/src/iree/base:core_headers",
        "//runtime/src/iree/base:cpu_data",
        "//runtime/src/iree/hal",
    ],
)

iree_runtime_cc_test(
    name = "cpu_device_spec_test",
    srcs = ["cpu_device_spec_test.cc"],
    deps = [
        ":cpu_device_spec",
        "//runtime/src/iree/base:core_headers",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
    ],
)

iree_runtime_cc_library(
    name = "device_spec_builder",
    srcs = ["device_spec_builder.c"],
    hdrs = ["device_spec_builder.h"],
    deps = [
        ":atomic",
        ":cpu_device_spec",
        ":executable_loader",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal:cpu",
        "//runtime/src/iree/hal",
        "//runtime/src/iree/hal/memory:cpu_slab_provider",
        "//runtime/src/iree/hal/utils:device_spec_builder",
    ],
)

iree_runtime_cc_test(
    name = "device_spec_builder_test",
    srcs = ["device_spec_builder_test.cc"],
    deps = [
        ":atomic",
        ":cpu_device_spec",
        ":device_spec_builder",
        "//runtime/src/iree/hal",
        "//runtime/src/iree/hal/local/loaders:static_library_loader",
        "//runtime/src/iree/hal/memory:cpu_slab_provider",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
    ],
)

iree_runtime_cc_library(
    name = "executable_data",
    srcs = ["executable_data.c"],
    hdrs = ["executable_data.h"],
    deps = [
        "//runtime/src/iree/base",
        "//runtime/src/iree/hal/utils:elf_format",
    ],
)

iree_runtime_cc_library(
    name = "executable_environment",
    srcs = ["executable_environment.c"],
    hdrs = ["executable_environment.h"],
    deps = [
        ":executable_library",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal:cpu",
        "//runtime/src/iree/hal",
    ],
)

iree_runtime_cc_library(
    name = "executable_library",
    hdrs = ["executable_library.h"],
)

iree_runtime_cc_benchmark(
    name = "executable_library_benchmark",
    srcs = ["executable_library_benchmark.c"],
    deps = [
        ":device_spec_builder",
        ":executable_environment",
        ":executable_library",
        ":executable_loader",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/tooling:flags",
        "//runtime/src/iree/hal",
        "//runtime/src/iree/hal/local/loaders/registration",
        "//runtime/src/iree/hal/local/plugins/registration",
        "//runtime/src/iree/io:file_handle",
        "//runtime/src/iree/testing:benchmark",
    ],
)

iree_runtime_cc_test(
    name = "executable_library_test",
    srcs = [
        "executable_library_demo.c",
        "executable_library_demo.h",
        "executable_library_test.c",
    ],
    deps = [
        ":executable_environment",
        ":executable_library",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal:cpu",
    ],
)

iree_runtime_cc_library(
    name = "executable_library_util",
    srcs = ["executable_library_util.c"],
    hdrs = ["executable_library_util.h"],
    deps = [
        ":executable_environment",
        ":executable_library",
        ":executable_loader",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal",
        "//runtime/src/iree/hal",
    ],
)

iree_runtime_cc_library(
    name = "executable_loader",
    srcs = [
        "executable_loader.c",
        "local_executable.c",
    ],
    hdrs = [
        "executable_loader.h",
        "local_executable.h",
    ],
    deps = [
        ":executable_environment",
        ":executable_library",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal",
        "//runtime/src/iree/hal",
    ],
)

iree_runtime_cc_test(
    name = "executable_library_util_test",
    srcs = ["executable_library_util_test.cc"],
    deps = [
        ":executable_library_util",
        "//runtime/src/iree/base",
        "//runtime/src/iree/hal",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
    ],
)

iree_runtime_cc_library(
    name = "executable_plugin",
    hdrs = ["executable_plugin.h"],
)

iree_runtime_cc_library(
    name = "executable_plugin_manager",
    srcs = ["executable_plugin_manager.c"],
    hdrs = ["executable_plugin_manager.h"],
    deps = [
        ":executable_loader",
        ":executable_plugin",
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/internal",
        "//runtime/src/iree/base/threading",
        "//runtime/src/iree/hal",
    ],
)

iree_runtime_cc_test(
    name = "executable_plugin_test",
    srcs = ["executable_plugin_test.cc"],
    deps = [
        ":executable_plugin",
        ":executable_plugin_manager",
        "//runtime/src/iree/base",
        "//runtime/src/iree/hal/local/plugins:static_plugin",
        "//runtime/src/iree/testing:gtest",
        "//runtime/src/iree/testing:gtest_main",
    ],
)
