# Copyright 2020 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//build_tools/bazel:select.bzl", "iree_select")
load("//runtime/build_tools/bazel:cc.bzl", "iree_runtime_cc_library")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

iree_runtime_cc_library(
    name = "drivers",
    srcs = ["init.c"],
    hdrs = ["init.h"],
    deps = (
        [
            "//runtime/src/iree/base",
            "//runtime/src/iree/hal",
        ] + iree_select({
            "//runtime/config/hal:driver_amdgpu": [
                "//runtime/src/iree/hal/drivers/amdgpu/registration",
            ],
            "//conditions:default": [],
        }) +
        iree_select({
            "//runtime/config/hal:driver_task": [
                "//runtime/src/iree/hal/drivers/task/registration",
            ],
            "//conditions:default": [],
        }) +
        iree_select({
            "//runtime/config/hal:driver_vulkan": [
                "//runtime/src/iree/hal/drivers/vulkan/registration",
            ],
            "//conditions:default": [],
        }) +
        iree_select({
            "//runtime/config/hal:driver_webgpu": [
                "//runtime/src/iree/hal/drivers/webgpu/registration",
            ],
            "//conditions:default": [],
        })
    ),
)
