# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//libamdf/build_tools/bazel:cc.bzl", "amdf_cc_library")
load("//libamdf/build_tools/bazel:cc_test.bzl", "amdf_cc_test")

package(
    default_visibility = ["//visibility:private"],
    features = ["layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

amdf_cc_library(
    name = "bootstrap",
    hdrs = ["bootstrap.h"],
    visibility = ["//libamdf/src/xdna:__subpackages__"],
)

amdf_cc_library(
    name = "transaction_interpreter",
    srcs = ["transaction_interpreter.c"],
    hdrs = ["transaction_interpreter.h"],
    visibility = ["//libamdf/src/xdna:__subpackages__"],
)

amdf_cc_library(
    name = "endpoint_profile",
    srcs = ["endpoint_profile.c"],
    hdrs = ["endpoint_profile.h"],
    visibility = [
        "//libamdf/src/provider:__pkg__",
        "//libamdf/src/xdna:__subpackages__",
    ],
    deps = [
        ":bootstrap",
        "//libamdf/src/xdna/target/npu4:bootstrap",
        "//libamdf/src/xdna/target/npu5:bootstrap",
    ],
)

amdf_cc_library(
    name = "device",
    srcs = [
        "device.c",
        "memory.c",
    ],
    hdrs = [
        "device.h",
        "memory.h",
    ],
    deps = [
        ":endpoint_profile",
        "//libamdf/src:allocator",
        "//libamdf/src:device",
        "//libamdf/src:endpoint",
        "//libamdf/src:host_mapping",
        "//libamdf/src:memory",
        "//libamdf/src:memory_profile",
        "//libamdf/src:memory_scope_state",
        "//libamdf/src:structure",
        "//libamdf/src/xdna/umd:context",
        "//libamdf/src/xdna/umd:device",
        "//libamdf/src/xdna/umd:memory",
    ],
)

amdf_cc_library(
    name = "context",
    srcs = ["context.c"],
    hdrs = ["context.h"],
    deps = [
        ":device",
        ":endpoint_profile",
        "//libamdf/src:allocator",
        "//libamdf/src:child_tracker",
        "//libamdf/src:device",
        "//libamdf/src:structure",
        "//libamdf/src/xdna/umd:context",
    ],
)

amdf_cc_library(
    name = "kernel_queue",
    srcs = ["kernel_queue.c"],
    hdrs = ["kernel_queue.h"],
    deps = [
        ":context",
        ":device",
        "//libamdf/src:allocator",
        "//libamdf/src:atomics",
        "//libamdf/src:device",
        "//libamdf/src:endpoint",
        "//libamdf/src:kernel_queue",
        "//libamdf/src:memory",
        "//libamdf/src:memory_resource",
        "//libamdf/src:memory_scope_state",
        "//libamdf/src:structure",
        "//libamdf/src:wait",
        "//libamdf/src/platform:wait",
        "//libamdf/src/xdna/umd:kernel_queue",
    ],
)

amdf_cc_library(
    name = "extension",
    srcs = ["extension.c"],
    hdrs = ["extension.h"],
    visibility = ["//libamdf/src/provider:__pkg__"],
    deps = [
        ":context",
        ":device",
        ":endpoint_profile",
        ":kernel_queue",
        "//libamdf/src:endpoint",
        "//libamdf/src:structure",
        "//libamdf/src/platform",
        "//libamdf/src/xdna/umd:device",
        "//libamdf/src/xdna/umd:memory_profile",
    ],
)

amdf_cc_library(
    name = "xdna",
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "@platforms//os:windows": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    visibility = ["//libamdf/src/provider:__pkg__"],
    deps = [":extension"] + select({
        "@platforms//os:linux": ["//libamdf/src/xdna/umd/drm"],
        "@platforms//os:windows": ["//libamdf/src/xdna/umd/mcdm"],
        "//conditions:default": [],
    }),
)

amdf_cc_test(
    name = "endpoint_profile_test",
    srcs = ["endpoint_profile_test.cc"],
    deps = [
        ":endpoint_profile",
        "//third_party:google_test",
        "//third_party:google_test_main",
    ],
)

amdf_cc_test(
    name = "transaction_interpreter_test",
    srcs = ["transaction_interpreter_test.cc"],
    deps = [
        ":transaction_interpreter",
        "//third_party:google_test",
        "//third_party:google_test_main",
    ],
)

amdf_cc_test(
    name = "kernel_queue_test",
    srcs = ["kernel_queue_test.cc"],
    deps = [
        ":context",
        ":device",
        ":endpoint_profile",
        ":kernel_queue",
        "//libamdf/src:allocator",
        "//libamdf/src:child_tracker",
        "//libamdf/src:device",
        "//libamdf/src:endpoint",
        "//libamdf/src:kernel_queue",
        "//libamdf/src:memory_resource",
        "//libamdf/src:memory_scope_state",
        "//libamdf/src/xdna/umd:kernel_queue",
        "//third_party:google_test",
        "//third_party:google_test_main",
    ],
)
