# Copyright 2026 The HRX Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Presubmit

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - main-staging

permissions:
  contents: read

jobs:
  presubmit:
    name: Linux / Presubmit
    runs-on: aws-linux-scale-rocm-prod
    timeout-minutes: 45
    container:
      image: ghcr.io/rocm/therock_build_manylinux_x86_64@sha256:702a5133851e6d1daf1207d2c9fbb01c2667914a5b6dc5a01faeb3ce66ea6421
    env:
      PIP_CACHE_DIR: ${{ github.workspace }}/build/presubmit/caches/pip
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Adjust git config
        run: git config --global --add safe.directory "$PWD"

      - name: Install developer tools
        run: |
          python3 --version
          python3 dev.py bazel setup --venv
          .venv/bin/python -m pip install semgrep==1.164.0
          echo "$PWD/.venv/bin" >> "$GITHUB_PATH"

      - name: Check tool versions
        run: python3 dev.py bazel doctor

      - name: Run presubmit
        run: python3 dev.py bazel presubmit --profile ci --no-project-tests
