# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//runtime/build_tools/bazel:cc.bzl", "iree_runtime_cc_library")
load("//runtime/build_tools/bazel:hal_cts.bzl", "iree_runtime_hal_cts_test_suite")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = ["notice"],
)

_AMDXDNA_COMPATIBLE_WITH = select({
    "@platforms//os:linux": [],
    "@platforms//os:windows": [],
    "//conditions:default": ["@platforms//:incompatible"],
})

iree_runtime_cc_library(
    name = "backends",
    testonly = True,
    srcs = ["backends.cc"],
    target_compatible_with = _AMDXDNA_COMPATIBLE_WITH,
    deps = [
        "//runtime/src/iree/async/util:proactor_pool",
        "//runtime/src/iree/base/threading",
        "//runtime/src/iree/hal",
        "//runtime/src/iree/hal/cts/util:registry",
        "//runtime/src/iree/hal/drivers/amdxdna/registration",
    ],
    alwayslink = True,
)

iree_runtime_hal_cts_test_suite(
    backends = ":backends",
    resource_group = "iree-hal-drivers-amdxdna-tests",
    tags = [
        "driver=amdxdna",
        "iree-build-requirement=runtime.hal.amdxdna",
        "iree-run-requirement=runtime.resource.amd_npu",
        "runtime-resource=amd-npu",
    ],
    target_compatible_with = _AMDXDNA_COMPATIBLE_WITH,
)
